(function(){
  'use strict';
  const A=window.AlMezan,S=A.state,$=A.$,esc=A.esc,num=A.num,I=A.I,D=()=>A.db;
  const action=(id,label,icon='plus',cls='btn-primary',attrs='')=>`<button class="btn ${cls}" data-action="${id}" ${attrs}>${I(icon)}${esc(label)}</button>`;
  const iconBtn=(id,icon,title,attrs='')=>`<button class="icon-button" data-action="${id}" title="${esc(title)}" ${attrs}>${I(icon)}</button>`;

  function ensureAdvancedDB(){
    const d=D();
    ['chatGroups','installmentContracts','installmentSchedule','messageTemplates','customerMessages'].forEach(k=>{if(!Array.isArray(d[k]))d[k]=[]});
    if(!d.settings.companyUsername)d.settings.companyUsername='12345';
    const accounts=[
      {id:'ACC-2400',code:'2400',name:'أرباح تقسيط مؤجلة',type:'liability',parentId:'ACC-2000',level:1},
      {id:'ACC-4200',code:'4200',name:'أرباح تقسيط محققة',type:'revenue',parentId:'ACC-4000',level:1}
    ];
    accounts.forEach(a=>{if(!d.accounts.some(x=>x.id===a.id))d.accounts.push(a)});
    const defaults=[
      {id:'TPL-INSTALLMENT-DUE',name:'تذكير قسط مستحق',channel:'all',body:'عزيزي {customer}، نذكرك بموعد سداد القسط رقم {installment_no} بقيمة {amount} بتاريخ {due_date}. شكراً لتعاملك معنا.',system:true},
      {id:'TPL-BALANCE',name:'تذكير رصيد عميل',channel:'all',body:'مرحباً {customer}، الرصيد المستحق على حسابكم هو {amount}. نرجو التواصل معنا لتسوية الرصيد.',system:true},
      {id:'TPL-THANKS',name:'شكر بعد الشراء',channel:'whatsapp',body:'شكراً لك {customer} على ثقتك بنا. يسعدنا خدمتك دائماً.',system:true}
    ];
    defaults.forEach(t=>{if(!d.messageTemplates.some(x=>x.id===t.id))d.messageTemplates.push({...t,createdAt:A.now()})});
    A.saveDB();
  }
  ensureAdvancedDB();

  // Keep nav/page metadata idempotent when upgrading older saved copies.
  const salesGroup=A.NAV.find(g=>g.title==='المبيعات والمشتريات');
  if(salesGroup&&!salesGroup.items.some(x=>x[0]==='installments'))salesGroup.items.push(['installments','calendar','الأقساط','installments']);
  const partiesGroup=A.NAV.find(g=>g.title==='الأطراف');
  if(partiesGroup&&!partiesGroup.items.some(x=>x[0]==='messaging'))partiesGroup.items.push(['messaging','chat','رسائل العملاء','messaging']);
  if(!A.PAGE_META.installments)A.PAGE_META.installments=['الأقساط',''];
  if(!A.PAGE_META.messaging)A.PAGE_META.messaging=['رسائل العملاء',''];

  // ---------- Chat: private + employee groups ----------
  function chatUsers(){return D().employees.filter(x=>x.active)}
  function userName(id){return D().employees.find(x=>x.id===id)?.name||'مستخدم'}
  function canSeeGroup(g,me){return me.system||(g.memberIds||[]).includes(me.id)||g.createdBy===me.id}
  function openChatGroup(group=null){
    const d=D(),me=A.currentUser(),people=chatUsers().filter(x=>x.id!==me.id);
    if(!A.has('chat_groups')&&!me.system)return A.toast('لا تملك صلاحية إنشاء مجموعات دردشة.','error');
    A.openModal({title:group?'تعديل مجموعة الدردشة':'إنشاء مجموعة موظفين',size:'modal-lg',body:`<div class="form-grid"><label class="field full"><span>اسم المجموعة</span><input name="name" required value="${esc(group?.name||'')}"></label></div><section class="form-section"><div class="form-section-title"><h4>أعضاء المجموعة</h4><small>سيتم إضافة منشئ المجموعة تلقائياً</small></div><div class="permissions-grid">${people.map(p=>`<label class="permission-item"><input type="checkbox" name="member" value="${p.id}" ${(group?.memberIds||[]).includes(p.id)?'checked':''}><span>${esc(p.name)} — ${esc(p.role||'موظف')}</span></label>`).join('')}</div></section>`,onSubmit:fd=>{
      const name=fd.get('name').trim();if(!name)throw Error('اكتب اسم المجموعة.');const memberIds=[...new Set([me.id,...fd.getAll('member')])];
      const target=group||{id:A.uid('CHATG'),createdBy:me.id,createdAt:A.now()};Object.assign(target,{name,memberIds,updatedAt:A.now()});if(!group)d.chatGroups.push(target);A.audit(group?'تعديل مجموعة دردشة':'إنشاء مجموعة دردشة','الدردشة',name);A.saveDB();S.chatMode='group';S.chatGroupId=target.id;A.renderCurrent()
    }})
  }
  function renderChatPro(root){
    const d=D(),me=A.currentUser(),contacts=chatUsers().filter(x=>x.id!==me.id),groups=d.chatGroups.filter(g=>canSeeGroup(g,me));
    S.chatMode=S.chatMode||'private';
    if(S.chatMode==='private'&&!contacts.some(x=>x.id===S.chatToId))S.chatToId=contacts[0]?.id||'';
    if(S.chatMode==='group'&&!groups.some(x=>x.id===S.chatGroupId))S.chatGroupId=groups[0]?.id||'';
    const privateMode=S.chatMode!=='group',target=privateMode?contacts.find(x=>x.id===S.chatToId):groups.find(x=>x.id===S.chatGroupId);
    const msgs=d.messages.filter(m=>privateMode?(!m.groupId&&((m.fromId===me.id&&m.toId===target?.id)||(m.fromId===target?.id&&m.toId===me.id))):(m.groupId===target?.id)).slice(-200);
    root.innerHTML=`${A.pageHead('الدردشة الداخلية','',A.has('chat_groups')||me.system?action('create-chat-group','مجموعة جديدة','plus'): '')}<div class="chat-pro-shell"><aside class="chat-pro-side"><div class="chat-mode-tabs"><button class="${privateMode?'active':''}" data-action="chat-mode" data-mode="private">${I('customer',15)} خاص</button><button class="${!privateMode?'active':''}" data-action="chat-mode" data-mode="group">${I('employees',15)} مجموعات</button></div><div class="chat-list">${privateMode?contacts.map(c=>`<button class="chat-list-item ${c.id===target?.id?'active':''}" data-action="chat-contact" data-id="${c.id}"><span class="avatar">${esc(c.name.slice(0,1))}</span><span><b>${esc(c.name)}</b><small>${esc(c.role||'موظف')}</small></span></button>`).join(''):groups.map(g=>`<button class="chat-list-item ${g.id===target?.id?'active':''}" data-action="chat-group" data-id="${g.id}"><span class="chat-group-icon">${I('employees',17)}</span><span><b>${esc(g.name)}</b><small>${(g.memberIds||[]).length} أعضاء</small></span></button>`).join('')}</div></aside><section class="chat-pro-room"><header class="chat-room-head"><div><b>${esc(target?.name||'اختر محادثة')}</b><small>${privateMode?esc(target?.role||''):(target?.memberIds||[]).map(userName).join('، ')}</small></div>${!privateMode&&target&&(target.createdBy===me.id||me.system)?iconBtn('edit-chat-group','edit','تعديل المجموعة',`data-id="${target.id}"`):''}</header><div class="chat-messages chat-pro-messages">${msgs.length?msgs.map(m=>`<div class="chat-bubble ${m.fromId===me.id?'mine':''}">${!privateMode?`<b>${esc(userName(m.fromId))}</b>`:''}<span>${esc(m.text)}</span><small>${A.dateFmt(m.createdAt,true)}</small></div>`).join(''):`<div class="chat-empty">${I('chat',26)}<span>ابدأ المحادثة</span></div>`}</div><form id="chatForm" class="chat-composer"><input id="chatText" autocomplete="off" placeholder="اكتب رسالة..." ${target?'':'disabled'}><button class="btn btn-primary" type="submit" ${target?'':'disabled'}>${I('arrow')} إرسال</button></form></section></div>`;
    $('#chatForm')?.addEventListener('submit',e=>{e.preventDefault();const text=$('#chatText').value.trim();if(!text||!target)return;d.messages.push({id:A.uid('MSG'),fromId:me.id,toId:privateMode?target.id:'',groupId:privateMode?'':target.id,text,createdAt:A.now()});A.saveDB();A.renderCurrent()});
    setTimeout(()=>{const el=$('.chat-pro-messages');if(el)el.scrollTop=el.scrollHeight},0)
  }
  A.registerView('chat',renderChatPro);
  A.registerAction('chat-mode',b=>{S.chatMode=b.dataset.mode;A.renderCurrent()});
  A.registerAction('chat-contact',b=>{S.chatMode='private';S.chatToId=b.dataset.id;A.renderCurrent()});
  A.registerAction('chat-group',b=>{S.chatMode='group';S.chatGroupId=b.dataset.id;A.renderCurrent()});
  A.registerAction('create-chat-group',()=>openChatGroup());
  A.registerAction('edit-chat-group',b=>openChatGroup(D().chatGroups.find(x=>x.id===b.dataset.id)));

  // ---------- Installments ----------
  const addDate=(date,frequency,n)=>{const d=new Date(date+'T12:00:00');if(frequency==='weekly')d.setDate(d.getDate()+7*n);else d.setMonth(d.getMonth()+n);return d.toISOString().slice(0,10)};
  function firstOutstanding(contract){return D().installmentSchedule.filter(x=>x.contractId===contract.id&&x.status!=='paid'&&x.status!=='cancelled').sort((a,b)=>num(a.installmentNo)-num(b.installmentNo))[0]||null}
  function updateScheduleStatuses(){const today=A.today();for(const x of D().installmentSchedule){if(x.status==='paid'||x.status==='cancelled')continue;x.status=num(x.paidAmount)>0?'partial':x.dueDate<today?'overdue':'pending'}}
  function installmentSale(){
    const d=D(),t=A.cashierTotals?.(),customer=A.cashierSelectedCustomer?.(),wh=A.cashierActiveWarehouse?.();if(!t||!S.cart.length)return A.toast('السلة فارغة.','warning');if(!customer||customer.system)return A.toast('بيع الأقساط يحتاج اختيار عميل مسجل.','warning');if(!A.has('installments')&&!A.currentUser()?.system)return A.toast('لا تملك صلاحية الأقساط.','error');
    for(const c of t.lines){if(c.p.trackStock!==false&&A.stockQty(c.p.id,wh.id)+1e-8<c.baseQty)return A.toast(`الرصيد غير كافٍ للصنف ${c.p.name}.`,'error')}
    const accountId=S.cashierAccountId||d.settings.defaultAccountId||A.paymentAccounts()[0]?.id||'ACC-1110',defaultFirst=addDate(S.cashierInvoiceDate||A.today(),'monthly',1);
    A.openModal({title:'بيع بالتقسيط',size:'modal-lg',body:`<div class="installment-kpis"><div><small>سعر الكاش</small><b>${A.money(t.total)}</b></div><div><small>العميل</small><b>${esc(customer.name)}</b></div></div><div class="form-grid cols-3"><label class="field"><span>الدفعة الأولى</span><input name="downPayment" id="instDown" type="number" min="0" max="${t.total}" step="0.01" value="0"></label><label class="field"><span>نسبة المرابحة %</span><input name="markupRate" id="instMarkup" type="number" min="0" step="0.01" value="0"></label><label class="field"><span>عدد الأقساط</span><input name="count" id="instCount" type="number" min="1" max="120" step="1" value="12"></label><label class="field"><span>الدورية</span><select name="frequency" id="instFrequency"><option value="monthly">شهري</option><option value="weekly">أسبوعي</option></select></label><label class="field"><span>أول استحقاق</span><input name="firstDueDate" id="instFirstDue" type="date" value="${defaultFirst}"></label><label class="field"><span>حساب الدفعة الأولى</span><select name="accountId">${A.paymentAccounts().map(a=>`<option value="${a.id}" ${a.id===accountId?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label></div><div id="installmentPreview" class="installment-preview"></div>`,submitText:'حفظ العقد وترحيل البيع',submitIcon:'check',onSubmit:fd=>{
      const cashTotal=Number(t.total.toFixed(2)),down=Math.max(0,num(fd.get('downPayment'))),markupRate=Math.max(0,num(fd.get('markupRate'))),markup=Number((cashTotal*markupRate/100).toFixed(2)),grand=Number((cashTotal+markup).toFixed(2)),financed=Number((grand-down).toFixed(2)),count=Math.max(1,Math.floor(num(fd.get('count')))),frequency=fd.get('frequency'),firstDue=fd.get('firstDueDate'),payAccount=fd.get('accountId')||accountId;if(down>grand+.009)throw Error('الدفعة الأولى أكبر من إجمالي التقسيط.');if(financed<=0)throw Error('لا يوجد رصيد متبقٍ للتقسيط.');
      const limit=A.customerCreditLimit?.(customer)||num(customer.creditLimit);if(limit>0&&num(customer.balance)+financed>limit)throw Error('العقد يتجاوز الحد الائتماني للعميل.');
      const number=A.nextNo('sale',(d.settings.invoicePrefix||'INV')+'-'),lines=t.lines.map((c,i)=>({productId:c.p.id,productName:c.p.name,unitId:c.u.id,unitName:c.u.name,factor:c.u.factor,qty:num(S.cart[i].qty),baseQty:c.baseQty,unitPrice:num(S.cart[i].unitPrice),discount:Number((c.discount+num(c.orderDiscountShare)).toFixed(2)),taxRate:c.rate,tax:c.tax,total:c.total,unitCost:c.p.trackStock===false?0:num(c.p.cost),costTotal:c.p.trackStock===false?0:c.baseQty*num(c.p.cost),trackStock:c.p.trackStock!==false})),costTotal=lines.reduce((a,l)=>a+num(l.costTotal),0),rep=d.representatives.find(r=>r.id===S.cashierRepId),commissionAmount=rep?Number(((cashTotal-t.tax)*num(rep.commission)/100).toFixed(2)):0;
      const sale={id:A.uid('INV'),number,date:S.cashierInvoiceDate||A.today(),createdAt:A.now(),branchId:S.activeBranchId,warehouseId:wh.id,customerId:customer.id,customerName:customer.name,representativeId:rep?.id||'',representativeName:rep?.name||'',commissionAmount,taxId:S.cashierTaxId,taxName:A.cashierSelectedTax?.()?.name||'ضريبة الصنف',userId:A.currentUser().id,userName:A.currentUser().name,lines,subtotal:t.subtotal,discount:t.discount,tax:t.tax,cashTotal,total:grand,installmentMarkup:markup,installmentMarkupRate:markupRate,paid:down,due:financed,payments:down>0?[{accountId:payAccount,amount:down}]:[],paymentMethod:'installment',paymentMethodLabel:'أقساط',costTotal,status:'installment'};
      d.sales.unshift(sale);lines.forEach(l=>{if(l.trackStock)A.adjustStock(l.productId,wh.id,-l.baseQty)});customer.balance=Number((num(customer.balance)+financed).toFixed(2));
      A.postJournal(`فاتورة تقسيط ${number}`,number,[{accountId:payAccount,debit:down,credit:0},{accountId:'ACC-1200',debit:financed,credit:0},{accountId:'ACC-4100',debit:0,credit:Number((cashTotal-t.tax).toFixed(2))},{accountId:'ACC-2200',debit:0,credit:Number(t.tax.toFixed(2))},{accountId:'ACC-2400',debit:0,credit:markup}],sale.date,true);if(costTotal>0)A.postJournal(`تكلفة مبيعات ${number}`,number,[{accountId:'ACC-5100',debit:costTotal,credit:0},{accountId:'ACC-1300',debit:0,credit:costTotal}],sale.date,true);
      if(rep&&commissionAmount>0){const repAcc=A.ensureRepAccount(rep);rep.balance=Number((num(rep.balance)+commissionAmount).toFixed(2));A.postJournal(`عمولة مندوب ${rep.name} - ${number}`,number,[{accountId:'ACC-5500',debit:commissionAmount,credit:0},{accountId:repAcc,debit:0,credit:commissionAmount}],sale.date,true)}
      const contract={id:A.uid('INST'),number:`INS-${String(d.installmentContracts.length+1).padStart(6,'0')}`,saleId:sale.id,saleNumber:number,customerId:customer.id,customerName:customer.name,cashTotal,markupRate,markupAmount:markup,total:grand,downPayment:down,financed,count,frequency,firstDueDate:firstDue,outstanding:financed,deferredProfitRemaining:markup,status:'active',payments:[],createdAt:A.now(),userId:A.currentUser().id};d.installmentContracts.unshift(contract);
      let allocated=0;for(let i=1;i<=count;i++){const amount=i===count?Number((financed-allocated).toFixed(2)):Number((financed/count).toFixed(2));allocated+=amount;d.installmentSchedule.push({id:A.uid('INSTROW'),contractId:contract.id,installmentNo:i,dueDate:i===1?firstDue:addDate(firstDue,frequency,i-1),dueAmount:amount,paidAmount:0,status:'pending'})}
      A.audit('بيع بالتقسيط','الأقساط',`${number} — ${customer.name} — ${grand}`);A.saveDB();A.cashierResetAfterSale?.();A.toast(`تم إنشاء عقد الأقساط ${contract.number}`);A.navigate('installments')
    },afterOpen:form=>{const preview=$('#installmentPreview',form),calc=()=>{const down=num($('#instDown',form).value),rate=num($('#instMarkup',form).value),count=Math.max(1,num($('#instCount',form).value)),markup=t.total*rate/100,grand=t.total+markup,remain=Math.max(0,grand-down);preview.innerHTML=`<div><span>المرابحة</span><b>${A.money(markup)}</b></div><div><span>إجمالي التقسيط</span><b>${A.money(grand)}</b></div><div><span>المتبقي</span><b>${A.money(remain)}</b></div><div><span>القسط التقريبي</span><b>${A.money(remain/count)}</b></div>`};['instDown','instMarkup','instCount'].forEach(id=>$('#'+id,form).oninput=calc);calc()}})
  }
  function payInstallment(contract){
    updateScheduleStatuses();const d=D(),row=firstOutstanding(contract);if(!row)return A.toast('لا يوجد قسط مستحق غير مسدد.','success');const remaining=Number((num(row.dueAmount)-num(row.paidAmount)).toFixed(2)),customer=d.customers.find(x=>x.id===contract.customerId),defaultAccount=d.settings.defaultAccountId||A.paymentAccounts()[0]?.id||'ACC-1110';
    A.openModal({title:`تحصيل القسط ${row.installmentNo} — ${contract.customerName}`,body:`<div class="installment-kpis"><div><small>الاستحقاق</small><b>${A.dateFmt(row.dueDate)}</b></div><div><small>المتبقي على القسط</small><b>${A.money(remaining)}</b></div></div><div class="form-grid"><label class="field"><span>المبلغ المحصل</span><input name="amount" type="number" min="0.01" max="${remaining}" step="0.01" value="${remaining}"></label><label class="field"><span>الحساب</span><select name="accountId">${A.paymentAccounts().map(a=>`<option value="${a.id}" ${a.id===defaultAccount?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label><label class="field full"><span>ملاحظات</span><input name="notes"></label></div>`,submitText:'تحصيل وترحيل',onSubmit:fd=>{const amount=num(fd.get('amount'));if(amount<=0||amount>remaining+.009)throw Error('قيمة التحصيل غير صالحة.');const accountId=fd.get('accountId')||defaultAccount;A.postJournal(`تحصيل قسط ${contract.number}/${row.installmentNo}`,contract.number,[{accountId,debit:amount,credit:0},{accountId:'ACC-1200',debit:0,credit:amount}],A.today(),true);const realized=Math.min(num(contract.deferredProfitRemaining),contract.financed>0?num(contract.markupAmount)*amount/num(contract.financed):0);if(realized>.009)A.postJournal(`تحقيق أرباح قسط ${contract.number}/${row.installmentNo}`,contract.number,[{accountId:'ACC-2400',debit:Number(realized.toFixed(2)),credit:0},{accountId:'ACC-4200',debit:0,credit:Number(realized.toFixed(2))}],A.today(),true);row.paidAmount=Number((num(row.paidAmount)+amount).toFixed(2));row.status=row.paidAmount+0.009>=num(row.dueAmount)?'paid':'partial';row.lastPaidAt=A.now();contract.outstanding=Number((num(contract.outstanding)-amount).toFixed(2));contract.deferredProfitRemaining=Number(Math.max(0,num(contract.deferredProfitRemaining)-realized).toFixed(2));contract.payments.push({id:A.uid('INSPAY'),scheduleId:row.id,installmentNo:row.installmentNo,amount,accountId,realizedProfit:Number(realized.toFixed(2)),date:A.today(),notes:fd.get('notes'),createdAt:A.now()});if(customer)customer.balance=Number((num(customer.balance)-amount).toFixed(2));if(contract.outstanding<=.009)contract.status='paid';A.audit('تحصيل قسط','الأقساط',`${contract.number}/${row.installmentNo} — ${amount}`);A.saveDB();A.toast('تم تحصيل القسط وترحيله');A.renderCurrent()}})
  }
  function reverseInstallment(contract){
    const d=D(),sale=d.sales.find(x=>x.id===contract.saleId),customer=d.customers.find(x=>x.id===contract.customerId);if(!sale)return;
    for(const p of [...(contract.payments||[])].reverse()){A.postJournal(`عكس تحصيل قسط ${contract.number}`,contract.number,[{accountId:'ACC-1200',debit:num(p.amount),credit:0},{accountId:p.accountId,debit:0,credit:num(p.amount)}],A.today(),true);if(num(p.realizedProfit)>0)A.postJournal(`عكس تحقيق أرباح ${contract.number}`,contract.number,[{accountId:'ACC-4200',debit:num(p.realizedProfit),credit:0},{accountId:'ACC-2400',debit:0,credit:num(p.realizedProfit)}],A.today(),true)}
    const originalOutstanding=num(contract.outstanding),down=num(contract.downPayment),markup=num(contract.markupAmount),cashTotal=num(contract.cashTotal),tax=num(sale.tax);A.postJournal(`عكس فاتورة تقسيط ${sale.number}`,sale.number,[{accountId:'ACC-4100',debit:Number((cashTotal-tax).toFixed(2)),credit:0},{accountId:'ACC-2200',debit:Number(tax.toFixed(2)),credit:0},{accountId:'ACC-2400',debit:Number(markup.toFixed(2)),credit:0},{accountId:(sale.payments?.[0]?.accountId||d.settings.defaultAccountId||'ACC-1110'),debit:0,credit:down},{accountId:'ACC-1200',debit:0,credit:num(contract.financed)}],A.today(),true);if(num(sale.costTotal)>0)A.postJournal(`عكس تكلفة تقسيط ${sale.number}`,sale.number,[{accountId:'ACC-1300',debit:num(sale.costTotal),credit:0},{accountId:'ACC-5100',debit:0,credit:num(sale.costTotal)}],A.today(),true);(sale.lines||[]).forEach(l=>{if(l.trackStock!==false)A.adjustStock(l.productId,sale.warehouseId,num(l.baseQty))});if(customer)customer.balance=Number((num(customer.balance)-originalOutstanding).toFixed(2));const rep=d.representatives.find(r=>r.id===sale.representativeId);if(rep&&num(sale.commissionAmount)>0){const acc=A.ensureRepAccount(rep);rep.balance=Number((num(rep.balance)-num(sale.commissionAmount)).toFixed(2));A.postJournal(`عكس عمولة ${sale.number}`,sale.number,[{accountId:acc,debit:num(sale.commissionAmount),credit:0},{accountId:'ACC-5500',debit:0,credit:num(sale.commissionAmount)}],A.today(),true)}sale.status='returned';sale.returnReason='إلغاء عقد تقسيط';contract.status='cancelled';contract.cancelledAt=A.now();d.installmentSchedule.filter(x=>x.contractId===contract.id).forEach(x=>x.status='cancelled');A.audit('إلغاء عقد تقسيط','الأقساط',contract.number);A.saveDB();A.toast('تم إلغاء العقد وعكس المخزون والذمم والقيود');A.renderCurrent()
  }
  function viewInstallment(contract){updateScheduleStatuses();const rows=D().installmentSchedule.filter(x=>x.contractId===contract.id).sort((a,b)=>a.installmentNo-b.installmentNo);A.openModal({title:`عقد ${contract.number}`,size:'modal-xl',hideSubmit:true,body:`<div class="installment-kpis four"><div><small>العميل</small><b>${esc(contract.customerName)}</b></div><div><small>إجمالي العقد</small><b>${A.money(contract.total)}</b></div><div><small>المتبقي</small><b>${A.money(contract.outstanding)}</b></div><div><small>المرابحة</small><b>${A.money(contract.markupAmount)}</b></div></div>${A.table(['#','الاستحقاق','المطلوب','المسدد','المتبقي','الحالة'],rows.map(r=>`<tr><td>${r.installmentNo}</td><td>${A.dateFmt(r.dueDate)}</td><td>${A.money(r.dueAmount)}</td><td>${A.money(r.paidAmount)}</td><td>${A.money(num(r.dueAmount)-num(r.paidAmount))}</td><td>${A.badge({paid:'مسدد',partial:'جزئي',overdue:'متأخر',pending:'غير مسدد',cancelled:'ملغي'}[r.status]||r.status,r.status==='paid'?'green':r.status==='overdue'?'red':r.status==='partial'?'amber':'primary')}</td></tr>`))}<div class="actions" style="margin-top:12px">${contract.status==='active'?`<button class="btn btn-primary" data-action="pay-installment" data-id="${contract.id}">${I('cash')} تحصيل القسط التالي</button>`:''}<button class="btn btn-secondary" data-action="installment-whatsapp" data-id="${contract.id}">${I('whatsapp')} واتساب</button></div>`})}
  function renderInstallments(root){updateScheduleStatuses();const d=D(),active=d.installmentContracts.filter(x=>x.status!=='cancelled'),overdue=d.installmentSchedule.filter(x=>x.status==='overdue');root.innerHTML=`${A.pageHead('الأقساط','',action('export-installments','تصدير Excel','download','btn-secondary'))}<div class="stat-strip"><div><small>العقود النشطة</small><strong>${active.filter(x=>x.status==='active').length}</strong></div><div><small>الرصيد المتبقي</small><strong>${A.money(active.reduce((a,x)=>a+num(x.outstanding),0))}</strong></div><div><small>الأقساط المتأخرة</small><strong class="text-red">${overdue.length}</strong></div><div><small>أرباح مؤجلة</small><strong>${A.money(active.reduce((a,x)=>a+num(x.deferredProfitRemaining),0))}</strong></div></div><article class="panel">${A.table(['العقد','العميل','فاتورة','الإجمالي','دفعة أولى','المتبقي','القسط التالي','الحالة','الإجراءات'],d.installmentContracts.map(c=>{const next=firstOutstanding(c);return `<tr><td class="text-primary"><b>${esc(c.number)}</b></td><td>${esc(c.customerName)}</td><td>${esc(c.saleNumber)}</td><td>${A.money(c.total)}</td><td>${A.money(c.downPayment)}</td><td><b>${A.money(c.outstanding)}</b></td><td>${next?`${A.dateFmt(next.dueDate)} — ${A.money(num(next.dueAmount)-num(next.paidAmount))}`:'—'}</td><td>${A.badge(c.status==='paid'?'مسدد':c.status==='cancelled'?'ملغي':'نشط',c.status==='paid'?'green':c.status==='cancelled'?'red':'amber')}</td><td><div class="table-actions">${iconBtn('view-installment','eye','عرض',`data-id="${c.id}"`)}${c.status==='active'?iconBtn('pay-installment','cash','تحصيل',`data-id="${c.id}"`):''}${c.status!=='cancelled'?iconBtn('cancel-installment','trash','إلغاء وعكس',`data-id="${c.id}"`):''}</div></td></tr>`}) ,A.emptyState('calendar','لا توجد عقود أقساط',''))}</article>`}
  A.registerView('installments',renderInstallments);A.registerAction('installment-sale',installmentSale);A.registerAction('view-installment',b=>viewInstallment(D().installmentContracts.find(x=>x.id===b.dataset.id)));A.registerAction('pay-installment',b=>{const c=D().installmentContracts.find(x=>x.id===b.dataset.id);if(c)payInstallment(c)});A.registerAction('cancel-installment',b=>{const c=D().installmentContracts.find(x=>x.id===b.dataset.id);if(c)A.confirmDialog('إلغاء عقد الأقساط',`${c.number} — سيتم إنشاء قيود عكس وإعادة المخزون وإلغاء كل الجدول.`,()=>reverseInstallment(c))});A.registerAction('export-installments',()=>A.exportExcel('الأقساط',['العقد','العميل','الفاتورة','الإجمالي','الدفعة الأولى','المتبقي','الحالة'],D().installmentContracts.map(c=>[c.number,c.customerName,c.saleNumber,c.total,c.downPayment,c.outstanding,c.status])));

  // ---------- Messaging templates + WhatsApp / SMS / call ----------
  function cleanPhone(v){return String(v||'').replace(/[^0-9+]/g,'')}
  function waPhone(v){return String(v||'').replace(/\D/g,'')}
  function templateText(template,customer,extra={}){return String(template?.body||'').replace(/\{customer\}/g,customer?.name||'').replace(/\{amount\}/g,extra.amount!=null?A.money(extra.amount):A.money(customer?.balance||0)).replace(/\{due_date\}/g,extra.dueDate?A.dateFmt(extra.dueDate):'').replace(/\{installment_no\}/g,String(extra.installmentNo||''))}
  function openTemplate(item=null){A.openModal({title:item?'تعديل قالب رسالة':'قالب رسالة جديد',body:`<div class="form-grid"><label class="field"><span>اسم القالب</span><input name="name" required value="${esc(item?.name||'')}"></label><label class="field"><span>القناة</span><select name="channel"><option value="all" ${item?.channel==='all'?'selected':''}>واتساب وSMS</option><option value="whatsapp" ${item?.channel==='whatsapp'?'selected':''}>واتساب</option><option value="sms" ${item?.channel==='sms'?'selected':''}>SMS</option></select></label><label class="field full"><span>نص الرسالة</span><textarea name="body" rows="5" required>${esc(item?.body||'مرحباً {customer}، ')}</textarea></label></div><div class="first-login-note">المتغيرات: {customer} اسم العميل، {amount} المبلغ، {due_date} تاريخ الاستحقاق، {installment_no} رقم القسط.</div>`,onSubmit:fd=>{const data=item||{id:A.uid('TPL'),createdAt:A.now()};Object.assign(data,{name:fd.get('name').trim(),channel:fd.get('channel'),body:fd.get('body').trim(),updatedAt:A.now()});if(!item)D().messageTemplates.push(data);A.audit(item?'تعديل قالب':'إضافة قالب','رسائل العملاء',data.name);A.saveDB();A.renderCurrent()}})}
  function renderMessaging(root){const d=D(),customers=d.customers.filter(x=>!x.system&&x.active),templates=d.messageTemplates;S.messageTemplateId=S.messageTemplateId||templates[0]?.id||'';const current=templates.find(x=>x.id===S.messageTemplateId)||templates[0];root.innerHTML=`${A.pageHead('رسائل العملاء','',action('add-message-template','قالب جديد','plus'))}<section class="messaging-toolbar panel"><label class="field"><span>قالب الرسالة</span><select id="messageTemplateSelect">${A.options(templates,'id','name',current?.id)}</select></label><label class="field message-preview-field"><span>معاينة النص</span><textarea id="messageTemplatePreview" rows="3">${esc(current?.body||'')}</textarea></label></section><article class="panel"><div class="panel-head"><div><h3>العملاء</h3></div></div>${A.table(['العميل','الهاتف','الرصيد','واتساب','SMS','اتصال'],customers.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.phone||'—')}</td><td>${A.money(c.balance)}</td><td>${iconBtn('customer-whatsapp','whatsapp','واتساب',`data-id="${c.id}"`)}</td><td>${iconBtn('customer-sms','chat','رسالة جوال',`data-id="${c.id}"`)}</td><td>${iconBtn('customer-call','phone','اتصال',`data-id="${c.id}"`)}</td></tr>`),A.emptyState('customer','لا يوجد عملاء',''))}</article><article class="panel" style="margin-top:12px"><div class="panel-head"><div><h3>قوالب الرسائل</h3></div></div>${A.table(['الاسم','القناة','النص','الإجراءات'],templates.map(t=>`<tr><td><b>${esc(t.name)}</b></td><td>${esc(t.channel)}</td><td class="template-snippet">${esc(t.body)}</td><td><div class="table-actions">${iconBtn('edit-message-template','edit','تعديل',`data-id="${t.id}"`)}${t.system?'':iconBtn('delete-message-template','trash','حذف',`data-id="${t.id}"`)}</div></td></tr>`))}</article>`;$('#messageTemplateSelect').onchange=e=>{S.messageTemplateId=e.target.value;const t=d.messageTemplates.find(x=>x.id===e.target.value);$('#messageTemplatePreview').value=t?.body||''}}
  function messageCustomer(id,channel,extra={}){const d=D(),c=d.customers.find(x=>x.id===id);if(!c)return;const phone=cleanPhone(c.phone),template=d.messageTemplates.find(x=>x.id===S.messageTemplateId)||d.messageTemplates[0],text=extra.text||templateText(template,c,extra);if(!phone)return A.toast('لا يوجد رقم هاتف لهذا العميل.','warning');d.customerMessages.unshift({id:A.uid('CMSG'),customerId:c.id,channel,templateId:template?.id||'',text,createdAt:A.now(),userId:A.currentUser().id,status:'opened'});A.saveDB();if(channel==='whatsapp')window.open(`https://wa.me/${waPhone(phone)}?text=${encodeURIComponent(text)}`,'_blank');else if(channel==='sms')location.href=`sms:${phone}?body=${encodeURIComponent(text)}`;else location.href=`tel:${phone}`}
  A.registerView('messaging',renderMessaging);A.registerAction('add-message-template',()=>openTemplate());A.registerAction('edit-message-template',b=>openTemplate(D().messageTemplates.find(x=>x.id===b.dataset.id)));A.registerAction('delete-message-template',b=>{const t=D().messageTemplates.find(x=>x.id===b.dataset.id);if(!t||t.system)return;A.confirmDialog('حذف القالب',t.name,()=>{D().messageTemplates=D().messageTemplates.filter(x=>x.id!==t.id);A.saveDB();A.renderCurrent()})});A.registerAction('customer-whatsapp',b=>messageCustomer(b.dataset.id,'whatsapp'));A.registerAction('customer-sms',b=>messageCustomer(b.dataset.id,'sms'));A.registerAction('customer-call',b=>messageCustomer(b.dataset.id,'call'));A.registerAction('installment-whatsapp',b=>{const c=D().installmentContracts.find(x=>x.id===b.dataset.id),r=c&&firstOutstanding(c),customer=c&&D().customers.find(x=>x.id===c.customerId);if(!c||!r||!customer)return;messageCustomer(customer.id,'whatsapp',{amount:num(r.dueAmount)-num(r.paidAmount),dueDate:r.dueDate,installmentNo:r.installmentNo,text:templateText(D().messageTemplates.find(x=>x.id==='TPL-INSTALLMENT-DUE'),customer,{amount:num(r.dueAmount)-num(r.paidAmount),dueDate:r.dueDate,installmentNo:r.installmentNo})})});

  // Route sale edit/return/delete safely when the invoice belongs to an installment contract.
  const baseReturnSale=A.state.actions['return-sale'],baseDeleteSale=A.state.actions['delete-sale'],baseEditSale=A.state.actions['edit-sale'];
  A.registerAction('return-sale',b=>{const sale=D().sales.find(x=>x.id===b.dataset.id),contract=sale&&D().installmentContracts.find(c=>c.saleId===sale.id&&c.status!=='cancelled');if(contract)return A.confirmDialog('إرجاع فاتورة أقساط',`${sale.number} — سيتم إلغاء عقد الأقساط وعكس التحصيلات والمخزون والقيود.`,()=>reverseInstallment(contract));baseReturnSale?.(b)});
  A.registerAction('delete-sale',b=>{const d=D(),sale=d.sales.find(x=>x.id===b.dataset.id),contract=sale&&d.installmentContracts.find(c=>c.saleId===sale.id&&c.status!=='cancelled');if(!contract)return baseDeleteSale?.(b);A.confirmDialog('حذف فاتورة أقساط',`${sale.number} — سيتم عكس العقد بالكامل ثم حذف الفاتورة من قائمة المبيعات.`,()=>{reverseInstallment(contract);d.sales=d.sales.filter(x=>x.id!==sale.id);A.audit('حذف فاتورة أقساط','الفواتير',sale.number);A.saveDB();A.renderCurrent()})});
  A.registerAction('edit-sale',b=>{const sale=D().sales.find(x=>x.id===b.dataset.id);if(sale?.paymentMethod==='installment')return A.toast('فاتورة الأقساط لا تعدل مباشرة بعد الترحيل؛ ألغ العقد بعكس القيود ثم أنشئ عقداً جديداً.','warning',5500);baseEditSale?.(b)});

  // Add overdue installment count to notification title without requiring a server.
  document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{ensureAdvancedDB();updateScheduleStatuses();if(A.currentUser())A.renderCurrent()},0));
})();
