/* Al-Meezan Pro v7.70 — representative inventory transfers + isolated representative cashier stock */
(()=>{
'use strict';
const A=window.AlMezan;if(!A)return;
const S=A.state,D=()=>A.db,$=A.$,$$=A.$$,esc=A.esc,num=A.num,I=A.I;
const round8=n=>Number(num(n).toFixed(8));
const sync=()=>{try{window.AlMezanSync?.requestSync?.(40)}catch(_){}};
const currentRep=()=>{const u=A.currentUser?.();return u?.representativeId?D().representatives?.find(r=>r.id===u.representativeId&&r.active!==false):null};
const isBranchManager=()=>A.getSession?.()?.type==='branch-manager'||A.currentUser?.()?.isBranchManager===true||A.currentUser?.()?.role==='مدير فرع';
const branchName=id=>D().branches?.find(b=>b.id===id)?.name||'—';
const whName=id=>D().warehouses?.find(w=>w.id===id)?.name||'—';
const managerGuard=()=>{if(currentRep()){A.toast('هذه العملية متاحة للإدارة فقط.','error');return false}return true};

function normalizeRepStock(){
 const d=D();d.repStock=Array.isArray(d.repStock)?d.repStock:[];d.repStockMoves=Array.isArray(d.repStockMoves)?d.repStockMoves:[];
 const newlyAssigned=new Set();for(const rep of d.representatives||[]){if(rep.stockMode!=='assigned')newlyAssigned.add(rep.id);rep.stockMode='assigned'}
 // Historical sales from the old “all branch stock” mode must not be deducted retroactively from the new representative inventory.
 for(const sale of d.sales||[])if(newlyAssigned.has(sale.representativeId)&&sale.status!=='returned'){const applied={};for(const l of sale.lines||[])if(l.trackStock!==false&&!l.useRecipe)applied[l.productId]=round8(num(applied[l.productId])+num(l.baseQty));sale._repStockAppliedMap=applied;sale._repStockPosted=true}
}
normalizeRepStock();
A.repStockQty=function(repId,productId){return round8((D().repStock||[]).filter(r=>r.repId===repId&&r.productId===productId).reduce((n,r)=>n+num(r.qtyBase),0))};
A.adjustRepStock=function(repId,productId,delta,branchId=''){
 const d=D(),rep=d.representatives?.find(r=>r.id===repId);let row=(d.repStock||[]).find(r=>r.repId===repId&&r.productId===productId);
 if(!row){row={id:A.uid('RST'),repId,productId,branchId:branchId||rep?.branchId||'',qtyBase:0,createdAt:A.now()};d.repStock.push(row)}
 const next=round8(num(row.qtyBase)+num(delta));if(next<-1e-8&&!d.settings.allowNegative)throw Error(`رصيد المندوب غير كافٍ: ${d.products?.find(p=>p.id===productId)?.name||'الصنف'}`);row.qtyBase=Math.max(0,next);row.branchId=rep?.branchId||branchId||row.branchId||'';row.updatedAt=A.now();return row.qtyBase
};

function productLabel(p){if(!p)return'';if(p.isVariant){const par=D().products?.find(x=>x.id===p.parentId),attrs=Object.values(p.variantAttributes||{}).filter(Boolean).join(' / ');return `${par?.name||p.name}${attrs?' — '+attrs:''}`}return p.name||''}
function saleableProducts({repId='',onlyInRep=false}={}){return (D().products||[]).filter(p=>p.active!==false&&(p.isVariant||(!p.isVariant&&!p.hasVariants))&&(!onlyInRep||A.repStockQty(repId,p.id)>0)).sort((a,b)=>productLabel(a).localeCompare(productLabel(b),'ar'))}
function lineUnits(line,p){if(Array.isArray(line?.unitQuantities))return Object.fromEntries(line.unitQuantities.map(u=>[u.unitId,num(u.qty)]));return {}}
function unitInputs(p,line={}){if(!p)return'<span class="muted">اختر صنفاً</span>';const vals=lineUnits(line,p),units=(p.units||[]).slice().sort((a,b)=>num(b.factor)-num(a.factor));return `<div class="v770-unit-grid">${units.map(u=>`<label class="v770-unit-field"><span>${esc(u.name||'وحدة')}</span><input type="number" min="0" step="any" inputmode="decimal" data-unit-id="${esc(u.id)}" data-factor="${num(u.factor)||1}" value="${vals[u.id]||''}" placeholder="0"></label>`).join('')}</div>`}
function lineHtml({repId='',onlyInRep=false,line={}}={}){const list=saleableProducts({repId,onlyInRep}),p=list.find(x=>x.id===line.productId)||list[0];return `<div class="v770-stock-line"><label class="field"><span>الصنف / المتغير</span><select class="v770-product searchable-select">${list.map(x=>`<option value="${esc(x.id)}" ${x.id===p?.id?'selected':''}>${esc(productLabel(x))}</option>`).join('')}</select></label><div class="v770-units">${unitInputs(p,line)}</div><button type="button" class="icon-button v770-remove" title="حذف">${I('trash',16)}</button></div>`}
function bindLines(form,boxId,addId,opts={}){const box=$('#'+boxId,form);box.innerHTML=lineHtml(opts);A.enhanceSelects(box);A.injectIcons(box);const refresh=row=>{const p=D().products.find(x=>x.id===$('.v770-product',row)?.value);$('.v770-units',row).innerHTML=unitInputs(p,{})};box.addEventListener('change',e=>{if(e.target.matches('.v770-product'))refresh(e.target.closest('.v770-stock-line'))});box.addEventListener('click',e=>{const b=e.target.closest('.v770-remove');if(!b)return;if($$('.v770-stock-line',box).length<=1)return A.toast('يجب أن يبقى صنف واحد على الأقل.','warning');b.closest('.v770-stock-line').remove()});$('#'+addId,form)?.addEventListener('click',()=>{box.insertAdjacentHTML('beforeend',lineHtml(opts));A.enhanceSelects(box.lastElementChild);A.injectIcons(box.lastElementChild)})}
function collectLines(form,boxId){const out=[];for(const row of $$('.v770-stock-line',$('#'+boxId,form))){const pid=$('.v770-product',row)?.value,p=D().products.find(x=>x.id===pid);if(!p)continue;const unitQuantities=[];let baseQty=0;for(const inp of $$('[data-unit-id]',row)){const qty=Math.max(0,num(inp.value));if(!qty)continue;const u=(p.units||[]).find(x=>x.id===inp.dataset.unitId),factor=num(u?.factor)||num(inp.dataset.factor)||1,bq=round8(qty*factor);baseQty=round8(baseQty+bq);unitQuantities.push({unitId:u?.id||inp.dataset.unitId,unitName:u?.name||'وحدة',factor,qty,baseQty:bq})}if(baseQty>0)out.push({productId:p.id,productName:productLabel(p),baseQty,unitQuantities,quantityText:unitQuantities.map(u=>`${u.qty} ${u.unitName}`).join(' + ')})}return out}
function warehousesForAction(){const d=D(),bid=S.activeBranchId||A.currentUser?.()?.branchId;return (d.warehouses||[]).filter(w=>w.active!==false&&w.deleted!==true&&(!isBranchManager()||w.branchId===bid))}
const loadSvg=`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7.5 12 3l9 4.5v9L12 21l-9-4.5z"/><path d="m3 7.5 9 4.5 9-4.5M12 12v9"/><path d="M18.5 12.5h-5m2-2 3 2-3 2"/></svg>`;
const returnSvg=`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M4 8.5 12 4l8 4.5v8L12 21l-8-4.5z"/><path d="m4 8.5 8 4.5 8-4.5M12 13v8"/><path d="M10.5 9H6m2-2-2 2 2 2"/></svg>`;
const boxSvg=`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m4 7 8-4 8 4-8 4zM4 7v10l8 4 8-4V7M12 11v10"/></svg>`;
function svgButton(action,svg,title,id){return `<button type="button" class="icon-button rep-stock-svg" data-action="${action}" data-id="${esc(id)}" title="${esc(title)}">${svg}</button>`}

function openLoad(rep){if(!managerGuard())return;const d=D(),whs=warehousesForAction();if(!whs.length)return A.toast('لا يوجد مستودع متاح.','warning');A.openModal({title:`تحميل بضاعة للمندوب — ${rep.name}`,size:'modal-xl',body:`<div class="form-grid cols-3"><label class="field"><span>من المستودع</span><select name="warehouseId">${A.options(whs)}</select></label><label class="field"><span>التاريخ</span><input type="date" name="date" value="${A.today()}"></label><label class="field"><span>ملاحظات</span><input name="notes"></label></div><section class="form-section"><div class="form-section-title"><h4>البضاعة المحملة</h4><button type="button" class="btn btn-secondary btn-sm" id="v770AddLoad">${I('plus',15)} إضافة صنف</button></div><div id="v770LoadLines"></div></section><div class="first-login-note">يتم خصم البضاعة فعلياً من المستودع وإضافتها لمخزون المندوب. بيع المندوب بعد ذلك يخصم من مخزونه فقط.</div>`,submitText:'تنفيذ تحميل البضاعة',afterOpen:f=>bindLines(f,'v770LoadLines','v770AddLoad',{}),onSubmit:(fd,form)=>A.atomicMutation(()=>{const wh=String(fd.get('warehouseId')||''),lines=collectLines(form,'v770LoadLines');if(!lines.length)throw Error('أدخل كمية لصنف واحد على الأقل.');for(const l of lines){const available=A.stockQty(l.productId,wh);if(available+1e-8<l.baseQty&&!d.settings.allowNegative)throw Error(`الرصيد غير كافٍ في المستودع: ${l.productName} — المتاح ${A.unitBreakdown(d.products.find(p=>p.id===l.productId),available)}`)}for(const l of lines){A.adjustStock(l.productId,wh,-l.baseQty);A.adjustRepStock(rep.id,l.productId,l.baseQty,rep.branchId)}const x={id:A.uid('RSM'),number:A.nextNo('repStockMove','RSM-'),type:'load',date:String(fd.get('date')||A.today()),repId:rep.id,repName:rep.name,warehouseId:wh,warehouseName:whName(wh),lines,notes:String(fd.get('notes')||''),createdAt:A.now(),userId:A.currentUser()?.id||''};d.repStockMoves.unshift(x);A.audit('تحميل بضاعة مندوب','المناديب',`${rep.name} ← ${whName(wh)} — ${lines.length} صنف`);A.saveDB();sync();A.toast('تم تحميل البضاعة للمندوب وخصمها من المستودع');A.renderCurrent()} )})}
function openReturn(rep){if(!managerGuard())return;const d=D(),whs=warehousesForAction();if(!saleableProducts({repId:rep.id,onlyInRep:true}).length)return A.toast('لا يوجد رصيد عند المندوب لإرجاعه.','warning');A.openModal({title:`إرجاع بضاعة من المندوب — ${rep.name}`,size:'modal-xl',body:`<div class="form-grid cols-3"><label class="field"><span>إلى المستودع</span><select name="warehouseId">${A.options(whs)}</select></label><label class="field"><span>التاريخ</span><input type="date" name="date" value="${A.today()}"></label><label class="field"><span>ملاحظات</span><input name="notes"></label></div><section class="form-section"><div class="form-section-title"><h4>البضاعة المرتجعة</h4><button type="button" class="btn btn-secondary btn-sm" id="v770AddReturn">${I('plus',15)} إضافة صنف</button></div><div id="v770ReturnLines"></div></section>`,submitText:'إرجاع إلى المستودع',afterOpen:f=>bindLines(f,'v770ReturnLines','v770AddReturn',{repId:rep.id,onlyInRep:true}),onSubmit:(fd,form)=>A.atomicMutation(()=>{const wh=String(fd.get('warehouseId')||''),lines=collectLines(form,'v770ReturnLines');if(!lines.length)throw Error('أدخل كمية لصنف واحد على الأقل.');for(const l of lines)if(A.repStockQty(rep.id,l.productId)+1e-8<l.baseQty)throw Error(`رصيد المندوب غير كافٍ: ${l.productName}`);for(const l of lines){A.adjustRepStock(rep.id,l.productId,-l.baseQty,rep.branchId);A.adjustStock(l.productId,wh,l.baseQty)}d.repStockMoves.unshift({id:A.uid('RSM'),number:A.nextNo('repStockMove','RSM-'),type:'return',date:String(fd.get('date')||A.today()),repId:rep.id,repName:rep.name,warehouseId:wh,warehouseName:whName(wh),lines,notes:String(fd.get('notes')||''),createdAt:A.now(),userId:A.currentUser()?.id||''});A.audit('إرجاع بضاعة مندوب','المناديب',`${rep.name} → ${whName(wh)} — ${lines.length} صنف`);A.saveDB();sync();A.toast('تم إرجاع البضاعة إلى المستودع');A.renderCurrent()})})}
function openInventory(rep){const d=D(),list=saleableProducts({repId:rep.id,onlyInRep:true}),moves=(d.repStockMoves||[]).filter(x=>x.repId===rep.id).slice(0,50);A.openModal({title:`مخزون المندوب — ${rep.name}`,size:'modal-xl',hideSubmit:true,body:`<div class="stat-strip"><div><small>الأصناف المحملة</small><strong>${list.length}</strong></div><div><small>إجمالي الوحدات الأساسية</small><strong>${list.reduce((n,p)=>n+A.repStockQty(rep.id,p.id),0)}</strong></div><div><small>آخر حركة</small><strong>${esc(moves[0]?.number||'—')}</strong></div><div><small>الحالة</small><strong>${rep.active!==false?'نشط':'موقوف'}</strong></div></div>${A.table(['الصنف','الرصيد حسب الوحدات'],A.pagedRecords(list,`rep-inventory-${rep.id}`).map(p=>`<tr><td><b>${esc(productLabel(p))}</b></td><td>${A.unitBreakdownHtml(p,A.repStockQty(rep.id,p.id))}</td></tr>`),A.emptyState('products','لا توجد بضاعة محملة',''))}<section class="form-section"><h4>آخر حركات التحميل والإرجاع</h4>${A.table(['الرقم','التاريخ','النوع','المستودع','الأصناف'],moves.map(x=>`<tr><td>${esc(x.number)}</td><td>${A.dateFmt(x.date)}</td><td>${A.badge(x.type==='load'?'تحميل':'إرجاع',x.type==='load'?'blue':'amber')}</td><td>${esc(x.warehouseName||whName(x.warehouseId))}</td><td>${x.lines?.length||0}</td></tr>`),'<p class="muted">لا توجد حركات بعد.</p>')}</section>`})}

function openRepEditor(rep=null){if(!managerGuard())return;const d=D(),primary=rep?.branchId||S.activeBranchId||d.branches?.[0]?.id,selected=rep?.permissions||['dashboard','cashier','sales','parties','debts'];A.openModal({title:rep?'تعديل مندوب':'إضافة مندوب',size:'modal-xl',body:`<div class="form-grid cols-3"><label class="field"><span>الاسم</span><input name="name" value="${esc(rep?.name||'')}" required></label><label class="field"><span>الهاتف</span><input name="phone" value="${esc(rep?.phone||'')}"></label><label class="field"><span>الفرع الأساسي</span><select name="branchId">${A.options(d.branches.filter(b=>b.active!==false),'id','name',primary)}</select></label><label class="field"><span>نسبة العمولة %</span><input name="commission" type="number" min="0" max="100" step="0.01" value="${num(rep?.commission)}"></label><label class="field"><span>الرصيد المالي</span><input name="balance" type="number" step="0.01" value="${num(rep?.balance)}"></label><label class="field"><span>الحالة</span><select name="active"><option value="1" ${rep?.active!==false?'selected':''}>نشط</option><option value="0" ${rep?.active===false?'selected':''}>موقوف</option></select></label></div><div class="first-login-note">المندوب يعمل دائماً بمخزون مستقل. لا يرى ولا يبيع إلا البضاعة التي تم تحميلها له.</div><section class="form-section"><h4>الصلاحيات</h4><div class="permissions-grid">${A.PERMISSIONS.filter(([id])=>!['employees','settings','branches_manage','branch_select'].includes(id)).map(([id,label])=>`<label class="permission-item"><input type="checkbox" name="permission" value="${id}" ${selected.includes(id)?'checked':''}><span>${esc(label)}</span></label>`).join('')}</div></section>`,onSubmit:fd=>{const name=String(fd.get('name')||'').trim(),permissions=fd.getAll('permission');if(!name)throw Error('اكتب اسم المندوب.');const target=rep||{id:A.uid('REP'),createdAt:A.now(),authVersion:A.uid('AUTH')},branchId=String(fd.get('branchId')||primary),commission=num(fd.get('commission'));Object.assign(target,{name,phone:String(fd.get('phone')||'').trim(),branchId,allowedBranchIds:[branchId],commission,commissionRates:{...(target.commissionRates||{}),[branchId]:commission},stockMode:'assigned',balance:num(fd.get('balance')),permissions,active:fd.get('active')==='1',updatedAt:A.now()});if(!rep)d.representatives.push(target);let u=d.employees.find(e=>e.representativeId===target.id);if(!u){u={id:A.uid('EMP'),representativeId:target.id,createdAt:A.now(),system:false,authVersion:target.authVersion};d.employees.push(u)}Object.assign(u,{name:target.name,role:'مندوب',branchId,permissions:[...permissions],active:target.active,authVersion:target.authVersion,representativeId:target.id});target.employeeId=u.id;A.ensureRepAccount?.(target);A.audit(rep?'تعديل مندوب':'إضافة مندوب','المناديب',target.name);A.saveDB();sync();A.toast('تم حفظ المندوب بنظام المخزون المستقل');A.renderCurrent()}})}

// Rebuild once without losing PagedRecordArray metadata (the expression above keeps it; this helper makes intent explicit).
function repsView770(root){const d=D(),bid=S.activeBranchId,list=(d.representatives||[]).filter(r=>!isBranchManager()||r.branchId===bid).slice().sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||''))),rows=A.pagedRecords(list,'representatives').map(r=>{const count=saleableProducts({repId:r.id,onlyInRep:true}).length;return `<tr><td><b>${esc(r.name)}</b></td><td>${esc(branchName(r.branchId))}</td><td>${num(r.commission)}%</td><td><b>${count}</b> صنف</td><td><b>${A.money(r.balance)}</b></td><td>${A.badge(r.active!==false?'نشط':'موقوف',r.active!==false?'green':'red')}</td><td><button class="btn btn-secondary btn-sm" data-action="download-rep-v752" data-id="${r.id}" ${r.active===false?'disabled':''}>${I('download',15)} .mzauth</button></td><td><div class="table-actions">${svgButton('rep-load-v770',loadSvg,'تحميل بضاعة للمندوب',r.id)}${svgButton('rep-return-v770',returnSvg,'إرجاع بضاعة للمستودع',r.id)}${svgButton('rep-inventory-v770',boxSvg,'عرض مخزون المندوب',r.id)}<button class="icon-button" data-action="rep-ledger-v752" data-id="${r.id}" title="سجل الحساب">${I('journal',16)}</button><button class="icon-button" data-action="edit-rep-v770" data-id="${r.id}" title="تعديل">${I('edit',16)}</button></div></td></tr>`});root.innerHTML=`${A.pageHead('المناديب','كل مندوب له مخزون مستقل يتم تحميله من المستودع وإرجاعه إليه.',`<button class="btn btn-primary" data-action="add-rep-v770">${I('plus',16)} إضافة مندوب</button>`)}<article class="panel">${A.table(['المندوب','الفرع','العمولة','مخزونه','الرصيد المالي','الحالة','ملف الدخول','الإجراءات'],rows,A.emptyState('rep','لا يوجد مناديب',''))}</article>`}
A.registerView('representatives',repsView770);
A.registerAction('add-rep-v770',()=>openRepEditor());A.registerAction('edit-rep-v770',b=>openRepEditor(D().representatives.find(r=>r.id===b.dataset.id)));A.registerAction('rep-load-v770',b=>{const r=D().representatives.find(x=>x.id===b.dataset.id);if(r)openLoad(r)});A.registerAction('rep-return-v770',b=>{const r=D().representatives.find(x=>x.id===b.dataset.id);if(r)openReturn(r)});A.registerAction('rep-inventory-v770',b=>{const r=D().representatives.find(x=>x.id===b.dataset.id);if(r)openInventory(r)});

// Representative cashier: force own stock, hide warehouse inventory and products not loaded to the rep.
const baseCashier=S.views.cashier;A.registerView('cashier',root=>{const rep=currentRep();if(rep){rep.stockMode='assigned';S.cashierRepId=rep.id;S.activeBranchId=rep.branchId}baseCashier?.(root);if(!rep)return;const whSel=$('#cashierWarehouse',root);if(whSel){whSel.disabled=true;const field=whSel.closest('.field,.cashier-field');if(field)field.style.display='none'}const grid=root.querySelector('.product-grid');if(grid)for(const card of $$('.product-card',grid)){const p=D().products.find(x=>x.id===card.dataset.id),qty=A.repStockQty(rep.id,card.dataset.id);card.hidden=qty<=0;if(!card.hidden){const st=card.querySelector('.product-stock');if(st)st.innerHTML=`مخزونك: ${A.unitBreakdownHtml(p,qty)}`}}});

// Returned/edited representative sales restore representative inventory, never the source warehouse.
if(A.reverseSaleEffect&&!A.reverseSaleEffect._repInventory770){const prev=A.reverseSaleEffect;const wrapped=function(sale,opts={}){if(!sale?.repInventorySale)return prev(sale,opts);const oldAdjust=A.adjustStock,oldRestore=A.cashierRestoreStock;A.adjustStock=()=>0;if(oldRestore)A.cashierRestoreStock=()=>true;let out;try{out=prev(sale,opts)}finally{A.adjustStock=oldAdjust;if(oldRestore)A.cashierRestoreStock=oldRestore}const repId=sale.repStockOwnerId||sale.representativeId;for(const l of sale.lines||[])if(l.trackStock!==false&&!l.useRecipe)A.adjustRepStock(repId,l.productId,num(l.baseQty),sale.branchId);sale._repStockAppliedMap={};return out};wrapped._repInventory770=true;A.reverseSaleEffect=wrapped}


// If a representative is allowed to open inventory, show only his loaded stock, never company warehouse balances.
const baseStockView=S.views.stock;A.registerView('stock',root=>{const rep=currentRep();if(!rep)return baseStockView?.(root);const list=saleableProducts({repId:rep.id,onlyInRep:true});root.innerHTML=`${A.pageHead('مخزوني','البضاعة المحملة لك فقط. أرصدة مستودعات الشركة غير معروضة.', '')}<article class="panel">${A.table(['الصنف','الرصيد حسب الوحدات'],A.pagedRecords(list,'rep-own-stock').map(p=>`<tr><td><b>${esc(productLabel(p))}</b></td><td>${A.unitBreakdownHtml(p,A.repStockQty(rep.id,p.id))}</td></tr>`),A.emptyState('products','لا توجد بضاعة محملة','اطلب من الإدارة تحميل بضاعة إلى مخزونك.'))}</article>`});

const style=document.createElement('style');style.textContent=`
.rep-stock-svg svg{width:18px;height:18px}.v770-stock-line{display:grid;grid-template-columns:minmax(210px,1.1fr) minmax(320px,2fr) 42px;gap:10px;align-items:end;padding:10px 0;border-bottom:1px solid var(--line)}.v770-unit-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(110px,1fr));gap:7px}.v770-unit-field{display:flex;flex-direction:column;gap:4px;font-size:10px;color:var(--muted)}.v770-unit-field input{width:100%;min-height:38px}@media(max-width:760px){.v770-stock-line{grid-template-columns:1fr}.v770-stock-line>.icon-button{justify-self:start}.v770-unit-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
`;document.head.appendChild(style);
if(num(D().settings.printCenterCalibrationVersion)<770){D().settings.printOffset58=0;D().settings.printOffset80=0;D().settings.printCenterCalibrationVersion=770}
D().settings.enterpriseSchemaVersion=770;D().sequences.repStockMove=num(D().sequences.repStockMove);A.saveDB(true);
})();
