(function(){
  'use strict';
  const A=window.AlMezan,S=A.state,$=A.$,esc=A.esc,num=A.num,I=A.I,D=()=>A.db;
  const action=(id,label,icon='plus',cls='btn-primary',attrs='')=>`<button class="btn ${cls}" data-action="${id}" ${attrs}>${I(icon)}${esc(label)}</button>`;
  const iconBtn=(id,icon,title,attrs='')=>`<button class="icon-button" data-action="${id}" title="${esc(title)}" ${attrs}>${I(icon)}</button>`;

  function ensureEnterpriseDB(){
    const d=D();
    const arrays=['taxes','workers','attendance','employeeLoans','payrollAdjustments','payrollSheets','messages'];
    arrays.forEach(k=>{if(!Array.isArray(d[k]))d[k]=[]});
    d.settings.defaultAccountId=d.settings.defaultAccountId||'ACC-1110';
    if(!d.taxes.some(x=>x.id==='TAX-ZERO'))d.taxes.unshift({id:'TAX-ZERO',name:'بدون ضريبة',rate:0,active:true,system:true});
    if(num(d.settings.taxRate)>0&&!d.taxes.some(x=>x.systemDefault))d.taxes.push({id:'TAX-DEFAULT',name:'الضريبة الافتراضية',rate:num(d.settings.taxRate),active:true,systemDefault:true});
    const required=[
      {id:'ACC-1500',code:'1500',name:'سلف وقروض الموظفين',type:'asset',parentId:'ACC-1000',level:1},
      {id:'ACC-2300',code:'2300',name:'ذمم ومستحقات الموظفين',type:'liability',parentId:'ACC-2000',level:1},
      {id:'ACC-2500',code:'2500',name:'عمولات المناديب المستحقة',type:'liability',parentId:'ACC-2000',level:1},
      {id:'ACC-4300',code:'4300',name:'استردادات وخصومات الموظفين',type:'revenue',parentId:'ACC-4000',level:1},
      {id:'ACC-5300',code:'5300',name:'مصروف الرواتب والأجور',type:'expense',parentId:'ACC-5000',level:1},
      {id:'ACC-5500',code:'5500',name:'مصروف عمولات المناديب',type:'expense',parentId:'ACC-5000',level:1}
    ];
    required.forEach(a=>{if(!d.accounts.some(x=>x.id===a.id))d.accounts.push(a)});
    A.saveDB();
  }

  const extraPermissions=[
    ['branch_select','تغيير الفرع الحالي'],['warehouse_select','اختيار المستودع في الكاشير'],['branches_view','عرض الفروع'],['warehouses_view','عرض المستودعات'],['branches_manage','إدارة الفروع'],['warehouses_manage','إدارة المستودعات'],
    ['sales_return','مرتجعات المبيعات'],['sales_credit','البيع الآجل'],['taxes','الضرائب'],['payroll','العمال والرواتب'],['attendance','الدوام والإجازات'],['loans','السلف والقروض'],['chat','الدردشة الداخلية']
  ];
  extraPermissions.forEach(p=>{if(!A.PERMISSIONS.some(x=>x[0]===p[0]))A.PERMISSIONS.push(p)});
  // Refine permissions used by navigation.
  for(const g of A.NAV){for(const item of g.items){if(item[0]==='branches')item[3]='branches_view';if(item[0]==='warehouses')item[3]='warehouses_view'}}
  if(!A.NAV.some(g=>g.title==='العمال والأجور'))A.NAV.splice(A.NAV.length-1,0,{title:'العمال والأجور',items:[['workers','employees','بطاقات العمال','payroll'],['attendance','clock','الدوام والإجازات','attendance'],['loans','voucher','السلف والقروض','loans'],['payroll','reports','مسيرات الرواتب','payroll'],['chat','chat','الدردشة الداخلية','chat']]});
  const accounting=A.NAV.find(g=>g.title==='المحاسبة');if(accounting&&!accounting.items.some(x=>x[0]==='taxes'))accounting.items.splice(4,0,['taxes','accounts','الضرائب','taxes']);
  Object.assign(A.PAGE_META,{taxes:['الضرائب',''],workers:['العمال',''],attendance:['الدوام والإجازات',''],loans:['السلف والقروض',''],payroll:['مسيرات الرواتب',''],chat:['الدردشة الداخلية','']});

  ensureEnterpriseDB();

  // v7.35 — fast, wide, autofocus barcode camera. Uses a standalone overlay so parent modals stay open.
  A.scanBarcodeCamera=function({title='مسح الباركود',onDetected,keepOpen=false}={}){
    try{S.barcodeScannerClose?.()}catch(_){}
    let closed=false,stream=null,timer=0,busy=false,lastCode='',lastAt=0;
    const preferred=['aztec','code_128','code_39','code_93','codabar','data_matrix','ean_13','ean_8','itf','pdf417','qr_code','upc_a','upc_e'];
    const overlay=document.createElement('div');overlay.className='barcode-camera-overlay';
    overlay.innerHTML=`<section class="barcode-camera-shell" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="barcode-camera-head"><div><span class="barcode-camera-kicker">${I('barcode',14)} ماسح ذكي</span><h3>${esc(title)}</h3></div><button type="button" class="icon-button barcode-camera-close" aria-label="إغلاق">${I('close',18)}</button></div><div class="barcode-camera-stage"><video class="barcode-camera-video" playsinline webkit-playsinline autoplay muted></video><div class="barcode-scan-window"><i class="barcode-scan-line"></i><span class="scan-corner c1"></span><span class="scan-corner c2"></span><span class="scan-corner c3"></span><span class="scan-corner c4"></span></div><div class="barcode-camera-status"><span class="barcode-camera-dot"></span><b>وجّه الباركود داخل الإطار</b><small>تركيز تلقائي وقراءة فورية</small></div></div><div class="barcode-camera-fallback" hidden><div>${I('camera',22)}<b>تعذر تشغيل المسح المباشر</b><small>يمكن التقاط صورة واضحة للباركود وقراءتها بدون إدخال يدوي.</small></div><button type="button" class="btn btn-primary barcode-photo-btn">${I('camera',15)} التقاط صورة</button><input class="barcode-photo-input" type="file" accept="image/*" capture="environment" hidden></div><div class="barcode-camera-foot"><span>${I('focus',14)} تركيز مستمر</span><span>${I('scan',14)} قراءة سريعة</span>${keepOpen?`<span class="keep-scanner-pill">${I('refresh',14)} يبقى مفتوحاً</span>`:''}</div></section>`;
    document.body.appendChild(overlay);A.injectIcons?.(overlay);
    const video=overlay.querySelector('.barcode-camera-video'),stage=overlay.querySelector('.barcode-camera-stage'),fallback=overlay.querySelector('.barcode-camera-fallback'),status=overlay.querySelector('.barcode-camera-status');
    const stop=()=>{if(closed)return;closed=true;clearTimeout(timer);try{stream?.getTracks().forEach(t=>t.stop())}catch(_){}if(S.activeStream===stream)S.activeStream=null;try{video.pause()}catch(_){}try{video.srcObject=null}catch(_){}overlay.remove();if(S.barcodeScannerClose===stop)S.barcodeScannerClose=null};
    S.barcodeScannerClose=stop;overlay.querySelector('.barcode-camera-close').onclick=stop;overlay.addEventListener('click',e=>{if(e.target===overlay)stop()});
    const flash=(ok=true,text='تمت القراءة')=>{if(!status)return;status.classList.remove('scan-ok','scan-warn');status.classList.add(ok?'scan-ok':'scan-warn');const b=status.querySelector('b');if(b)b.textContent=text;setTimeout(()=>{if(!closed&&b){status.classList.remove('scan-ok','scan-warn');b.textContent='وجّه الباركود داخل الإطار'}},650)};
    const emit=async raw=>{const code=String(raw||'').trim();if(!code||closed)return false;const now=Date.now();if(code===lastCode&&now-lastAt<850)return false;lastCode=code;lastAt=now;let accepted=true;try{const result=await onDetected?.(code);if(result===false)accepted=false}catch(e){accepted=false;A.toast?.(String(e?.message||e),'error')}flash(accepted,accepted?'تمت القراءة':'الكود غير مقبول');if(!keepOpen&&accepted)stop();return accepted};
    const detectorFor=async()=>{if(!('BarcodeDetector' in window))return null;try{const supported=typeof BarcodeDetector.getSupportedFormats==='function'?await BarcodeDetector.getSupportedFormats():preferred;const formats=preferred.filter(x=>supported.includes(x));return new BarcodeDetector(formats.length?{formats}:undefined)}catch(_){try{return new BarcodeDetector()}catch(__){return null}}};
    const tuneFocus=async track=>{try{const caps=track.getCapabilities?.()||{},adv={};if(Array.isArray(caps.focusMode)&&caps.focusMode.includes('continuous'))adv.focusMode='continuous';if(Array.isArray(caps.exposureMode)&&caps.exposureMode.includes('continuous'))adv.exposureMode='continuous';if(Array.isArray(caps.whiteBalanceMode)&&caps.whiteBalanceMode.includes('continuous'))adv.whiteBalanceMode='continuous';if(Object.keys(adv).length)await track.applyConstraints({advanced:[adv]})}catch(_){} };
    const showFallback=(message='تعذر تشغيل الكاميرا مباشرة.')=>{stage.hidden=true;fallback.hidden=false;const small=fallback.querySelector('small');if(small)small.textContent=message+' التقط صورة واضحة للباركود.'};
    const startPhotoFallback=async detector=>{showFallback(detector?'المتصفح لم يتمكن من تشغيل بث الكاميرا.':'هذا المتصفح لا يدعم قراءة الباركود المباشرة.');const input=fallback.querySelector('.barcode-photo-input');fallback.querySelector('.barcode-photo-btn').onclick=()=>input.click();input.onchange=async()=>{const file=input.files?.[0];if(!file||!detector){A.toast?.('هذا المتصفح لا يدعم قراءة الباركود من الصورة.','warning',4500);return}try{const bmp=await createImageBitmap(file),found=await detector.detect(bmp);bmp.close?.();if(found?.[0]?.rawValue)await emit(found[0].rawValue);else A.toast?.('لم يظهر باركود واضح في الصورة. قرّب الكاميرا وحاول مرة أخرى.','warning',4200)}catch(_){A.toast?.('تعذر قراءة الصورة. حاول بصورة أوضح.','warning',4200)}}};
    (async()=>{
      const detector=await detectorFor();if(!detector||!navigator.mediaDevices?.getUserMedia){await startPhotoFallback(detector);return}
      try{
        const attempts=[{video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:30,max:60}},audio:false},{video:{facingMode:'environment',width:{ideal:1280},height:{ideal:720}},audio:false},{video:true,audio:false}];let err=null;
        for(const constraints of attempts){try{stream=await navigator.mediaDevices.getUserMedia(constraints);break}catch(e){err=e;if(['NotAllowedError','SecurityError','NotReadableError'].includes(String(e?.name||'')))break}}
        if(!stream)throw err||new Error('CAMERA_UNAVAILABLE');S.activeStream=stream;const track=stream.getVideoTracks?.()[0];if(track)await tuneFocus(track);video.srcObject=stream;await video.play();
        const loop=async()=>{if(closed)return;if(!busy&&video.readyState>=2){busy=true;try{const found=await detector.detect(video);if(found?.length){const vw=video.videoWidth||1,vh=video.videoHeight||1,inside=found.filter(x=>{const b=x.boundingBox;if(!b)return true;const cx=(b.x+b.width/2)/vw,cy=(b.y+b.height/2)/vh;return cx>=.04&&cx<=.96&&cy>=.08&&cy<=.92}),best=(inside.length?inside:found).slice().sort((a,b)=>((b.boundingBox?.width||0)*(b.boundingBox?.height||0))-((a.boundingBox?.width||0)*(a.boundingBox?.height||0)))[0];if(best?.rawValue)await emit(best.rawValue)}}catch(_){}finally{busy=false}}timer=setTimeout(loop,70)};loop();
      }catch(error){try{stream?.getTracks().forEach(t=>t.stop())}catch(_){}S.activeStream=null;await startPhotoFallback(detector)}
    })();
    return stop;
  };

  A.findProductByBarcode=function(code){code=String(code||'').trim();for(const p of D().products){const u=p.units?.find(x=>String(x.barcode||'').trim()===code);if(u)return{product:p,unit:u};if(String(p.sku||'').trim()===code)return{product:p,unit:p.units?.[0]}}return null};

  A.ensureRepAccount=function(rep){if(!rep)return null;const d=D();if(rep.accountId&&d.accounts.some(a=>a.id===rep.accountId))return rep.accountId;const id='ACC-REP-'+rep.id.replace(/[^A-Z0-9-]/gi,'').slice(-18),code='25'+String(d.representatives.indexOf(rep)+1).padStart(3,'0');if(!d.accounts.some(a=>a.id===id))d.accounts.push({id,code,name:`عمولة المندوب - ${rep.name}`,type:'liability',parentId:'ACC-2500',level:2});rep.accountId=id;rep.balance=num(rep.balance);return id};

  function renderTaxes(root){
    const d=D(),accounts=A.paymentAccounts();root.innerHTML=`${A.pageHead('الضرائب','',action('add-tax','إضافة ضريبة'))}<div class="grid-2"><article class="panel"><div class="panel-head"><div><h3>الضرائب المعرفة</h3></div></div>${A.table(['الاسم','النسبة','الحالة','الإجراءات'],d.taxes.map(t=>`<tr><td><b>${esc(t.name)}</b></td><td>${num(t.rate)}%</td><td>${A.badge(t.active!==false?'نشطة':'موقوفة',t.active!==false?'green':'red')}</td><td><div class="table-actions">${t.system?'':iconBtn('edit-tax','edit','تعديل',`data-id="${t.id}"`)}${t.system?'':iconBtn('delete-tax','trash','حذف',`data-id="${t.id}"`)}</div></td></tr>`))}</article><article class="panel"><div class="panel-head"><div><h3>الحساب الافتراضي</h3></div></div><label class="field"><span>حساب التحصيل/الدفع الافتراضي</span><select id="defaultPaymentAccount">${accounts.map(a=>`<option value="${a.id}" ${a.id===d.settings.defaultAccountId?'selected':''}>${esc(a.code)} — ${esc(a.name)}</option>`).join('')}</select></label><div class="first-login-note">يظهر هذا الحساب أولاً في قوائم الحسابات والكاشير والمشتريات.</div></article></div>`;$('#defaultPaymentAccount').onchange=e=>{d.settings.defaultAccountId=e.target.value;A.saveDB();A.toast('تم تعيين الحساب الافتراضي')}
  }
  function openTax(item=null){A.openModal({title:item?'تعديل ضريبة':'إضافة ضريبة',body:`<div class="form-grid"><label class="field"><span>اسم الضريبة</span><input name="name" required value="${esc(item?.name||'')}"></label><label class="field"><span>النسبة %</span><input name="rate" type="number" min="0" max="100" step="0.01" required value="${num(item?.rate)}"></label><label class="field"><span>الحالة</span><select name="active"><option value="1" ${item?.active!==false?'selected':''}>نشطة</option><option value="0" ${item?.active===false?'selected':''}>موقوفة</option></select></label></div>`,onSubmit:fd=>{const d=D(),data={id:item?.id||A.uid('TAX'),name:fd.get('name').trim(),rate:num(fd.get('rate')),active:fd.get('active')==='1'};if(!data.name)throw Error('اكتب اسم الضريبة.');if(item)Object.assign(item,data);else d.taxes.push(data);A.audit(item?'تعديل ضريبة':'إضافة ضريبة','الضرائب',`${data.name} ${data.rate}%`);A.saveDB();A.toast('تم حفظ الضريبة');A.renderCurrent()}})}

  function ensureWorkerAccount(worker){const d=D();if(worker.accountId&&d.accounts.some(a=>a.id===worker.accountId))return worker.accountId;const id='ACC-WRK-'+worker.id.replace(/[^A-Z0-9-]/gi,'').slice(-18),code='23'+String(d.workers.indexOf(worker)+1).padStart(3,'0');if(!d.accounts.some(a=>a.id===id))d.accounts.push({id,code,name:`ذمة العامل - ${worker.name}`,type:'liability',parentId:'ACC-2300',level:2});worker.accountId=id;return id}
  function workerBy(id){return D().workers.find(x=>x.id===id)}
  function renderWorkers(root){const d=D();root.innerHTML=`${A.pageHead('بطاقات العمال','',action('add-worker','عامل جديد'))}<div class="stat-strip"><div><small>العمال</small><strong>${d.workers.length}</strong></div><div><small>إجمالي الرواتب الأساسية</small><strong>${A.money(d.workers.filter(x=>x.active!==false).reduce((a,x)=>a+num(x.basicSalary),0))}</strong></div><div><small>سلف قائمة</small><strong>${A.money(d.employeeLoans.filter(x=>num(x.remaining)>0).reduce((a,x)=>a+num(x.remaining),0))}</strong></div><div><small>سجلات دوام الشهر</small><strong>${d.attendance.filter(x=>String(x.date).slice(0,7)===A.today().slice(0,7)).length}</strong></div></div><article class="panel">${A.table(['الرقم','العامل','الوظيفة','الراتب','البدلات','الوردية','الحساب','الحالة','الإجراءات'],d.workers.map(w=>`<tr><td class="text-primary">${esc(w.employeeNo)}</td><td><b>${esc(w.name)}</b><small class="muted"> ${esc(w.phone||'')}</small></td><td>${esc(w.jobTitle||'—')}</td><td>${A.money(w.basicSalary)}</td><td>${A.money(w.allowances)}</td><td>${esc(w.shiftStart||'08:00')} - ${esc(w.shiftEnd||'16:00')}</td><td>${esc(d.accounts.find(a=>a.id===w.accountId)?.code||'—')}</td><td>${A.badge(w.active!==false?'نشط':'موقوف',w.active!==false?'green':'red')}</td><td><div class="table-actions">${iconBtn('worker-adjustment','expense','خصم/إضافة',`data-id="${w.id}"`)}${iconBtn('edit-worker','edit','تعديل',`data-id="${w.id}"`)}${iconBtn('delete-worker','trash','حذف',`data-id="${w.id}"`)}</div></td></tr>`),A.emptyState('employees','لا يوجد عمال',''))}</article>`}
  function openWorker(item=null){const d=D();A.openModal({title:item?'تعديل بطاقة عامل':'عامل جديد',size:'modal-lg',body:`<div class="form-grid cols-3"><label class="field"><span>الرقم الوظيفي</span><input name="employeeNo" required value="${esc(item?.employeeNo||`EMP-${String(d.workers.length+1).padStart(4,'0')}`)}"></label><label class="field"><span>اسم العامل</span><input name="name" required value="${esc(item?.name||'')}"></label><label class="field"><span>الهاتف / واتساب</span><input name="phone" inputmode="tel" value="${esc(item?.phone||'')}"></label><label class="field"><span>المسمى الوظيفي</span><input name="jobTitle" value="${esc(item?.jobTitle||'')}"></label><label class="field"><span>الراتب الأساسي</span><input name="basicSalary" type="number" min="0" step="0.01" value="${num(item?.basicSalary)}"></label><label class="field"><span>البدلات الشهرية</span><input name="allowances" type="number" min="0" step="0.01" value="${num(item?.allowances)}"></label><label class="field"><span>بداية الوردية</span><input name="shiftStart" type="time" value="${esc(item?.shiftStart||'08:00')}"></label><label class="field"><span>نهاية الوردية</span><input name="shiftEnd" type="time" value="${esc(item?.shiftEnd||'16:00')}"></label><label class="field"><span>معامل الإضافي</span><input name="overtimeMultiplier" type="number" min="1" step="0.1" value="${num(item?.overtimeMultiplier)||1.5}"></label><label class="field"><span>الفرع</span><select name="branchId">${A.options(d.branches.filter(x=>x.active),'id','name',item?.branchId||S.activeBranchId)}</select></label><label class="field"><span>الحالة</span><select name="active"><option value="1" ${item?.active!==false?'selected':''}>نشط</option><option value="0" ${item?.active===false?'selected':''}>موقوف</option></select></label></div>`,onSubmit:fd=>{const data=item||{id:A.uid('WRK'),createdAt:A.now()};Object.assign(data,{employeeNo:fd.get('employeeNo').trim(),name:fd.get('name').trim(),phone:fd.get('phone').trim(),jobTitle:fd.get('jobTitle').trim(),basicSalary:num(fd.get('basicSalary')),allowances:num(fd.get('allowances')),shiftStart:fd.get('shiftStart')||'08:00',shiftEnd:fd.get('shiftEnd')||'16:00',overtimeMultiplier:num(fd.get('overtimeMultiplier'))||1.5,branchId:fd.get('branchId'),active:fd.get('active')==='1',updatedAt:A.now()});if(!data.name)throw Error('اكتب اسم العامل.');if(!item)d.workers.push(data);ensureWorkerAccount(data);A.audit(item?'تعديل عامل':'إضافة عامل','العمال',data.name);A.saveDB();A.toast('تم حفظ بطاقة العامل');A.renderCurrent()}})}
  function openAdjustment(worker){A.openModal({title:`خصم أو إضافة - ${worker.name}`,body:`<div class="form-grid"><label class="field"><span>التاريخ</span><input name="date" type="date" value="${A.today()}"></label><label class="field"><span>النوع</span><select name="type"><option value="deduction">خصم من الراتب</option><option value="allowance">إضافة للراتب</option></select></label><label class="field"><span>المبلغ</span><input name="amount" type="number" min="0.01" step="0.01" required></label><label class="field full"><span>السبب</span><input name="reason" required placeholder="مثال: كسر جهاز، غياب، مكافأة"></label></div>`,onSubmit:fd=>{D().payrollAdjustments.push({id:A.uid('ADJ'),workerId:worker.id,date:fd.get('date'),type:fd.get('type'),amount:num(fd.get('amount')),reason:fd.get('reason').trim(),createdAt:A.now()});A.audit('تسجيل تعديل راتب','الرواتب',`${worker.name} — ${fd.get('reason')}`);A.saveDB();A.toast('تم تسجيل الحركة على راتب العامل');A.renderCurrent()}})}

  function timeToMinutes(v){if(!v)return 0;const [h,m]=v.split(':').map(Number);return h*60+m}
  function renderAttendance(root){const d=D(),month=S.attMonth||A.today().slice(0,7),list=d.attendance.filter(x=>String(x.date).startsWith(month));root.innerHTML=`${A.pageHead('الدوام والإجازات','',`${action('add-attendance','تسجيل دوام','plus')}<input id="attendanceMonth" type="month" value="${month}" class="toolbar-month">`)}<article class="panel">${A.table(['التاريخ','العامل','الحضور','الانصراف','الحالة','تأخير','إضافي','الإجراءات'],list.map(x=>`<tr><td>${A.dateFmt(x.date)}</td><td><b>${esc(workerBy(x.workerId)?.name||'—')}</b></td><td>${esc(x.checkIn||'—')}</td><td>${esc(x.checkOut||'—')}</td><td>${A.badge(x.status==='absent'?'غياب':x.status==='leave'?'إجازة':'حضور',x.status==='present'?'green':x.status==='leave'?'primary':'red')}</td><td>${num(x.lateMinutes)} دقيقة</td><td>${num(x.overtimeMinutes)} دقيقة</td><td>${iconBtn('delete-attendance','trash','حذف',`data-id="${x.id}"`)}</td></tr>`),A.emptyState('clock','لا توجد سجلات دوام',''))}</article>`;$('#attendanceMonth').onchange=e=>{S.attMonth=e.target.value;A.renderCurrent()}}
  function openAttendance(){const d=D();if(!d.workers.length)return A.toast('أضف عاملًا أولاً.','warning');A.openModal({title:'تسجيل دوام',body:`<div class="form-grid"><label class="field"><span>العامل</span><select name="workerId">${A.options(d.workers.filter(x=>x.active!==false))}</select></label><label class="field"><span>التاريخ</span><input name="date" type="date" value="${A.today()}"></label><label class="field"><span>الحالة</span><select name="status"><option value="present">حضور</option><option value="absent">غياب</option><option value="leave">إجازة</option></select></label><label class="field"><span>وقت الحضور</span><input name="checkIn" type="time"></label><label class="field"><span>وقت الانصراف</span><input name="checkOut" type="time"></label></div>`,onSubmit:fd=>{const w=workerBy(fd.get('workerId')),status=fd.get('status'),ci=fd.get('checkIn'),co=fd.get('checkOut');let late=0,ot=0;if(status==='present'){late=Math.max(0,timeToMinutes(ci)-timeToMinutes(w.shiftStart));ot=Math.max(0,timeToMinutes(co)-timeToMinutes(w.shiftEnd))}d.attendance.push({id:A.uid('ATT'),workerId:w.id,date:fd.get('date'),status,checkIn:ci,checkOut:co,lateMinutes:late,overtimeMinutes:ot,createdAt:A.now()});A.audit('تسجيل دوام','العمال',`${w.name} ${fd.get('date')}`);A.saveDB();A.toast('تم تسجيل الدوام');A.renderCurrent()}})}

  function renderLoans(root){const d=D();root.innerHTML=`${A.pageHead('السلف والقروض','',action('add-loan','صرف سلفة','plus'))}<article class="panel">${A.table(['العامل','التاريخ','المبلغ','القسط','المتبقي','الحالة','الإجراءات'],d.employeeLoans.map(l=>`<tr><td><b>${esc(workerBy(l.workerId)?.name||'—')}</b></td><td>${A.dateFmt(l.date)}</td><td>${A.money(l.amount)}</td><td>${A.money(l.installment)}</td><td><b>${A.money(l.remaining)}</b></td><td>${A.badge(num(l.remaining)>0?'نشطة':'مسددة',num(l.remaining)>0?'amber':'green')}</td><td>${iconBtn('delete-loan','trash','حذف وعكس',`data-id="${l.id}"`)}</td></tr>`),A.emptyState('voucher','لا توجد سلف',''))}</article>`}
  function openLoan(){const d=D();if(!d.workers.length)return A.toast('أضف عاملًا أولاً.','warning');const accounts=A.paymentAccounts();A.openModal({title:'صرف سلفة / قرض',body:`<div class="form-grid"><label class="field"><span>العامل</span><select name="workerId">${A.options(d.workers.filter(x=>x.active!==false))}</select></label><label class="field"><span>التاريخ</span><input name="date" type="date" value="${A.today()}"></label><label class="field"><span>المبلغ</span><input name="amount" type="number" min="0.01" step="0.01" required></label><label class="field"><span>قسط شهري</span><input name="installment" type="number" min="0.01" step="0.01" required></label><label class="field"><span>حساب الصرف</span><select name="accountId">${accounts.map(a=>`<option value="${a.id}">${esc(a.code)} — ${esc(a.name)}</option>`).join('')}</select></label><label class="field full"><span>ملاحظات</span><input name="notes"></label></div>`,onSubmit:fd=>{const amount=num(fd.get('amount')),installment=num(fd.get('installment')),w=workerBy(fd.get('workerId')),accountId=fd.get('accountId');if(amount<=0||installment<=0)throw Error('تحقق من المبلغ والقسط.');const loan={id:A.uid('LOAN'),workerId:w.id,date:fd.get('date'),amount,installment,remaining:amount,accountId,notes:fd.get('notes'),createdAt:A.now()};d.employeeLoans.push(loan);A.postJournal(`سلفة عامل - ${w.name}`,loan.id,[{accountId:'ACC-1500',debit:amount,credit:0},{accountId,debit:0,credit:amount}],loan.date,true);A.audit('صرف سلفة','الرواتب',`${w.name} — ${amount}`);A.saveDB();A.toast('تم صرف السلفة وترحيل القيد');A.renderCurrent()}})}

  function payrollRow(worker,month){
    const d=D(),days=d.attendance.filter(x=>x.workerId===worker.id&&String(x.date).startsWith(month)),daily=num(worker.basicSalary)/30,hourly=daily/8,absent=days.filter(x=>x.status==='absent').length,lateMin=days.reduce((a,x)=>a+num(x.lateMinutes),0),otMin=days.reduce((a,x)=>a+num(x.overtimeMinutes),0),attendanceDeduction=absent*daily+(lateMin/60)*hourly,overtime=(otMin/60)*hourly*(num(worker.overtimeMultiplier)||1.5),adjust=d.payrollAdjustments.filter(x=>x.workerId===worker.id&&String(x.date).startsWith(month)),additions=adjust.filter(x=>x.type==='allowance').reduce((a,x)=>a+num(x.amount),0),deductions=adjust.filter(x=>x.type==='deduction').reduce((a,x)=>a+num(x.amount),0),loan=d.employeeLoans.find(x=>x.workerId===worker.id&&num(x.remaining)>0),loanDeduction=loan?Math.min(num(loan.installment),num(loan.remaining)):0,gross=num(worker.basicSalary)+num(worker.allowances)+overtime+additions,salaryExpense=Math.max(0,gross-attendanceDeduction),net=Math.max(0,salaryExpense-deductions-loanDeduction);return{workerId:worker.id,workerName:worker.name,basic:num(worker.basicSalary),allowances:num(worker.allowances)+additions,overtime:Number(overtime.toFixed(2)),attendanceDeduction:Number(attendanceDeduction.toFixed(2)),otherDeductions:Number(deductions.toFixed(2)),loanDeduction:Number(loanDeduction.toFixed(2)),loanId:loan?.id||'',salaryExpense:Number(salaryExpense.toFixed(2)),net:Number(net.toFixed(2))}
  }
  function renderPayroll(root){const d=D(),month=S.payrollMonth||A.today().slice(0,7),existing=d.payrollSheets.find(x=>x.month===month),rows=existing?.rows||d.workers.filter(x=>x.active!==false).map(w=>payrollRow(w,month)),total=rows.reduce((a,x)=>a+num(x.net),0);root.innerHTML=`${A.pageHead('مسيرات الرواتب','',`<input id="payrollMonth" type="month" value="${month}" class="toolbar-month">${existing?existing.posted?'':action('post-payroll','ترحيل ودفع','check'):action('save-payroll','حفظ المسير','save')}`)}<div class="stat-strip"><div><small>العاملون</small><strong>${rows.length}</strong></div><div><small>صافي الرواتب</small><strong>${A.money(total)}</strong></div><div><small>السلف المخصومة</small><strong>${A.money(rows.reduce((a,x)=>a+num(x.loanDeduction),0))}</strong></div><div><small>الحالة</small><strong>${existing?.posted?'مرحّل':existing?'محفوظ':'مسودة'}</strong></div></div><article class="panel">${A.table(['العامل','الأساسي','البدلات','الإضافي','خصم دوام','خصومات','قسط سلفة','الصافي','إجراء'],rows.map(r=>`<tr><td><b>${esc(r.workerName)}</b></td><td>${A.money(r.basic)}</td><td>${A.money(r.allowances)}</td><td>${A.money(r.overtime)}</td><td>${A.money(r.attendanceDeduction)}</td><td>${A.money(r.otherDeductions)}</td><td>${A.money(r.loanDeduction)}</td><td><b>${A.money(r.net)}</b></td><td>${iconBtn('share-payslip','phone','إرسال عبر واتساب',`data-worker="${r.workerId}" data-month="${month}"`)}</td></tr>`))}</article>`;S.currentPayrollRows=rows;$('#payrollMonth').onchange=e=>{S.payrollMonth=e.target.value;A.renderCurrent()}}

  function renderChat(root){const d=D(),me=A.currentUser(),contacts=d.employees.filter(x=>x.active&&x.id!==me.id),toId=S.chatToId||contacts[0]?.id||'',msgs=d.messages.filter(m=>(m.fromId===me.id&&m.toId===toId)||(m.fromId===toId&&m.toId===me.id)).slice(-120);root.innerHTML=`${A.pageHead('الدردشة الداخلية','')}<div class="chat-shell"><aside class="chat-contacts">${contacts.map(c=>`<button class="chat-contact ${c.id===toId?'active':''}" data-action="chat-contact" data-id="${c.id}"><span class="avatar">${esc(c.name.slice(0,1))}</span><span><b>${esc(c.name)}</b><small>${esc(c.role||'موظف')}</small></span></button>`).join('')||'<div class="purchase-empty-lines">لا يوجد موظفون آخرون</div>'}</aside><section class="chat-room"><div class="chat-messages">${msgs.map(m=>`<div class="chat-bubble ${m.fromId===me.id?'mine':''}"><span>${esc(m.text)}</span><small>${A.dateFmt(m.createdAt,true)}</small></div>`).join('')||'<div class="purchase-empty-lines">ابدأ المحادثة</div>'}</div><form id="chatForm" class="chat-composer"><input id="chatText" autocomplete="off" placeholder="رسالة نصية..." ${toId?'':'disabled'}><button class="btn btn-primary" type="submit" ${toId?'':'disabled'}>${I('arrow')} إرسال</button></form></section></div>`;$('#chatForm')?.addEventListener('submit',e=>{e.preventDefault();const text=$('#chatText').value.trim();if(!text||!toId)return;d.messages.push({id:A.uid('MSG'),fromId:me.id,toId,text,createdAt:A.now()});A.saveDB();A.renderCurrent()})}

  function reportRows(type,from,to){
    const d=D(),between=x=>(!from||x>=from)&&(!to||x<=to),until=x=>(!to||x<=to),journals=(d.journals||[]);
    const accountPeriod=(id)=>{let debit=0,credit=0;for(const j of journals.filter(j=>between(j.date)))for(const l of j.lines||[])if(l.accountId===id){debit+=num(l.debit);credit+=num(l.credit)}return{debit,credit}};
    const accountTo=(id)=>{let debit=0,credit=0;for(const j of journals.filter(j=>until(j.date)))for(const l of j.lines||[])if(l.accountId===id){debit+=num(l.debit);credit+=num(l.credit)}const a=d.accounts.find(x=>x.id===id);return ['liability','equity','revenue'].includes(a?.type)?credit-debit:debit-credit};
    const leaves=()=>{const parents=new Set(d.accounts.map(a=>a.parentId).filter(Boolean));return d.accounts.filter(a=>!parents.has(a.id))};
    if(type==='trial')return{title:'ميزان المراجعة',headers:['الحساب','مدين','دائن','الرصيد'],rows:leaves().map(a=>{const p=accountPeriod(a.id),creditNature=['liability','equity','revenue'].includes(a.type),balance=creditNature?p.credit-p.debit:p.debit-p.credit;return[`${a.code} — ${a.name}`,p.debit,p.credit,balance]})};
    if(type==='balance'){
      const assets=d.accounts.filter(a=>a.type==='asset'&&!d.accounts.some(x=>x.parentId===a.id)).reduce((s,a)=>s+accountTo(a.id),0),liabilities=d.accounts.filter(a=>a.type==='liability'&&!d.accounts.some(x=>x.parentId===a.id)).reduce((s,a)=>s+accountTo(a.id),0),equity=d.accounts.filter(a=>a.type==='equity'&&!d.accounts.some(x=>x.parentId===a.id)).reduce((s,a)=>s+accountTo(a.id),0),revenue=d.accounts.filter(a=>a.type==='revenue'&&!d.accounts.some(x=>x.parentId===a.id)).reduce((s,a)=>s+accountTo(a.id),0),expense=d.accounts.filter(a=>a.type==='expense'&&!d.accounts.some(x=>x.parentId===a.id)).reduce((s,a)=>s+accountTo(a.id),0),retained=revenue-expense;
      return{title:'الميزانية العمومية',headers:['البيان','القيمة'],rows:[['إجمالي الأصول',assets],['إجمالي الخصوم',liabilities],['حقوق الملكية',equity],['الأرباح المتراكمة المحسوبة',retained],['الخصوم + حقوق الملكية + الأرباح',liabilities+equity+retained],['فرق المعادلة',assets-(liabilities+equity+retained)]]};
    }
    if(type==='income'){
      const revenue=d.accounts.filter(a=>a.type==='revenue').reduce((s,a)=>{const p=accountPeriod(a.id);return s+p.credit-p.debit},0),expenses=d.accounts.filter(a=>a.type==='expense').reduce((s,a)=>{const p=accountPeriod(a.id);return s+p.debit-p.credit},0);return{title:'قائمة الدخل',headers:['البيان','القيمة'],rows:[['الإيرادات',revenue],['المصروفات',expenses],['صافي الربح',revenue-expenses]]};
    }
    if(type==='cashflow'){
      const ids=new Set(A.paymentAccounts().map(a=>a.id));let inflow=0,outflow=0;for(const j of journals.filter(j=>between(j.date)))for(const l of j.lines||[])if(ids.has(l.accountId)){inflow+=num(l.debit);outflow+=num(l.credit)}return{title:'التدفقات النقدية والبنكية',headers:['البيان','القيمة'],rows:[['التدفقات الداخلة',inflow],['التدفقات الخارجة',outflow],['صافي التدفق',inflow-outflow]]};
    }
    if(type==='aging'){
      const now=to?new Date(to+'T00:00:00'):new Date(),map=new Map();d.sales.filter(x=>x.status!=='returned'&&num(x.due)>0&&until(x.date)).forEach(x=>{const key=x.customerId||x.customerName,row=map.get(key)||{name:x.customerName,current:0,d31:0,d61:0,d90:0,total:0},age=Math.max(0,Math.floor((now-new Date(x.date+'T00:00:00'))/86400000)),v=num(x.due);if(age<=30)row.current+=v;else if(age<=60)row.d31+=v;else if(age<=90)row.d61+=v;else row.d90+=v;row.total+=v;map.set(key,row)});return{title:'أعمار ذمم العملاء',headers:['العميل','0–30','31–60','61–90','أكثر من 90','الإجمالي'],rows:[...map.values()].map(r=>[r.name,r.current,r.d31,r.d61,r.d90,r.total])};
    }
    if(type==='tax'){
      const output=d.sales.filter(x=>x.status!=='returned'&&between(x.date)).reduce((a,x)=>a+num(x.tax),0),input=d.purchases.filter(x=>x.status!=='cancelled'&&between(x.date)).reduce((a,x)=>a+num(x.tax),0);return{title:'تقرير الضرائب',headers:['البيان','القيمة'],rows:[['ضريبة المخرجات',output],['ضريبة المدخلات',input],['صافي الضريبة المستحقة',output-input]]};
    }
    if(type==='stockmove'){const rows=[];d.purchases.filter(x=>x.status!=='cancelled'&&between(x.date)).forEach(x=>(x.lines||[]).forEach(l=>rows.push([x.date,'شراء',l.productName,l.unitName,l.qty,l.baseQty,A.warehouseName(x.warehouseId)])));d.sales.filter(x=>x.status!=='returned'&&between(x.date)).forEach(x=>(x.lines||[]).filter(l=>l.trackStock!==false).forEach(l=>rows.push([x.date,'بيع',l.productName,l.unitName,-num(l.qty),-num(l.baseQty),A.warehouseName(x.warehouseId)])));d.transfers.filter(x=>x.status!=='cancelled'&&between(x.date)).forEach(x=>rows.push([x.date,'نقل',x.productName,x.unitName||'أساسية',x.unitQty||x.qty,x.baseQty||x.qty,`${A.warehouseName(x.fromId)} → ${A.warehouseName(x.toId)}`]));return{title:'حركة المخزون',headers:['التاريخ','الحركة','الصنف','الوحدة','الكمية','كمية أساسية','الموقع'],rows}}
    if(type==='reps')return{title:'عمولات المناديب',headers:['المندوب','المبيعات الصافية','نسبة العمولة','العمولة المستحقة'],rows:d.representatives.map(r=>{const sales=d.sales.filter(s=>s.status!=='returned'&&s.representativeId===r.id&&between(s.date)),value=sales.reduce((a,s)=>a+num(s.total)-num(s.tax),0),comm=sales.reduce((a,s)=>a+num(s.commissionAmount),0);return[r.name,value,`${num(r.commission)}%`,comm]})};
    if(type==='payroll')return{title:'الرواتب',headers:['الشهر','الحالة','العاملون','صافي الرواتب'],rows:d.payrollSheets.filter(s=>(!from||s.month>=from.slice(0,7))&&(!to||s.month<=to.slice(0,7))).map(s=>[s.month,s.posted?'مرحّل':'محفوظ',String(s.rows.length),s.rows.reduce((a,r)=>a+num(r.net),0)])};
    return{title:'كشف أرصدة الحسابات',headers:['الحساب','الرصيد'],rows:leaves().map(a=>[`${a.code} — ${a.name}`,accountTo(a.id)])}
  }
  function renderReportsPro(root){const first=new Date();first.setDate(1);S.proReportType=S.proReportType||'trial';S.proReportFrom=S.proReportFrom||first.toISOString().slice(0,10);S.proReportTo=S.proReportTo||A.today();const r=reportRows(S.proReportType,S.proReportFrom,S.proReportTo);root.innerHTML=`${A.pageHead('التقارير المالية','',action('export-pro-report','تصدير Excel','download','btn-secondary'))}<article class="panel"><div class="toolbar"><select id="proReportType" class="filter-select"><option value="trial">ميزان المراجعة</option><option value="balance">الميزانية العمومية</option><option value="income">قائمة الدخل</option><option value="cashflow">التدفقات النقدية</option><option value="aging">أعمار الذمم</option><option value="tax">الضرائب</option><option value="stockmove">حركة المخزون</option><option value="reps">عمولات المناديب</option><option value="payroll">الرواتب</option></select><div class="date-range"><input id="proReportFrom" type="date" value="${S.proReportFrom}"><input id="proReportTo" type="date" value="${S.proReportTo}"></div></div>${A.table(r.headers,r.rows.map(row=>`<tr>${row.map((c,i)=>`<td>${typeof c==='number'&&i>0?A.money(c):esc(c)}</td>`).join('')}</tr>`),A.emptyState('reports','لا توجد بيانات',''))}</article>`;$('#proReportType').value=S.proReportType;$('#proReportType').onchange=e=>{S.proReportType=e.target.value;A.renderCurrent()};$('#proReportFrom').onchange=e=>{S.proReportFrom=e.target.value;A.renderCurrent()};$('#proReportTo').onchange=e=>{S.proReportTo=e.target.value;A.renderCurrent()}}

  A.registerView('taxes',renderTaxes);A.registerView('workers',renderWorkers);A.registerView('attendance',renderAttendance);A.registerView('loans',renderLoans);A.registerView('payroll',renderPayroll);A.registerView('chat',renderChat);A.registerView('reports',renderReportsPro);
  A.registerAction('add-tax',()=>openTax());A.registerAction('edit-tax',b=>openTax(D().taxes.find(x=>x.id===b.dataset.id)));A.registerAction('delete-tax',b=>{const t=D().taxes.find(x=>x.id===b.dataset.id);if(!t||t.system)return;A.confirmDialog('حذف الضريبة',t.name,()=>{D().taxes=D().taxes.filter(x=>x.id!==t.id);A.saveDB();A.renderCurrent()})});
  A.registerAction('add-worker',()=>openWorker());A.registerAction('edit-worker',b=>openWorker(workerBy(b.dataset.id)));A.registerAction('worker-adjustment',b=>openAdjustment(workerBy(b.dataset.id)));A.registerAction('delete-worker',b=>{const d=D(),w=workerBy(b.dataset.id);if(!w)return;if(d.employeeLoans.some(x=>x.workerId===w.id)||d.payrollSheets.some(s=>(s.rows||[]).some(r=>r.workerId===w.id))||d.attendance.some(x=>x.workerId===w.id)||d.payrollAdjustments.some(x=>x.workerId===w.id))return A.toast('لا يمكن حذف عامل مرتبط بدوام أو رواتب أو سلف؛ أوقفه بدلاً من ذلك.','warning',5000);A.confirmDialog('حذف العامل',w.name,()=>{d.workers=d.workers.filter(x=>x.id!==w.id);A.audit('حذف عامل','العمال',w.name);A.saveDB();A.renderCurrent()})});
  A.registerAction('add-attendance',openAttendance);A.registerAction('delete-attendance',b=>{D().attendance=D().attendance.filter(x=>x.id!==b.dataset.id);A.saveDB();A.renderCurrent()});
  A.registerAction('add-loan',openLoan);A.registerAction('delete-loan',b=>{const d=D(),l=d.employeeLoans.find(x=>x.id===b.dataset.id);if(!l)return;const remaining=num(l.remaining);A.confirmDialog('حذف السلفة',`سيتم عكس الرصيد المتبقي فقط (${A.money(remaining)}) من الحسابات.`,()=>{if(remaining>0)A.postJournal('عكس سلفة عامل',l.id,[{accountId:l.accountId||d.settings.defaultAccountId,debit:remaining,credit:0},{accountId:'ACC-1500',debit:0,credit:remaining}],A.today(),true);d.employeeLoans=d.employeeLoans.filter(x=>x.id!==l.id);A.audit('حذف سلفة','العمال',l.id);A.saveDB();A.renderCurrent()})});
  A.registerAction('save-payroll',()=>{const d=D(),month=S.payrollMonth||A.today().slice(0,7);if(d.payrollSheets.some(x=>x.month===month))return A.toast('المسير محفوظ مسبقاً.','warning');d.payrollSheets.push({id:A.uid('PAYROLL'),month,rows:A.clone(S.currentPayrollRows||[]),posted:false,createdAt:A.now()});A.audit('حفظ مسير رواتب','الرواتب',month);A.saveDB();A.toast('تم حفظ مسير الرواتب');A.renderCurrent()});
  A.registerAction('post-payroll',()=>{const d=D(),month=S.payrollMonth||A.today().slice(0,7),sheet=d.payrollSheets.find(x=>x.month===month);if(!sheet||sheet.posted)return;const accountId=d.settings.defaultAccountId||A.paymentAccounts()[0]?.id||'ACC-1110';A.confirmDialog('ترحيل الرواتب',`سيتم ترحيل ودفع صافي رواتب ${month} من الحساب الافتراضي.`,()=>{for(const r of sheet.rows){const w=workerBy(r.workerId);if(!w)continue;const salaryExpense=num(r.salaryExpense);if(salaryExpense<=0)continue;ensureWorkerAccount(w);const workerAcc=ensureWorkerAccount(w);A.postJournal(`استحقاق راتب ${w.name} - ${month}`,sheet.id,[{accountId:'ACC-5300',debit:salaryExpense,credit:0},{accountId:workerAcc,debit:0,credit:salaryExpense}],A.today(),true);A.postJournal(`تسوية راتب ${w.name} - ${month}`,sheet.id,[{accountId:workerAcc,debit:salaryExpense,credit:0},{accountId, debit:0,credit:num(r.net)},{accountId:'ACC-1500',debit:0,credit:num(r.loanDeduction)},{accountId:'ACC-4300',debit:0,credit:num(r.otherDeductions)}],A.today(),true);if(r.loanId){const loan=d.employeeLoans.find(x=>x.id===r.loanId);if(loan)loan.remaining=Math.max(0,Number((num(loan.remaining)-num(r.loanDeduction)).toFixed(2)))}}sheet.posted=true;sheet.postedAt=A.now();A.audit('ترحيل مسير رواتب','الرواتب',month);A.saveDB();A.toast('تم ترحيل الرواتب وتحديث السلف والحسابات');A.renderCurrent()},false)});
  A.registerAction('share-payslip',b=>{const w=workerBy(b.dataset.worker),sheet=D().payrollSheets.find(x=>x.month===b.dataset.month),r=(sheet?.rows||S.currentPayrollRows||[]).find(x=>x.workerId===w?.id);if(!w||!r)return;const text=`قسيمة راتب ${b.dataset.month}\n${w.name}\nالأساسي: ${A.money(r.basic)}\nالبدلات: ${A.money(r.allowances)}\nالإضافي: ${A.money(r.overtime)}\nالخصومات: ${A.money(r.attendanceDeduction+r.otherDeductions+r.loanDeduction)}\nالصافي: ${A.money(r.net)}`;const phone=String(w.phone||'').replace(/\D/g,'');if(!phone)return A.toast('أضف رقم واتساب للعامل أولاً.','warning');window.open(`https://wa.me/${phone}?text=${encodeURIComponent(text)}`,'_blank')});
  A.registerAction('chat-contact',b=>{S.chatToId=b.dataset.id;A.renderCurrent()});
  A.registerAction('export-pro-report',()=>{const r=reportRows(S.proReportType,S.proReportFrom,S.proReportTo);A.exportExcel(r.title,r.headers,r.rows)});


  // Extend sale reversal to also reverse representative commission.
  if(A.reverseSaleEffect&&!A.reverseSaleEffect._enterpriseWrapped){const baseReverse=A.reverseSaleEffect;const wrapped=function(sale,opts={}){const d=D(),rep=d.representatives.find(r=>r.id===sale?.representativeId),commission=num(sale?.commissionAmount);if(rep&&commission>0&&!sale._commissionReversed){const acc=A.ensureRepAccount(rep);rep.balance=Number((num(rep.balance)-commission).toFixed(2));A.postJournal(`عكس عمولة مندوب ${rep.name} - ${sale.number}`,sale.number,[{accountId:acc,debit:commission,credit:0},{accountId:'ACC-5500',debit:0,credit:commission}],A.today(),true);if(opts.markReturned!==false)sale._commissionReversed=true}return baseReverse(sale,opts)};wrapped._enterpriseWrapped=true;A.reverseSaleEffect=wrapped}

  A.registerAction('purchase-camera-scan',()=>A.scanBarcodeCamera({title:'مسح باركود للمشتريات',onDetected:code=>{const hit=A.findProductByBarcode(code);if(!hit)return A.toast('الباركود غير مسجل في الأصناف.','warning');if(!S.purchaseDraft)return;const draft=S.purchaseDraft;draft.date=$('#purDate')?.value||draft.date;draft.supplierId=$('#purSupplier')?.value??draft.supplierId;draft.warehouseId=$('#purWarehouse')?.value||draft.warehouseId;draft.paid=num($('#purPaid')?.value??draft.paid);draft.paymentAccountId=$('#purAccount')?.value||draft.paymentAccountId;draft.reference=$('#purReference')?.value??draft.reference;draft.add.productId=hit.product.id;draft.add.unitId=hit.unit.id;draft.add.unitCost=num(hit.unit.purchasePrice)||num(hit.product.cost);draft.add.taxRate=num(hit.product.taxRate??D().settings.taxRate);A.renderCurrent()}}));

  function openTransferPro(){const d=D();if(!d.products.length||d.warehouses.filter(x=>x.active).length<2)return A.toast('تحتاج صنفاً ومستودعين على الأقل.','warning');const p=d.products.find(x=>x.active!==false)||d.products[0];A.openModal({title:'نقل مخزني بالوحدة',size:'modal-lg',body:`<div class="form-grid cols-3"><label class="field"><span>التاريخ</span><input name="date" type="date" value="${A.today()}"></label><label class="field"><span>الصنف</span><select name="productId" id="trProduct">${A.options(d.products.filter(x=>x.active!==false))}</select></label><label class="field"><span>الوحدة</span><select name="unitId" id="trUnit">${A.options(p.units||[])}</select></label><label class="field"><span>من مستودع</span><select name="fromId">${A.options(d.warehouses.filter(x=>x.active))}</select></label><label class="field"><span>إلى مستودع</span><select name="toId">${A.options(d.warehouses.filter(x=>x.active))}</select></label><label class="field"><span>الكمية</span><input name="qty" type="number" min="0.00000001" step="any" value="1"></label><label class="field full"><span>ملاحظات / مرجع</span><input name="notes"></label></div>`,onSubmit:fd=>{const product=d.products.find(x=>x.id===fd.get('productId')),unit=A.productUnit(product,fd.get('unitId')),from=fd.get('fromId'),to=fd.get('toId'),unitQty=num(fd.get('qty')),baseQty=unitQty*num(unit.factor||1);if(from===to)throw Error('اختر مستودعين مختلفين.');if(product.trackStock===false)throw Error('الصنف غير مخزني ولا يحتاج نقل.');if(A.stockQty(product.id,from)+1e-8<baseQty)throw Error('الرصيد غير كافٍ في مستودع المصدر.');A.adjustStock(product.id,from,-baseQty);A.adjustStock(product.id,to,baseQty);const x={id:A.uid('TRF'),number:A.nextNo('transfer','TRF-'),date:fd.get('date'),productId:product.id,productName:product.name,unitId:unit.id,unitName:unit.name,factor:num(unit.factor||1),unitQty,baseQty,qty:baseQty,fromId:from,toId:to,notes:fd.get('notes'),status:'posted',createdAt:A.now(),userId:A.currentUser().id};d.transfers.unshift(x);A.audit('نقل مخزني','المخزون',`${x.number} — ${product.name} ${unitQty} ${unit.name}`);A.saveDB();A.toast('تم النقل وتحديث المستودعين');A.renderCurrent()},afterOpen:form=>{const ps=A.$('#trProduct',form),us=A.$('#trUnit',form);ps.onchange=()=>{const product=d.products.find(x=>x.id===ps.value);us.innerHTML=A.options(product.units||[]);A.enhanceSelects(form)}}})}
  function renderTransfersPro(root){const d=D();root.innerHTML=`${A.pageHead('النقل المخزني','',action('add-transfer','نقل جديد','transfer'))}<article class="panel">${A.table(['الرقم','التاريخ','الصنف','الوحدة','الكمية','من','إلى','الحالة','الإجراءات'],d.transfers.map(x=>`<tr><td class="text-primary">${esc(x.number)}</td><td>${A.dateFmt(x.date)}</td><td><b>${esc(x.productName)}</b></td><td>${esc(x.unitName||'أساسية')}</td><td>${num(x.unitQty||x.qty)} ${esc(x.unitName||'')}</td><td>${esc(A.warehouseName(x.fromId))}</td><td>${esc(A.warehouseName(x.toId))}</td><td>${A.badge(x.status==='cancelled'?'ملغي':'مرحّل',x.status==='cancelled'?'red':'green')}</td><td><div class="table-actions">${x.status!=='cancelled'?iconBtn('cancel-transfer','refresh','عكس',`data-id="${x.id}"`):''}${iconBtn('delete-transfer','trash','حذف',`data-id="${x.id}"`)}</div></td></tr>`),A.emptyState('transfer','لا توجد تحويلات',''))}</article>`}
  A.registerView('transfers',renderTransfersPro);A.registerAction('add-transfer',openTransferPro);A.registerAction('cancel-transfer',b=>{const d=D(),x=d.transfers.find(t=>t.id===b.dataset.id);if(!x||x.status==='cancelled')return;const q=num(x.baseQty||x.qty);if(A.stockQty(x.productId,x.toId)+1e-8<q)return A.toast('رصيد مستودع الوجهة أقل من كمية النقل ولا يمكن عكسه.','warning');A.confirmDialog('عكس النقل',x.number,()=>{A.adjustStock(x.productId,x.toId,-q);A.adjustStock(x.productId,x.fromId,q);x.status='cancelled';x.cancelledAt=A.now();A.audit('عكس نقل','المخزون',x.number);A.saveDB();A.renderCurrent()})});A.registerAction('delete-transfer',b=>{const d=D(),x=d.transfers.find(t=>t.id===b.dataset.id);if(!x)return;A.confirmDialog('حذف النقل',x.number,()=>{const q=num(x.baseQty||x.qty);if(x.status!=='cancelled'){if(A.stockQty(x.productId,x.toId)+1e-8<q)return A.toast('لا يمكن الحذف قبل توفر كمية العكس.','warning');A.adjustStock(x.productId,x.toId,-q);A.adjustStock(x.productId,x.fromId,q)}d.transfers=d.transfers.filter(t=>t.id!==x.id);A.audit('حذف نقل','المخزون',x.number);A.saveDB();A.renderCurrent()})});

  // Re-apply UI once DOM is ready so newly added permissions/nav are reflected on first load.
  document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{ensureEnterpriseDB();if(A.currentUser())A.renderCurrent()},0));
})();
