/* Al-Meezan Pro v7.83 — expiry/wastage + phone camera bridge. Additive layer only. */
(()=>{
'use strict';
const A=window.AlMezan;if(!A)return;const S=A.state,D=()=>A.db,num=A.num,esc=A.esc;
const PHONE_KEY='almezan_phone_scanner_v783';
let hostPeer=null,hostConn=null,hostReadyPromise=null,hostAuthenticated=false;
const css=`
#phoneScannerSettingsV783{scroll-margin-top:78px}.phone-scanner-status{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.phone-scanner-dot{width:9px;height:9px;border-radius:50%;background:#9ca3af;box-shadow:0 0 0 3px rgba(156,163,175,.14)}.phone-scanner-status.connected .phone-scanner-dot{background:#16a34a;box-shadow:0 0 0 3px rgba(22,163,74,.14)}.phone-scanner-status.connecting .phone-scanner-dot{background:#d97706}.phone-scanner-status.error .phone-scanner-dot{background:#dc2626}.phone-scanner-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.phone-scanner-note{font-size:12px;line-height:1.8;color:var(--muted,#697587);margin-top:8px}.phone-pair-box{display:grid;grid-template-columns:minmax(190px,230px) 1fr;gap:18px;align-items:center}.phone-pair-qr{background:#fff;border:1px solid #dce3ea;border-radius:16px;padding:12px;display:grid;place-items:center}.phone-pair-qr svg{width:100%;height:auto;display:block}.phone-pair-copy h3{margin:0 0 8px;font-size:17px}.phone-pair-copy p{margin:4px 0;font-size:13px;line-height:1.8}.phone-pair-status{margin-top:10px;padding:9px 11px;border:1px solid #dce3ea;border-radius:10px;background:#f8fafc}.expiry-alert-group{border:1px solid rgba(220,38,38,.18);border-radius:12px;overflow:hidden;margin-bottom:10px}.expiry-alert-toolbar{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:10px;background:rgba(220,38,38,.06)}.expiry-alert-item{border-top:1px solid rgba(220,38,38,.1)}.purchase-lines-table .pur-line-expiry{min-width:138px}.purchase-lines-table .pur-line-batch{min-width:110px}.purchase-add-row{align-items:end}
@media(max-width:700px){.phone-pair-box{grid-template-columns:1fr}.phone-pair-qr{max-width:250px;margin:auto}.expiry-alert-toolbar{align-items:stretch;flex-direction:column}.expiry-alert-item{align-items:flex-start;flex-wrap:wrap}.expiry-alert-item .btn{margin-inline-start:auto}}
`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
function uidPart(){try{return crypto.randomUUID().replace(/-/g,'').slice(0,18)}catch(_){return Math.random().toString(36).slice(2)+Date.now().toString(36)}}
function loadPhone(){try{return JSON.parse(localStorage.getItem(PHONE_KEY)||'{}')}catch(_){return{}}}
function savePhone(patch){const next={...loadPhone(),...patch,updatedAt:Date.now()};localStorage.setItem(PHONE_KEY,JSON.stringify(next));updatePhoneUi();return next}
function safeSend(conn,data){try{if(conn?.open)conn.send(data)}catch(_){}}
function phoneStatus(){if(hostConn?.open&&hostAuthenticated)return{tone:'connected',label:'متصلة وجاهزة للمسح'};if(hostPeer&&!hostPeer.destroyed)return{tone:'connecting',label:'بانتظار كاميرا الجوال'};const c=loadPhone();return c.lastError?{tone:'error',label:'غير متصلة'}:{tone:'',label:c.pairedAt?'غير متصلة — يمكن إعادة الربط':'لم يتم ربط كاميرا جوال'}}
function updatePhoneUi(){const st=phoneStatus(),markup=`<span class="phone-scanner-dot"></span><b>${esc(st.label)}</b>`;document.querySelectorAll('[data-phone-scanner-status]').forEach(el=>{const cls=`phone-scanner-status ${st.tone}`.trim();if(el.className!==cls)el.className=cls;if(el.innerHTML!==markup)el.innerHTML=markup});const modal=document.querySelector('#phonePairLiveStatus');if(modal){const cls=`phone-pair-status phone-scanner-status ${st.tone}`.trim();if(modal.className!==cls)modal.className=cls;if(modal.innerHTML!==markup)modal.innerHTML=markup}}
function branchExpiredLots(){const d=D(),ids=new Set((d.warehouses||[]).filter(w=>!S.activeBranchId||w.branchId===S.activeBranchId).map(w=>w.id));return(d.productBatches||[]).filter(b=>ids.has(b.warehouseId)&&b.expiryDate&&b.expiryDate<A.today()&&num(b.qtyBase)>0)}
function ensureInventoryCollections(){const d=D();d.productBatches=d.productBatches||[];d.wastageDocs=d.wastageDocs||[];d.sequences=d.sequences||{};d.sequences.wastage=num(d.sequences.wastage)||0}
function disposeExpired(ids=null){ensureInventoryCollections();const d=D(),wanted=ids?new Set(ids):null,lots=branchExpiredLots().filter(l=>!wanted||wanted.has(l.id));if(!lots.length){A.toast('لا توجد كميات منتهية قابلة للإتلاف.','warning');return false}
  const groups=new Map();let skipped=0,totalRemoved=0;
  for(const lot of lots){const p=d.products.find(x=>x.id===lot.productId);if(!p)continue;const inStock=Math.max(0,num(A.stockQty(lot.productId,lot.warehouseId))),requested=Math.max(0,num(lot.qtyBase)),qty=Math.min(requested,inStock);if(qty<=1e-8){skipped++;continue}const cost=num(lot.cost||p.cost||0),lineCost=Number((qty*cost).toFixed(2));lot.qtyBase=Number((requested-qty).toFixed(8));A.adjustStock(lot.productId,lot.warehouseId,-qty);totalRemoved+=qty;const g=groups.get(lot.warehouseId)||{warehouseId:lot.warehouseId,lines:[],totalCost:0};g.lines.push({productId:p.id,productName:p.name,qtyBase:qty,consumptions:[{productId:p.id,warehouseId:lot.warehouseId,batchId:lot.id,batchNo:lot.batchNo||'',expiryDate:lot.expiryDate||'',qtyBase:qty,unitCost:cost,totalCost:lineCost}],costTotal:lineCost});g.totalCost+=lineCost;groups.set(lot.warehouseId,g)}
  if(!groups.size){A.toast('تعذر نقل المنتهي للتالف لأن الرصيد الفعلي لا يغطي التشغيلات. راجع تسوية المخزون.','warning',5500);return false}
  for(const g of groups.values()){const number=`WST-${String(++d.sequences.wastage).padStart(6,'0')}`,totalCost=Number(g.totalCost.toFixed(2)),doc={id:A.uid('WST'),number,date:A.today(),warehouseId:g.warehouseId,reason:'منتهي الصلاحية',notes:'إضافة منتهيات الصلاحية تلقائياً من مركز التنبيهات',lines:g.lines,totalCost,createdAt:A.now()};d.wastageDocs.unshift(doc);if(totalCost>.009)A.postJournal(`سند إتلاف ${number}`,number,[{accountId:'ACC-5230',debit:totalCost,credit:0},{accountId:'ACC-1300',debit:0,credit:totalCost}],doc.date,true);A.audit('إتلاف منتهي الصلاحية','المخزون',`${number} — ${g.lines.length} تشغيلة`)}
  A.saveDB(true);A.closeModal?.();A.renderCurrent();A.toast(`تمت إضافة المنتهي للتالف وخصمه من المخزون${skipped?' — توجد تشغيلات تحتاج مراجعة رصيد':''}`,'success',4500);return totalRemoved>0
}
A.registerAction('v783-expire-all-wastage',()=>A.confirmDialog('إضافة كل المنتهي للتالف','سيتم إنشاء سند/سندات إتلاف وخصم الكميات المنتهية من المخزون وترحيل تكلفتها محاسبياً.',()=>disposeExpired()));
A.registerAction('v783-expire-lot-wastage',b=>{const lot=(D().productBatches||[]).find(x=>x.id===b.dataset.id),p=D().products.find(x=>x.id===lot?.productId);if(!lot)return;A.confirmDialog('إضافة للتالف',`سيتم خصم الكمية المنتهية من ${p?.name||'الصنف'} ونقلها إلى سجل التالف.`,()=>disposeExpired([lot.id]))});

function loadPeerJs(){if(window.Peer)return Promise.resolve(window.Peer);if(window.__almezanPeerLoading)return window.__almezanPeerLoading;const urls=['https://unpkg.com/peerjs@1.5.5/dist/peerjs.min.js','https://cdn.jsdelivr.net/npm/peerjs@1.5.5/dist/peerjs.min.js'];window.__almezanPeerLoading=(async()=>{let last;for(const src of urls){try{await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.async=true;s.crossOrigin='anonymous';s.onload=resolve;s.onerror=()=>reject(Error('load'));document.head.appendChild(s)});if(window.Peer)return window.Peer}catch(e){last=e}}throw Error('تعذر تحميل خدمة الربط WebRTC. تأكد من وجود إنترنت عند إنشاء الاتصال، أو استخدم Local PeerServer/Bridge في الشبكة المحلية.')})().finally(()=>{window.__almezanPeerLoading=null});return window.__almezanPeerLoading}
function makeHostConfig(regenerate=false){let c=loadPhone();if(regenerate||!c.hostId||!c.pairToken)c=savePhone({hostId:`almezan-${uidPart()}`,pairToken:uidPart()+uidPart(),pairedAt:regenerate?'':c.pairedAt||'',remotePeer:'',lastError:''});return c}
function destroyHost(){try{hostConn?.close?.()}catch(_){}try{hostPeer?.destroy?.()}catch(_){}hostConn=null;hostPeer=null;hostReadyPromise=null;hostAuthenticated=false;updatePhoneUi()}
async function ensureHost(regenerate=false){if(regenerate)destroyHost();if(hostPeer&&!hostPeer.destroyed&&hostPeer.open)return hostPeer;if(hostReadyPromise)return hostReadyPromise;const cfg=makeHostConfig(regenerate);hostReadyPromise=(async()=>{const Peer=await loadPeerJs();let peer=new Peer(cfg.hostId,{debug:0});hostPeer=peer;peer.on('connection',acceptConnection);peer.on('disconnected',()=>{hostAuthenticated=false;savePhone({lastError:'انقطع اتصال الإشارة'});updatePhoneUi()});peer.on('close',()=>{hostAuthenticated=false;updatePhoneUi()});const opened=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('انتهت مهلة الاتصال بخدمة الربط.')),12000);peer.on('open',id=>{clearTimeout(t);resolve(id)});peer.on('error',err=>{clearTimeout(t);reject(err)})}).catch(async err=>{if(/taken|unavailable/i.test(String(err?.type||err?.message||''))&&!regenerate){destroyHost();savePhone({hostId:`almezan-${uidPart()}`,pairToken:uidPart()+uidPart(),remotePeer:'',pairedAt:'',lastError:''});return ensureHost(true)}throw err});savePhone({lastError:'',hostId:opened||cfg.hostId});updatePhoneUi();return hostPeer})().finally(()=>{hostReadyPromise=null});return hostReadyPromise}
function acceptConnection(conn){hostAuthenticated=false;if(hostConn&&hostConn!==conn){try{hostConn.close()}catch(_){}}hostConn=conn;updatePhoneUi();let authTimer=setTimeout(()=>{if(!hostAuthenticated)try{conn.close()}catch(_){}},8000);conn.on('open',()=>updatePhoneUi());conn.on('data',msg=>{const cfg=loadPhone();if(!hostAuthenticated){if(msg?.type==='hello'&&String(msg.token||'')===String(cfg.pairToken||'')){clearTimeout(authTimer);hostAuthenticated=true;savePhone({pairedAt:Date.now(),remotePeer:conn.peer||'',lastError:'',autoResume:true});safeSend(conn,{type:'paired',companyName:D().company?.name||'الميزان',at:Date.now()});updatePhoneUi();A.toast('تم ربط كاميرا الجوال بنجاح','success');return}safeSend(conn,{type:'auth-error',message:'رمز الربط غير صحيح'});try{conn.close()}catch(_){}return}
    if(msg?.type==='ping'){safeSend(conn,{type:'pong',at:Date.now()});return}
    if(msg?.type==='barcode'){const code=String(msg.code||'').trim();if(!code)return;const hit=A.findProductByBarcode?.(code);if(S.view!=='cashier')A.navigate('cashier');setTimeout(()=>{let ok=false;try{ok=!!A.cashierAddScannedCode?.(code)}catch(e){console.error(e)}safeSend(conn,{type:'scan-result',ok,code,productName:hit?.product?.name||'',unitName:hit?.unit?.name||'',message:ok?'تمت الإضافة إلى الفاتورة':(hit?'تعذر إضافة الصنف إلى السلة':'الباركود غير مسجل'),at:Date.now()})},S.view==='cashier'?0:60)}});conn.on('close',()=>{if(hostConn===conn){hostConn=null;hostAuthenticated=false;updatePhoneUi()}});conn.on('error',err=>{savePhone({lastError:String(err?.message||err||'خطأ اتصال')});updatePhoneUi()})}
function scannerUrl(){const c=makeHostConfig(false),u=new URL('mobile-scanner.html',location.href);u.hash=new URLSearchParams({peer:c.hostId,token:c.pairToken}).toString();return u.href}
async function openPairModal(regenerate=false){await ensureHost(regenerate);const url=scannerUrl(),qr=window.AlMezanPrinterManager?.qrSvg?.(url,260)||`<div style="word-break:break-all">${esc(url)}</div>`;A.openModal({title:'ربط كاميرا جوال',size:'modal-lg',hideSubmit:true,body:`<div class="phone-pair-box"><div class="phone-pair-qr">${qr}</div><div class="phone-pair-copy"><h3>اربط الجوال مع الكاشير</h3><p>1) افتح <b>mobile-scanner.html</b> على الجوال أو امسح هذا الـQR بكاميرا الجوال.</p><p>2) في تطبيق القارئ اضغط <b>مسح باركود الربط</b> إذا لم يُفتح الرابط تلقائياً.</p><p>3) بعد ظهور <b>تم الربط</b> يفتح ماسح المنتجات ويرسل الباركود مباشرة إلى سلة الكاشير.</p><p><b>مهم:</b> استخدم الجهازين على نفس شبكة Wi‑Fi. الربط WebRTC حقيقي، لكن إصدار Web/PWA يحتاج خدمة إشارة عبر الإنترنت عند إنشاء الاتصال ما لم تستخدم PeerServer/Bridge محلياً.</p><div id="phonePairLiveStatus" class="phone-pair-status"></div><div class="phone-scanner-actions"><button type="button" class="btn btn-secondary" data-action="v783-phone-pair-new">إنشاء رمز ربط جديد</button><button type="button" class="btn btn-secondary" data-action="v783-phone-open-scanner">فتح تطبيق القارئ</button></div></div></div>`});updatePhoneUi()}
function mountPhoneSettings(root){if(!root||root.querySelector('#phoneScannerSettingsV783'))return;const form=root.querySelector('#settingsForm'),grid=form?.querySelector('.grid-equal');if(!grid)return;const section=document.createElement('section');section.id='phoneScannerSettingsV783';section.className='settings-section settings-subsection';section.innerHTML=`<div class="settings-section-head"><div><h3>كاميرا جوال كقارئ باركود</h3><small>ربط جوال ثانٍ بالـQR وإرسال الباركود مباشرة إلى الكاشير</small></div></div><div data-phone-scanner-status class="phone-scanner-status"></div><div class="phone-scanner-actions"><button type="button" class="btn btn-primary" data-action="v783-phone-pair">${A.I?.('camera',16)||''} ربط كاميرا جوال</button><button type="button" class="btn btn-secondary" data-action="v783-phone-reconnect">إعادة اتصال</button><button type="button" class="btn btn-danger btn-sm" data-action="v783-phone-unpair">إلغاء الربط</button></div><div class="phone-scanner-note">يبقى الربط فعالاً أثناء التنقل بين صفحات التطبيق لأن النظام SPA. بعد إعادة تحميل التطبيق يحاول استعادة جلسة الربط المحفوظة تلقائياً عندما تتوفر خدمة الإشارة.</div>`;grid.appendChild(section);A.injectIcons?.(section);updatePhoneUi();const nav=root.querySelector('.settings-v771-nav');if(nav&&!nav.querySelector('[data-setting-jump="كاميرا الجوال"]')){const b=document.createElement('button');b.type='button';b.dataset.settingJump='كاميرا الجوال';b.textContent='كاميرا الجوال';b.onclick=()=>section.scrollIntoView({behavior:'smooth',block:'start'});nav.appendChild(b)}}
A.registerAction('v783-phone-pair',()=>openPairModal(false).catch(e=>A.toast(String(e?.message||e),'error',7000)));
A.registerAction('v783-phone-pair-new',()=>{A.closeModal?.();openPairModal(true).catch(e=>A.toast(String(e?.message||e),'error',7000))});
A.registerAction('v783-phone-open-scanner',()=>{const u=scannerUrl();window.open(u,'_blank','noopener')});
A.registerAction('v783-phone-reconnect',()=>{destroyHost();ensureHost(false).then(()=>A.toast('تم تشغيل نقطة ربط كاميرا الجوال','success')).catch(e=>A.toast(String(e?.message||e),'error',7000))});
A.registerAction('v783-phone-unpair',()=>A.confirmDialog('إلغاء ربط كاميرا الجوال','سيتم إبطال رمز الربط الحالي. يلزم مسح رمز جديد للاتصال مرة أخرى.',()=>{destroyHost();savePhone({hostId:`almezan-${uidPart()}`,pairToken:uidPart()+uidPart(),pairedAt:'',remotePeer:'',autoResume:false,lastError:''});A.toast('تم إلغاء الربط');A.renderCurrent()}));
const baseSettings=A.state?.views?.settings;if(baseSettings)A.state.views.settings=root=>{baseSettings(root);try{mountPhoneSettings(root)}catch(e){console.error('Phone scanner settings mount failed',e);A.toast?.('تم فتح الإعدادات، لكن تعذر تحميل قسم كاميرا الجوال.','warning',5000)}};
let phoneSettingsMountQueued=false;const phoneSettingsRoot=document.querySelector('#workspace')||document.body;const observer=new MutationObserver(()=>{if(S.view!=='settings'||phoneSettingsMountQueued)return;phoneSettingsMountQueued=true;requestAnimationFrame(()=>{phoneSettingsMountQueued=false;if(S.view!=='settings')return;try{mountPhoneSettings(document.querySelector('#workspace'));updatePhoneUi()}catch(e){console.error('Phone scanner settings observer failed',e)}})});observer.observe(phoneSettingsRoot,{childList:true,subtree:false});
window.AlMezanPhoneScanner={openPairModal,ensureHost,disposeExpired,mountPhoneSettings,updateUi:updatePhoneUi,get status(){return phoneStatus()},get settings(){return loadPhone()}};
setTimeout(()=>{const c=loadPhone();if(c.autoResume&&c.hostId&&c.pairToken)ensureHost(false).catch(()=>{})},1800);
})();
