/* Al-Meezan Pro v7.83 — expiry/wastage + phone camera bridge. Additive layer only. */
(()=>{
'use strict';
const A=window.AlMezan;if(!A)return;const S=A.state,D=()=>A.db,num=A.num,esc=A.esc;
const PHONE_KEY='almezan_phone_scanner_v783';
let hostPeer=null,hostConn=null,hostReadyPromise=null,hostAuthenticated=false,hostDirectAuthenticated=false,relayClient=null,relayTopic='',relayAuthenticated=false,relayReadyPromise=null,relayBrokerIndex=0,relayReconnectTimer=0;
const css=`
#phoneScannerSettingsV783{scroll-margin-top:78px}.phone-scanner-status{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.phone-scanner-dot{width:9px;height:9px;border-radius:50%;background:#9ca3af;box-shadow:0 0 0 3px rgba(156,163,175,.14)}.phone-scanner-status.connected .phone-scanner-dot{background:#16a34a;box-shadow:0 0 0 3px rgba(22,163,74,.14)}.phone-scanner-status.connecting .phone-scanner-dot{background:#d97706}.phone-scanner-status.error .phone-scanner-dot{background:#dc2626}.phone-scanner-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.phone-scanner-note{font-size:12px;line-height:1.8;color:var(--muted,#697587);margin-top:8px}.phone-pair-box{display:grid;grid-template-columns:minmax(190px,230px) 1fr;gap:18px;align-items:center}.phone-pair-qr{background:#fff;border:1px solid #dce3ea;border-radius:16px;padding:12px;display:grid;place-items:center}.phone-pair-qr svg{width:100%;height:auto;display:block}.phone-pair-copy h3{margin:0 0 8px;font-size:17px}.phone-pair-copy p{margin:4px 0;font-size:13px;line-height:1.8}.phone-pair-status{margin-top:10px;padding:9px 11px;border:1px solid #dce3ea;border-radius:10px;background:#f8fafc}.expiry-alert-group{border:1px solid rgba(220,38,38,.18);border-radius:12px;overflow:hidden;margin-bottom:10px}.expiry-alert-toolbar{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:10px;background:rgba(220,38,38,.06)}.expiry-alert-item{border-top:1px solid rgba(220,38,38,.1)}.purchase-lines-table .pur-line-expiry{min-width:138px}.purchase-lines-table .pur-line-batch{min-width:110px}.purchase-add-row{align-items:end}
@media(max-width:700px){.phone-pair-box{grid-template-columns:1fr}.phone-pair-qr{max-width:250px;margin:auto}.expiry-alert-toolbar{align-items:stretch;flex-direction:column}.expiry-alert-item{align-items:flex-start;flex-wrap:wrap}.expiry-alert-item .btn{margin-inline-start:auto}}
`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
function uidPart(){try{return crypto.randomUUID().replace(/-/g,'').slice(0,18)}catch(_){return Math.random().toString(36).slice(2)+Date.now().toString(36)}}
function loadPhone(){try{return JSON.parse(localStorage.getItem(PHONE_KEY)||'{}')}catch(_){return{}}}
function savePhone(patch){const next={...loadPhone(),...patch,updatedAt:Date.now()};localStorage.setItem(PHONE_KEY,JSON.stringify(next));updatePhoneUi();return next}
function safeSend(conn,data){try{if(conn?.open)conn.send(data)}catch(_){}}
function updatePhoneUi(){const st=phoneStatus(),markup=`<span class="phone-scanner-dot"></span><b>${esc(st.label)}</b>`;document.querySelectorAll('[data-phone-scanner-status]').forEach(el=>{const cls=`phone-scanner-status ${st.tone}`.trim();if(el.className!==cls)el.className=cls;if(el.innerHTML!==markup)el.innerHTML=markup});const modal=document.querySelector('#phonePairLiveStatus');if(modal){const cls=`phone-pair-status phone-scanner-status ${st.tone}`.trim();if(modal.className!==cls)modal.className=cls;if(modal.innerHTML!==markup)modal.innerHTML=markup}}
function branchExpiredLots(){const d=D(),ids=new Set((d.warehouses||[]).filter(w=>!S.activeBranchId||w.branchId===S.activeBranchId).map(w=>w.id));return(d.productBatches||[]).filter(b=>ids.has(b.warehouseId)&&b.expiryDate&&b.expiryDate<A.today()&&num(b.qtyBase)>0)}
function ensureInventoryCollections(){const d=D();d.productBatches=d.productBatches||[];d.wastageDocs=d.wastageDocs||[];d.sequences=d.sequences||{};d.sequences.wastage=num(d.sequences.wastage)||0}
function disposeExpired(ids=null){ensureInventoryCollections();const d=D(),wanted=ids?new Set(ids):null,lots=branchExpiredLots().filter(l=>!wanted||wanted.has(l.id));if(!lots.length){A.toast('لا توجد كميات منتهية قابلة للإتلاف.','warning');return false}
  const groups=new Map();let skipped=0,totalRemoved=0;
  for(const lot of lots){const p=d.products.find(x=>x.id===lot.productId);if(!p)continue;const inStock=Math.max(0,num(A.stockQty(lot.productId,lot.warehouseId))),requested=Math.max(0,num(lot.qtyBase)),qty=Math.min(requested,inStock);if(qty<=1e-8){skipped++;continue}const cost=num(lot.cost||p.cost||0),lineCost=Number((qty*cost).toFixed(2));lot.qtyBase=Number((requested-qty).toFixed(8));A.adjustStock(lot.productId,lot.warehouseId,-qty);totalRemoved+=qty;const g=groups.get(lot.warehouseId)||{warehouseId:lot.warehouseId,lines:[],totalCost:0};g.lines.push({productId:p.id,productName:p.name,qtyBase:qty,consumptions:[{productId:p.id,warehouseId:lot.warehouseId,batchId:lot.id,batchNo:lot.batchNo||'',expiryDate:lot.expiryDate||'',qtyBase:qty,unitCost:cost,totalCost:lineCost}],costTotal:lineCost});g.totalCost+=lineCost;groups.set(lot.warehouseId,g)}
  if(!groups.size){A.toast('تعذر نقل المنتهي للتالف لأن الرصيد الفعلي لا يغطي التشغيلات. راجع تسوية المخزون.','warning',5500);return false}
  for(const g of groups.values()){const number=`WST-${String(++d.sequences.wastage).padStart(6,'0')}`,totalCost=Number(g.totalCost.toFixed(2)),doc={id:A.uid('WST'),number,date:A.today(),warehouseId:g.warehouseId,reason:'منتهي الصلاحية',notes:'إضافة منتهيات الصلاحية تلقائياً من مركز التنبيهات',lines:g.lines,totalCost,createdAt:A.now()};d.wastageDocs.unshift(doc);if(totalCost>.009)A.postJournal(`سند إتلاف ${number}`,number,[{accountId:'ACC-5230',debit:totalCost,credit:0},{accountId:'ACC-1300',debit:0,credit:totalCost}],doc.date,true);A.audit('إتلاف منتهي الصلاحية','المخزون',`${number} — ${g.lines.length} تشغيلة`)}
  A.saveDB(true);A.closeModal?.();A.renderCurrent();A.toast(`تمت إضافة المنتهي للتالف وخصمه من المخزون${skipped?' — توجد تشغيلات تحتاج مراجعة رصيد':''}`,'success',4500);return totalRemoved>0
}
A.registerAction('v783-expire-all-wastage',()=>A.confirmDialog('إضافة كل المنتهي للتالف','سيتم إنشاء سند/سندات إتلاف وخصم الكميات المنتهية من المخزون وترحيل تكلفتها محاسبياً.',()=>disposeExpired()));
A.registerAction('v783-expire-lot-wastage',b=>{const lot=(D().productBatches||[]).find(x=>x.id===b.dataset.id),p=D().products.find(x=>x.id===lot?.productId);if(!lot)return;A.confirmDialog('إضافة للتالف',`سيتم خصم الكمية المنتهية من ${p?.name||'الصنف'} ونقلها إلى سجل التالف.`,()=>disposeExpired([lot.id]))});

function loadScript(urls,check,key){if(check())return Promise.resolve(check());if(window[key])return window[key];window[key]=(async()=>{let last;for(const src of urls){try{await new Promise((resolve,reject)=>{const el=document.createElement('script');el.src=src;el.async=true;el.crossOrigin='anonymous';el.onload=resolve;el.onerror=reject;document.head.appendChild(el)});if(check())return check()}catch(e){last=e}}throw last||Error('تعذر تحميل مكتبة الاتصال')})().finally(()=>window[key]=null);return window[key]}
function loadPeerJs(){return loadScript(['https://unpkg.com/peerjs@1.5.5/dist/peerjs.min.js','https://cdn.jsdelivr.net/npm/peerjs@1.5.5/dist/peerjs.min.js'],()=>window.Peer,'__almezanPeerLoading')}
function loadMqttJs(){return loadScript(['https://unpkg.com/mqtt@5.15.2/dist/mqtt.min.js','https://cdn.jsdelivr.net/npm/mqtt@5.15.2/dist/mqtt.min.js'],()=>window.mqtt?.connect?window.mqtt:null,'__almezanMqttLoading')}
const RELAY_BROKERS=['wss://broker.emqx.io:8084/mqtt','wss://broker.hivemq.com:8884/mqtt'];
const ICE_SERVERS=[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun.relay.metered.ca:80'}];
const _te=new TextEncoder(),_td=new TextDecoder(),recentScanIds=new Map();
function b64Text(s){const bytes=_te.encode(String(s||''));let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function bytesToB64u(bytes){let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64uToBytes(s){s=String(s).replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const bin=atob(s),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
async function digestBytes(v){return new Uint8Array(await crypto.subtle.digest('SHA-256',_te.encode(String(v))))}
async function relayBase(cfg){const d=await digestBytes(`${cfg.hostId}|${cfg.pairToken}|almezan-relay-v7842`);return 'almezan/v7842/'+[...d.slice(0,18)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function relayKey(token){const d=await digestBytes(`${token}|almezan-relay-key-v7842`);return crypto.subtle.importKey('raw',d,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function relayEncode(obj,token){const iv=crypto.getRandomValues(new Uint8Array(12)),key=await relayKey(token),plain=_te.encode(JSON.stringify(obj)),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain)),all=new Uint8Array(iv.length+ct.length);all.set(iv);all.set(ct,iv.length);return bytesToB64u(all)}
async function relayDecode(raw,token){const all=b64uToBytes(String(raw)),iv=all.slice(0,12),ct=all.slice(12),key=await relayKey(token),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,ct);return JSON.parse(_td.decode(plain))}
function makeHostConfig(regenerate=false){let c=loadPhone();if(regenerate||!c.hostId||!c.pairToken)c=savePhone({hostId:`almezan-${uidPart()}`,pairToken:uidPart()+uidPart(),pairedAt:regenerate?'':c.pairedAt||'',remotePeer:'',lastError:''});return c}
function phoneStatus(){if(hostDirectAuthenticated&&hostConn?.open)return{tone:'connected',label:'متصلة — اتصال مباشر'};if(relayAuthenticated&&relayClient?.connected)return{tone:'connected',label:'متصلة — عبر الإنترنت'};if((hostPeer&&!hostPeer.destroyed)||relayClient||relayReadyPromise)return{tone:'connecting',label:'بانتظار كاميرا الجوال'};const c=loadPhone();return c.lastError?{tone:'error',label:'غير متصلة'}:{tone:'',label:c.pairedAt?'غير متصلة — يمكن إعادة الربط':'لم يتم ربط كاميرا جوال'}}
function destroyHost(){clearTimeout(relayReconnectTimer);try{hostConn?.close?.()}catch(_){}try{hostPeer?.destroy?.()}catch(_){}try{relayClient?.end?.(true)}catch(_){}hostConn=null;hostPeer=null;hostReadyPromise=null;hostAuthenticated=false;hostDirectAuthenticated=false;relayClient=null;relayTopic='';relayAuthenticated=false;relayReadyPromise=null;updatePhoneUi()}
async function relaySend(data){const cfg=loadPhone();if(!relayClient?.connected||!relayTopic||!cfg.pairToken)return false;try{const payload=await relayEncode(data,cfg.pairToken);relayClient.publish(relayTopic+'/to-scanner',payload,{qos:0,retain:false});return true}catch(_){return false}}
function scheduleRelayHost(){clearTimeout(relayReconnectTimer);const c=loadPhone();if(!c.hostId||!c.pairToken)return;relayReconnectTimer=setTimeout(()=>ensureRelayHost(c).catch(()=>scheduleRelayHost()),3500)}
async function ensureRelayHost(cfg=makeHostConfig(false)){if(!crypto?.subtle)return false;if(relayClient?.connected&&relayTopic)return true;if(relayReadyPromise)return relayReadyPromise;relayReadyPromise=(async()=>{const mq=await loadMqttJs(),base=await relayBase(cfg);relayTopic=base;for(let off=0;off<RELAY_BROKERS.length;off++){const idx=(relayBrokerIndex+off)%RELAY_BROKERS.length,broker=RELAY_BROKERS[idx];try{const client=await new Promise((resolve,reject)=>{let done=false;const c=mq.connect(broker,{clientId:'almezan-h-'+Math.random().toString(16).slice(2)+Date.now().toString(36),clean:true,connectTimeout:6500,reconnectPeriod:0,keepalive:20,protocolVersion:4});const t=setTimeout(()=>{if(done)return;done=true;try{c.end(true)}catch(_){}reject(Error('relay timeout'))},7500);c.once('connect',()=>{if(done)return;done=true;clearTimeout(t);resolve(c)});c.once('error',e=>{if(done)return;done=true;clearTimeout(t);try{c.end(true)}catch(_){}reject(e)})});relayClient=client;relayBrokerIndex=idx;await new Promise((resolve,reject)=>client.subscribe(base+'/to-host',{qos:0},e=>e?reject(e):resolve()));client.on('message',async(topic,payload)=>{if(topic!==base+'/to-host')return;try{const msg=await relayDecode(payload.toString(),cfg.pairToken);handlePhoneMessage(msg,'relay',null)}catch(_){}});client.on('close',()=>{relayAuthenticated=false;updatePhoneUi();scheduleRelayHost()});client.on('error',()=>{});updatePhoneUi();return true}catch(_){continue}}throw Error('تعذر تشغيل الربط الاحتياطي عبر الإنترنت')})().finally(()=>relayReadyPromise=null);return relayReadyPromise}
async function ensureDirectHost(cfg=makeHostConfig(false)){if(hostPeer&&!hostPeer.destroyed&&hostPeer.open)return hostPeer;if(hostReadyPromise)return hostReadyPromise;hostReadyPromise=(async()=>{const Peer=await loadPeerJs();const peer=new Peer(cfg.hostId,{debug:0,config:{iceServers:ICE_SERVERS,sdpSemantics:'unified-plan'}});hostPeer=peer;peer.on('connection',acceptConnection);peer.on('disconnected',()=>{hostDirectAuthenticated=false;hostAuthenticated=relayAuthenticated;updatePhoneUi()});peer.on('close',()=>{hostDirectAuthenticated=false;hostAuthenticated=relayAuthenticated;updatePhoneUi()});const opened=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('انتهت مهلة الاتصال المباشر.')),11000);peer.once('open',id=>{clearTimeout(t);resolve(id)});peer.once('error',err=>{clearTimeout(t);reject(err)})});savePhone({lastError:'',hostId:opened||cfg.hostId});updatePhoneUi();return hostPeer})().finally(()=>hostReadyPromise=null);return hostReadyPromise}
async function ensureHost(regenerate=false){if(regenerate)destroyHost();let cfg=makeHostConfig(regenerate);let results=await Promise.allSettled([ensureDirectHost(cfg),ensureRelayHost(cfg)]);const directErr=results[0].status==='rejected'?results[0].reason:null;if(directErr&&/taken|unavailable/i.test(String(directErr?.type||directErr?.message||''))&&!regenerate){destroyHost();cfg=makeHostConfig(true);results=await Promise.allSettled([ensureDirectHost(cfg),ensureRelayHost(cfg)])}if(results.every(x=>x.status==='rejected')){savePhone({lastError:'تعذر تشغيل الربط'});throw Error('تعذر تشغيل الاتصال المباشر أو الاتصال عبر الإنترنت')}savePhone({lastError:''});return hostPeer||relayClient}
function sourceSend(via,conn,data){if(via==='direct'){safeSend(conn,data);return true}relaySend(data);return true}
function seenScan(id){if(!id)return false;const now=Date.now();for(const [k,t] of recentScanIds)if(now-t>10000)recentScanIds.delete(k);if(recentScanIds.has(id))return true;recentScanIds.set(id,now);return false}
function handlePhoneMessage(msg,via,conn){const cfg=loadPhone(),auth=via==='direct'?hostDirectAuthenticated:relayAuthenticated;if(!auth){if(msg?.type==='hello'&&String(msg.token||'')===String(cfg.pairToken||'')){if(via==='direct'){hostDirectAuthenticated=true;hostAuthenticated=true}else{relayAuthenticated=true;hostAuthenticated=true}savePhone({pairedAt:Date.now(),remotePeer:conn?.peer||cfg.remotePeer||'',lastError:'',autoResume:true});sourceSend(via,conn,{type:'paired',companyName:D().company?.name||'الميزان',at:Date.now(),via});updatePhoneUi();A.toast('تم ربط كاميرا الجوال بنجاح','success');return}sourceSend(via,conn,{type:'auth-error',message:'رمز الربط غير صحيح'});if(via==='direct')try{conn?.close?.()}catch(_){}return}
  if(msg?.type==='ping'){sourceSend(via,conn,{type:'pong',at:Date.now()});return}
  if(msg?.type==='barcode'){const code=String(msg.code||'').trim();if(!code||seenScan(msg.id))return;const hit=A.findProductByBarcode?.(code);if(S.view!=='cashier')A.navigate('cashier');setTimeout(()=>{let ok=false;try{ok=!!A.cashierAddScannedCode?.(code)}catch(e){console.error(e)}sourceSend(via,conn,{type:'scan-result',id:msg.id||'',ok,code,productName:hit?.product?.name||'',unitName:hit?.unit?.name||'',message:ok?'تمت الإضافة إلى الفاتورة':(hit?'تعذر إضافة الصنف إلى السلة':'الباركود غير مسجل'),at:Date.now()})},S.view==='cashier'?0:60)}
}
function acceptConnection(conn){if(hostConn&&hostConn!==conn){try{hostConn.close()}catch(_){}}hostConn=conn;hostDirectAuthenticated=false;hostAuthenticated=relayAuthenticated;updatePhoneUi();let authTimer=setTimeout(()=>{if(!hostDirectAuthenticated)try{conn.close()}catch(_){}},8000);conn.on('open',()=>updatePhoneUi());conn.on('data',msg=>{if(msg?.type==='hello')clearTimeout(authTimer);handlePhoneMessage(msg,'direct',conn)});conn.on('close',()=>{if(hostConn===conn){hostConn=null;hostDirectAuthenticated=false;hostAuthenticated=relayAuthenticated;updatePhoneUi()}});conn.on('error',err=>{savePhone({lastError:String(err?.message||err||'خطأ اتصال')});updatePhoneUi()})}
function scannerUrl(){const c=makeHostConfig(false),u=new URL('mobile-scanner.html',location.href);u.hash=new URLSearchParams({peer:c.hostId,token:c.pairToken}).toString();return u.href}
function pairCode(){const c=makeHostConfig(false);return `MZPAIR1.${b64Text(c.hostId)}.${b64Text(c.pairToken)}`}
async function openPairModal(regenerate=false){await ensureHost(regenerate);const code=pairCode(),qr=window.AlMezanPrinterManager?.qrSvg?.(code,260)||`<div style="word-break:break-all">${esc(code)}</div>`;A.openModal({title:'ربط كاميرا جوال',size:'modal-lg',hideSubmit:true,body:`<div class="phone-pair-box"><div class="phone-pair-qr">${qr}</div><div class="phone-pair-copy"><h3>ربط قارئ الجوال</h3><p>امسح رمز الربط من تطبيق القارئ.</p><p>يستخدم اتصالاً مباشراً سريعاً متى أمكن، ويتحول تلقائياً إلى اتصال إنترنت مشفر عند الحاجة.</p><div id="phonePairLiveStatus" class="phone-pair-status"></div><div class="phone-scanner-actions"><button type="button" class="btn btn-secondary" data-action="v783-phone-pair-new">رمز جديد</button><button type="button" class="btn btn-secondary" data-action="v783-phone-open-scanner">فتح القارئ</button></div></div></div>`});updatePhoneUi()}
function mountPhoneSettings(root){if(!root||root.querySelector('#phoneScannerSettingsV783'))return;const form=root.querySelector('#settingsForm'),grid=form?.querySelector('.grid-equal');if(!grid)return;const section=document.createElement('section');section.id='phoneScannerSettingsV783';section.className='settings-section settings-subsection';section.innerHTML=`<div class="settings-section-head"><div><h3>كاميرا جوال كقارئ باركود</h3><small>ربط جوال ثانٍ بالـQR وإرسال الباركود مباشرة إلى الكاشير</small></div></div><div data-phone-scanner-status class="phone-scanner-status"></div><div class="phone-scanner-actions"><button type="button" class="btn btn-primary" data-action="v783-phone-pair">${A.I?.('camera',16)||''} ربط كاميرا جوال</button><button type="button" class="btn btn-secondary" data-action="v783-phone-reconnect">إعادة اتصال</button><button type="button" class="btn btn-danger btn-sm" data-action="v783-phone-unpair">إلغاء الربط</button></div><div class="phone-scanner-note">يبقى الربط فعالاً أثناء التنقل بين صفحات التطبيق لأن النظام SPA. بعد إعادة تحميل التطبيق يحاول استعادة جلسة الربط المحفوظة تلقائياً عندما تتوفر خدمة الإشارة.</div>`;grid.appendChild(section);A.injectIcons?.(section);updatePhoneUi();const nav=root.querySelector('.settings-v771-nav');if(nav&&!nav.querySelector('[data-setting-jump="كاميرا الجوال"]')){const b=document.createElement('button');b.type='button';b.dataset.settingJump='كاميرا الجوال';b.textContent='كاميرا الجوال';b.onclick=()=>section.scrollIntoView({behavior:'smooth',block:'start'});nav.appendChild(b)}}
A.registerAction('v783-phone-pair',()=>openPairModal(false).catch(e=>A.toast(String(e?.message||e),'error',7000)));
A.registerAction('v783-phone-pair-new',()=>{A.closeModal?.();openPairModal(true).catch(e=>A.toast(String(e?.message||e),'error',7000))});
A.registerAction('v783-phone-open-scanner',()=>{const u=scannerUrl();window.open(u,'_blank','noopener')});
A.registerAction('v783-phone-reconnect',()=>{destroyHost();ensureHost(false).then(()=>A.toast('تم تشغيل ربط كاميرا الجوال','success')).catch(e=>A.toast(String(e?.message||e),'error',7000))});
A.registerAction('v783-phone-unpair',()=>A.confirmDialog('إلغاء ربط كاميرا الجوال','سيتم إبطال رمز الربط الحالي. يلزم مسح رمز جديد للاتصال مرة أخرى.',()=>{destroyHost();savePhone({hostId:`almezan-${uidPart()}`,pairToken:uidPart()+uidPart(),pairedAt:'',remotePeer:'',autoResume:false,lastError:''});A.toast('تم إلغاء الربط');A.renderCurrent()}));
const baseSettings=A.state?.views?.settings;if(baseSettings)A.state.views.settings=root=>{baseSettings(root);try{mountPhoneSettings(root)}catch(e){console.error('Phone scanner settings mount failed',e);A.toast?.('تم فتح الإعدادات، لكن تعذر تحميل قسم كاميرا الجوال.','warning',5000)}};
let phoneSettingsMountQueued=false;const phoneSettingsRoot=document.querySelector('#workspace')||document.body;const observer=new MutationObserver(()=>{if(S.view!=='settings'||phoneSettingsMountQueued)return;phoneSettingsMountQueued=true;requestAnimationFrame(()=>{phoneSettingsMountQueued=false;if(S.view!=='settings')return;try{mountPhoneSettings(document.querySelector('#workspace'));updatePhoneUi()}catch(e){console.error('Phone scanner settings observer failed',e)}})});observer.observe(phoneSettingsRoot,{childList:true,subtree:false});
window.AlMezanPhoneScanner={openPairModal,ensureHost,disposeExpired,mountPhoneSettings,updateUi:updatePhoneUi,get status(){return phoneStatus()},get settings(){return loadPhone()}};
setTimeout(()=>{const c=loadPhone();if(c.autoResume&&c.hostId&&c.pairToken)ensureHost(false).catch(()=>{})},1200);
})();
