/* Al-Meezan Pro v7.53 — multi-line internal transfers, transfer exports/printing, stable cashier search, unified vouchers, branch manager usernames */
(()=>{
'use strict';
const A=window.AlMezan;if(!A)return;
const S=A.state,D=()=>A.db,$=A.$,$$=A.$$,esc=A.esc,num=A.num,I=A.I;
const round=n=>Number(num(n).toFixed(2));
const activeBranch=()=>A.currentUser()?.branchId||S.activeBranchId||D().branches?.[0]?.id||'';
const isBranchManager=()=>A.getSession?.()?.type==='branch-manager'||A.currentUser()?.role==='مدير فرع';
const branchName=id=>D().branches.find(b=>b.id===id)?.name||'—';
const whName=id=>D().warehouses.find(w=>w.id===id)?.name||'—';
const sync=()=>{try{window.AlMezanSync?.syncNow?.({manual:false,force:true})?.catch?.(()=>{})}catch(_){}};
const btn=(action,label,icon='plus',cls='btn-primary',attrs='')=>`<button type="button" class="btn ${cls}" data-action="${action}" ${attrs}>${I(icon,16)} ${esc(label)}</button>`;
const ib=(action,icon,title,attrs='')=>`<button type="button" class="icon-button" data-action="${action}" title="${esc(title)}" ${attrs}>${I(icon,16)}</button>`;

function ensure753(){
 const d=D();d.branchManagers=Array.isArray(d.branchManagers)?d.branchManagers:[];
 for(const m of d.branchManagers){if(!m.username)m.username=`manager-${String(d.branches.find(b=>b.id===m.branchId)?.code||m.id).toLowerCase().replace(/[^a-z0-9_-]+/g,'-')}`;m.permissions=Array.isArray(m.permissions)?m.permissions:[];if(!m.permissions.includes('reports'))m.permissions.push('reports')}
 d.settings.enterpriseSchemaVersion=753;
}
ensure753();A.saveDB(true);

// ---------------- Branch managers: username + downloadable activation file ----------------
const MANAGER_DEFAULT_PERMS=['dashboard','cashier','sales','purchases','inventory','transfers','parties','debts','vouchers','cheques','expenses','reports','employees','branches_view','warehouses_view','warehouses_manage','customer_groups','price_groups','installments','messaging','discount','price_change','sales_return','sales_credit','warehouse_select'];
function usernameTaken(value,exceptId=''){
 const v=String(value||'').trim().toLowerCase();if(!v)return false;
 return [...(D().employees||[]),...(D().branchManagers||[])].some(x=>x.id!==exceptId&&String(x.username||'').trim().toLowerCase()===v);
}
function editBranchManager753(branch){
 const d=D(),m=d.branchManagers.find(x=>x.id===branch.managerId)||d.branchManagers.find(x=>x.branchId===branch.id),selected=m?.permissions?.length?m.permissions:MANAGER_DEFAULT_PERMS,defaultUser=m?.username||`manager-${String(branch.code||branch.name||'branch').toLowerCase().replace(/[^a-z0-9_-]+/g,'-')}`;
 A.openModal({title:`مدير ${branch.name}`,size:'modal-lg',body:`<div class="form-grid cols-3"><label class="field"><span>اسم مدير الفرع</span><input name="name" value="${esc(m?.name||'')}" required></label><label class="field"><span>اسم المستخدم</span><input name="username" value="${esc(defaultUser)}" autocomplete="off" required></label><label class="field"><span>الفرع</span><input value="${esc(branch.name)}" readonly></label><label class="field"><span>الحالة</span><select name="active"><option value="1" ${m?.active!==false?'selected':''}>نشط</option><option value="0" ${m?.active===false?'selected':''}>موقوف</option></select></label></div><section class="form-section"><h4>صلاحيات مدير الفرع</h4><div class="permissions-grid">${A.PERMISSIONS.filter(([id])=>!['branch_select','branches_manage','settings'].includes(id)).map(([id,label])=>`<label class="permission-item"><input type="checkbox" name="permission" value="${id}" ${selected.includes(id)?'checked':''}><span>${esc(label)}</span></label>`).join('')}</div></section><div class="first-login-note">مدير الفرع حساب مستقل عن الموظفين. ملف دخوله يفتح هذا الفرع فقط، ويستطيع إدارة موظفيه ومستودعاته والنقل المخزني وصلاحياته المسموح بها.</div>`,onSubmit:fd=>{
   const name=String(fd.get('name')||'').trim(),username=String(fd.get('username')||'').trim(),permissions=fd.getAll('permission');if(!name)throw Error('اكتب اسم مدير الفرع.');if(!username)throw Error('اكتب اسم المستخدم.');if(usernameTaken(username,m?.id||''))throw Error('اسم المستخدم مستخدم لحساب آخر.');if(!permissions.length)throw Error('اختر صلاحية واحدة على الأقل.');
   const target=m||{id:A.uid('BRM'),role:'مدير فرع',isBranchManager:true,branchId:branch.id,createdAt:A.now(),authVersion:A.uid('AUTH')};Object.assign(target,{name,username,active:fd.get('active')==='1',permissions,branchId:branch.id,role:'مدير فرع',isBranchManager:true,updatedAt:A.now()});if(!m)d.branchManagers.push(target);branch.managerId=target.id;branch.updatedAt=A.now();A.audit(m?'تعديل مدير فرع':'تعيين مدير فرع','الفروع',`${branch.name} — ${target.name} (${target.username})`);A.saveDB();sync();A.toast('تم حفظ مدير الفرع ومزامنة صلاحياته');A.renderCurrent();
 }})
}
function branchesView753(root){
 const d=D(),bid=activeBranch(),list=isBranchManager()?d.branches.filter(b=>b.id===bid):d.branches;
 root.innerHTML=`${A.pageHead('الفروع','إدارة مستقلة لكل فرع ومدير دخول مستقل',isBranchManager()?'':(S.actions['add-branch']?btn('add-branch','إضافة فرع','plus'):''))}<article class="panel">${A.table(['الفرع','الكود','المستودعات','الموظفون','مدير الفرع','اسم المستخدم','ملف الدخول','الحالة','الإجراءات'],list.map(b=>{const m=d.branchManagers.find(x=>x.id===b.managerId),ec=d.employees.filter(e=>!e.system&&!e.representativeId&&e.branchId===b.id).length;return `<tr><td><b>${esc(b.name)}</b></td><td>${esc(b.code||'')}</td><td>${d.warehouses.filter(w=>w.branchId===b.id).length}</td><td>${ec}</td><td>${m?`<b>${esc(m.name)}</b>`:'غير معين'}</td><td>${m?`<code>${esc(m.username||'—')}</code>`:'—'}</td><td>${m?`<button class="btn btn-secondary btn-sm" data-action="download-branch-manager-v752" data-id="${b.id}" ${m.active===false?'disabled':''}>${I('download')} ملف الدخول</button>`:'—'}</td><td>${A.badge(b.active!==false?'نشط':'موقوف',b.active!==false?'green':'red')}</td><td><div class="table-actions">${isBranchManager()?'':`${ib('edit-branch-manager-v753','employees','مدير الفرع',`data-id="${b.id}"`)}${S.actions['edit-branch']?ib('edit-branch','edit','تعديل',`data-id="${b.id}"`):''}`}</div></td></tr>`}) )}</article>`;
}
A.registerView('branches',branchesView753);
A.registerAction('edit-branch-manager-v753',b=>{const br=D().branches.find(x=>x.id===b.dataset.id);if(br)editBranchManager753(br)});
A.registerAction('edit-branch-manager-v752',b=>{const br=D().branches.find(x=>x.id===b.dataset.id);if(br)editBranchManager753(br)});

// ---------------- Unified customer / supplier / representative vouchers ----------------
function partyList(type){const d=D();if(type==='customer')return d.customers||[];if(type==='supplier')return d.suppliers||[];if(type==='representative')return d.representatives||[];return []}
function findParty(type,id){return partyList(type).find(x=>x.id===id)}
function voucherEffect(v){if(Number(v?.partyEffect)===1||Number(v?.partyEffect)===-1)return Number(v.partyEffect);if(v?.partyType==='customer')return v.direction==='receipt'?-1:1;if(v?.partyType==='supplier')return v.direction==='payment'?-1:1;if(v?.partyType==='representative')return v.direction==='payment'?-1:1;return 0}
function voucherLines753(v){
 const amount=round(v.amount),cash=v.accountId||'ACC-1110',effect=voucherEffect(v),meta={branchId:v.branchId||activeBranch()};
 if(v.partyType==='customer')return effect>0?[{accountId:'ACC-1200',debit:amount,credit:0,...meta},{accountId:cash,debit:0,credit:amount,...meta}]:[{accountId:cash,debit:amount,credit:0,...meta},{accountId:'ACC-1200',debit:0,credit:amount,...meta}];
 if(v.partyType==='supplier')return effect>0?[{accountId:cash,debit:amount,credit:0,...meta},{accountId:'ACC-2100',debit:0,credit:amount,...meta}]:[{accountId:'ACC-2100',debit:amount,credit:0,...meta},{accountId:cash,debit:0,credit:amount,...meta}];
 if(v.partyType==='representative'){
   const rep=findParty('representative',v.partyId),repAcc=A.ensureRepAccount?.(rep);if(!repAcc)return [];
   return effect>0?[{accountId:'ACC-5500',debit:amount,credit:0,...meta},{accountId:repAcc,debit:0,credit:amount,...meta}]:[{accountId:repAcc,debit:amount,credit:0,...meta},{accountId:cash,debit:0,credit:amount,...meta}];
 }
 return v.direction==='receipt'?[{accountId:cash,debit:amount,credit:0,...meta},{accountId:'ACC-4100',debit:0,credit:amount,...meta}]:[{accountId:'ACC-520001',debit:amount,credit:0,costCenterId:D().settings.defaultCostCenterId||'',...meta},{accountId:cash,debit:0,credit:amount,...meta}];
}
function applyVoucher753(v,mult=1){const p=findParty(v.partyType,v.partyId),effect=voucherEffect(v);if(p&&effect)p.balance=round(num(p.balance)+mult*effect*num(v.amount));const lines=voucherLines753(v).map(l=>mult===1?l:{...l,debit:l.credit,credit:l.debit});if(lines.length)A.postJournal(`${mult===1?'':'عكس '}${v.direction==='receipt'?'سند قبض':'سند صرف'} ${v.number}`,v.number,lines,v.date||A.today(),true)}
function openUnifiedVoucher(pref={},existing=null){
 const d=D(),v=existing||{},prefType=v.partyType||pref.type||'customer',initialEffect=existing?voucherEffect(existing):(pref.effect??-1),defaultAccount=v.accountId||A.paymentAccounts()[0]?.id||'ACC-1110';
 const scoped=t=>partyList(t).filter(x=>x.active!==false&&!x.system&&(!isBranchManager()||(x.branchId===activeBranch()||(t==='representative'&&(x.allowedBranchIds||[]).includes(activeBranch())))));
 A.openModal({title:existing?'تعديل سند':'سند قبض / صرف',body:`<div class="form-grid"><label class="field"><span>نوع الطرف</span><select name="partyType" id="v753PartyType"><option value="customer" ${prefType==='customer'?'selected':''}>عميل</option><option value="supplier" ${prefType==='supplier'?'selected':''}>مورد</option><option value="representative" ${prefType==='representative'?'selected':''}>مندوب</option><option value="other" ${prefType==='other'?'selected':''}>أخرى</option></select></label><label class="field"><span>تأثير الرصيد</span><select name="partyEffect" id="v753Effect"><option value="1" ${initialEffect>0?'selected':''}>+ زيادة الرصيد</option><option value="-1" ${initialEffect<=0?'selected':''}>− سداد / تخفيض الرصيد</option></select></label><label class="field"><span>نوع السند</span><select name="direction" id="v753Direction"><option value="receipt">سند قبض</option><option value="payment">سند صرف</option></select></label><label class="field"><span>التاريخ</span><input name="date" type="date" value="${esc(v.date||A.today())}" required></label><label class="field"><span>اسم الطرف</span><select name="partyId" id="v753Party" class="searchable-select"></select></label><label class="field"><span>المبلغ (₪)</span><input name="amount" type="number" min="0.01" step="0.01" value="${num(v.amount||pref.amount)||''}" required></label><label class="field"><span>حساب الصندوق / البنك</span><select name="accountId" class="searchable-select">${A.options(A.paymentAccounts(),'id','name',defaultAccount)}</select></label><label class="field"><span>المرجع</span><input name="reference" value="${esc(v.reference||'')}"></label><label class="field full"><span>البيان</span><textarea name="notes">${esc(v.notes??pref.notes??'')}</textarea></label></div><div class="first-login-note">العميل والمورد والمندوب موجودون داخل نفس السند. اختر الطرف ثم + لزيادة رصيده أو − لتسجيل السداد.</div>`,onSubmit:fd=>A.atomicMutation(()=>{
   const type=fd.get('partyType'),effect=type==='other'?0:(Number(fd.get('partyEffect'))||-1),p=findParty(type,fd.get('partyId')),amount=round(fd.get('amount')),date=fd.get('date'),accountId=fd.get('accountId')||'ACC-1110';if(amount<=0)throw Error('اكتب مبلغاً صحيحاً.');if(type!=='other'&&!p)throw Error('اختر الطرف.');A.validateOpenFinancialDate?.(date);if(existing)applyVoucher753(existing,-1);
   let direction=fd.get('direction');if(type==='customer')direction=effect>0?'payment':'receipt';if(type==='supplier')direction=effect>0?'receipt':'payment';if(type==='representative')direction=effect>0?'receipt':'payment';
   const target=existing||{id:A.uid('VCH'),createdAt:A.now()};if(!existing)target.number=A.nextNo('voucher',direction==='receipt'?'RCV-':'PAY-');Object.assign(target,{direction,partyEffect:effect,date,partyType:type,partyId:p?.id||'',partyName:p?.name||'أخرى',amount,accountId,reference:fd.get('reference')||'',notes:fd.get('notes')||'',branchId:p?.branchId||activeBranch(),updatedAt:A.now(),userId:A.currentUser()?.id||''});if(!existing)d.vouchers.unshift(target);applyVoucher753(target,1);A.audit(existing?'تعديل سند':'إضافة سند','السندات',`${target.number} — ${target.partyName} — ${effect>0?'+':'−'}${amount}`);A.saveDB();sync();A.toast('تم حفظ السند وتحديث رصيد الطرف');A.renderCurrent();
 }),afterOpen:form=>{
   const type=$('#v753PartyType',form),effect=$('#v753Effect',form),dir=$('#v753Direction',form),ps=$('#v753Party',form);const syncDirection=()=>{if(type.value==='customer')dir.value=Number(effect.value)>0?'payment':'receipt';else if(type.value==='supplier')dir.value=Number(effect.value)>0?'receipt':'payment';else if(type.value==='representative')dir.value=Number(effect.value)>0?'receipt':'payment'};const fill=()=>{const list=type.value==='other'?[]:scoped(type.value);ps.innerHTML=type.value==='other'?'<option value="">بدون طرف</option>':A.options(list,'id','name',existing?.partyId||pref.id||'');effect.closest('.field').style.display=type.value==='other'?'none':'';syncDirection();A.enhanceSelects(form)};type.onchange=fill;effect.onchange=syncDirection;dir.onchange=()=>{if(type.value==='customer')effect.value=dir.value==='receipt'?'-1':'1';else if(type.value==='supplier')effect.value=dir.value==='payment'?'-1':'1';else if(type.value==='representative')effect.value=dir.value==='payment'?'-1':'1'};fill();
 }});
}
function unifiedVoucherView(root){const d=D(),list=d.vouchers.filter(x=>!isBranchManager()||x.branchId===activeBranch());root.innerHTML=`${A.pageHead('سندات القبض والصرف','عميل أو مورد أو مندوب من نفس نموذج السند',btn('add-voucher-v753','سند جديد','plus'))}<article class="panel">${A.table(['السند','التاريخ','الطرف','نوع الطرف','الأثر','النوع','الحساب','المبلغ','البيان','الإجراءات'],list.map(x=>`<tr><td><b>${esc(x.number)}</b></td><td>${A.dateFmt(x.date)}</td><td>${esc(x.partyName||'أخرى')}</td><td>${esc(x.partyType==='customer'?'عميل':x.partyType==='supplier'?'مورد':x.partyType==='representative'?'مندوب':'أخرى')}</td><td>${x.partyType==='other'?'—':A.badge(voucherEffect(x)>0?'+ زيادة':'− سداد',voucherEffect(x)>0?'amber':'green')}</td><td>${A.badge(x.direction==='receipt'?'قبض':'صرف',x.direction==='receipt'?'green':'red')}</td><td>${esc(d.accounts.find(a=>a.id===x.accountId)?.name||'—')}</td><td><b>${A.money(x.amount)}</b></td><td>${esc(x.notes||'—')}</td><td><div class="table-actions">${ib('edit-voucher-v753','edit','تعديل',`data-id="${x.id}"`)}${A.has('delete')?ib('delete-voucher-v753','trash','حذف وعكس',`data-id="${x.id}"`):''}</div></td></tr>`),A.emptyState('voucher','لا توجد سندات',''))}</article>`}
A.registerView('vouchers',unifiedVoucherView);
A.registerAction('add-voucher-v753',()=>openUnifiedVoucher());A.registerAction('add-voucher',()=>openUnifiedVoucher());A.registerAction('add-voucher-v750',()=>openUnifiedVoucher());
A.registerAction('edit-voucher-v753',b=>openUnifiedVoucher({},D().vouchers.find(x=>x.id===b.dataset.id)));A.registerAction('edit-voucher',b=>openUnifiedVoucher({},D().vouchers.find(x=>x.id===b.dataset.id)));A.registerAction('edit-voucher-v750',b=>openUnifiedVoucher({},D().vouchers.find(x=>x.id===b.dataset.id)));
A.registerAction('rep-voucher-v752',b=>openUnifiedVoucher({type:'representative',id:b?.dataset?.id||''}));A.registerAction('settle-party',b=>{const p=findParty(b.dataset.type,b.dataset.id);openUnifiedVoucher({type:b.dataset.type,id:b.dataset.id,effect:-1,amount:Math.abs(num(p?.balance)),notes:`سداد على حساب ${p?.name||''}`})});
A.registerAction('delete-voucher-v753',b=>{const v=D().vouchers.find(x=>x.id===b.dataset.id);if(!v)return;if(!A.has('delete'))return A.toast('لا تملك صلاحية الحذف.','error');A.confirmDialog('حذف السند',`${v.number} — سيتم عكس أثره بالكامل.`,()=>A.atomicMutation(()=>{applyVoucher753(v,-1);D().vouchers=D().vouchers.filter(x=>x.id!==v.id);A.saveDB();sync();A.toast('تم حذف السند وعكس أثره');A.renderCurrent()}))});
A.registerAction('delete-voucher',b=>S.actions['delete-voucher-v753']?.(b));A.registerAction('delete-voucher-v750',b=>S.actions['delete-voucher-v753']?.(b));

// ---------------- Multi-line internal transfer ----------------
function transferLineRow(line={}){return `<div class="v753-internal-line"><select name="productId" class="searchable-select">${A.options(D().products.filter(p=>p.active!==false&&!p.isVariant),'id','name',line.productId||'')}</select><input name="qty" type="number" min="0.00000001" step="any" value="${num(line.qty)||1}" aria-label="الكمية"><button type="button" class="icon-button v753-remove-line" title="حذف">${I('trash',16)}</button></div>`}
function collectInternalLines(form){const merged=new Map();for(const r of $$('.v753-internal-line',form)){const p=D().products.find(x=>x.id===$('[name=productId]',r)?.value),qty=num($('[name=qty]',r)?.value);if(!p||qty<=0)continue;const u=p.units?.[0],factor=num(u?.factor||1)||1,baseQty=qty*factor,old=merged.get(p.id);if(old){old.qty+=qty;old.baseQty+=baseQty}else merged.set(p.id,{productId:p.id,productName:p.name,unitId:u?.id||'',unitName:u?.name||'',factor,qty,baseQty,unitCost:num(p.cost)})}return [...merged.values()]}
function openInternalTransfer753(){
 const d=D(),bid=isBranchManager()?activeBranch():(S.activeBranchId||d.branches[0]?.id),branches=isBranchManager()?d.branches.filter(b=>b.id===bid):d.branches.filter(b=>b.active!==false);
 A.openModal({title:'نقل مخزني داخل الفرع',size:'modal-xl',body:`<div class="form-grid cols-3"><label class="field"><span>الفرع</span>${isBranchManager()?`<input value="${esc(branchName(bid))}" readonly><input type="hidden" name="branchId" value="${bid}">`:`<select name="branchId" id="v753InternalBranch">${A.options(branches,'id','name',bid)}</select>`}</label><label class="field"><span>من مستودع</span><select name="fromId" id="v753InternalFrom"></select></label><label class="field"><span>إلى مستودع</span><select name="toId" id="v753InternalTo"></select></label><label class="field"><span>التاريخ</span><input name="date" type="date" value="${A.today()}" required></label><label class="field full"><span>ملاحظات</span><input name="notes"></label></div><section class="form-section"><div class="form-section-title"><h4>الأصناف المنقولة</h4><button type="button" class="btn btn-secondary btn-sm" id="v753AddInternalLine">${I('plus')} إضافة صنف</button></div><div id="v753InternalLines">${transferLineRow()}</div></section><div class="first-login-note">يمكن إضافة أكثر من صنف في نفس سند النقل. يتم الخصم من مستودع المصدر والإضافة لمستودع الوجهة داخل نفس الفرع دفعة واحدة.</div>`,submitText:'تنفيذ النقل',onSubmit:(fd,form)=>A.atomicMutation(()=>{
   const branchId=fd.get('branchId')||bid,from=fd.get('fromId'),to=fd.get('toId'),wf=d.warehouses.find(w=>w.id===from),wt=d.warehouses.find(w=>w.id===to),lines=collectInternalLines(form);if(!wf||!wt||wf.branchId!==branchId||wt.branchId!==branchId)throw Error('اختر مستودعين تابعين لنفس الفرع.');if(from===to)throw Error('مستودع المصدر والوجهة يجب أن يكونا مختلفين.');if(!lines.length)throw Error('أضف صنفاً واحداً على الأقل.');for(const l of lines)if(A.stockQty(l.productId,from)+1e-8<num(l.baseQty)&&!d.settings.allowNegative)throw Error(`الرصيد غير كافٍ للصنف: ${l.productName}`);let total=0;for(const l of lines){l.outValue=round(num(l.baseQty)*num(l.unitCost));total+=l.outValue;A.adjustStock(l.productId,from,-num(l.baseQty));A.adjustStock(l.productId,to,num(l.baseQty))}const x={id:A.uid('TRF'),number:A.nextNo('transfer','TRF-'),date:fd.get('date')||A.today(),scope:'internal',fromBranchId:branchId,toBranchId:branchId,fromId:from,toId:to,lines,status:'received',locked:true,totalValue:round(total),notes:fd.get('notes')||'',createdAt:A.now(),receivedAt:A.now(),userId:A.currentUser()?.id||''};d.transfers.unshift(x);A.audit('نقل داخلي متعدد الأصناف','المخزون',`${x.number}: ${whName(from)} → ${whName(to)} (${lines.length} صنف)`);A.saveDB();sync();A.toast('تم نقل جميع الأصناف داخل الفرع');A.renderCurrent();
 }),afterOpen:form=>{
   const br=$('#v753InternalBranch',form),from=$('#v753InternalFrom',form),to=$('#v753InternalTo',form),box=$('#v753InternalLines',form);const fillWh=()=>{const id=br?.value||bid,wh=d.warehouses.filter(w=>w.branchId===id&&w.active!==false);from.innerHTML=A.options(wh,'id','name',wh[0]?.id||'');to.innerHTML=A.options(wh,'id','name',wh[1]?.id||wh[0]?.id||'');A.enhanceSelects(form)};br?.addEventListener('change',fillWh);$('#v753AddInternalLine',form)?.addEventListener('click',()=>{box.insertAdjacentHTML('beforeend',transferLineRow());A.enhanceSelects(box);A.injectIcons(box)});form.addEventListener('click',e=>{const b=e.target.closest('.v753-remove-line');if(!b)return;if(box.children.length<=1)return A.toast('يجب أن يبقى صنف واحد على الأقل.','warning');b.closest('.v753-internal-line')?.remove()});fillWh();A.enhanceSelects(form);
 }});
}
A.registerAction('internal-transfer-v752',openInternalTransfer753);A.registerAction('internal-transfer-v753',openInternalTransfer753);

// ---------------- Transfer Excel / PDF / Print with header ----------------
function transferDoc(kind,id){const d=D();return kind==='request'?d.transferRequests.find(x=>x.id===id):d.transfers.find(x=>x.id===id)}
function transferDocTitle(kind,x){if(kind==='request')return 'طلب تحويل مخزني';return x.scope==='internal'?'سند نقل مخزني داخلي':'سند نقل مخزني بين الفروع'}
function transferFromLabel(kind,x){if(kind==='request')return branchName(x.fromBranchId);return x.scope==='internal'?`${branchName(x.fromBranchId)} / ${whName(x.fromId)}`:branchName(x.fromBranchId)}
function transferToLabel(kind,x){if(kind==='request')return branchName(x.toBranchId);return x.scope==='internal'?`${branchName(x.toBranchId)} / ${whName(x.toId)}`:branchName(x.toBranchId)}
function transferRows(x){return (x.lines||[]).map((l,i)=>[i+1,l.productName||D().products.find(p=>p.id===l.productId)?.name||l.productId,num(l.qty||l.baseQty),l.unitName||'',round(l.unitCost||0),round(l.outValue||num(l.baseQty)*num(l.unitCost||0))])}
function exportTransferExcel(kind,id){const x=transferDoc(kind,id);if(!x)return;const rows=transferRows(x);A.exportExcel(`${transferDocTitle(kind,x)}-${x.number}`,['#','الصنف','الكمية','الوحدة','تكلفة الوحدة','الإجمالي'],rows)}
function printTransferDoc(kind,id,forceA4=false){
 const x=transferDoc(kind,id);if(!x)return;const d=D(),st=d.settings||{},size=forceA4?'a4':(st.printSize||'80'),thermal=size!=='a4',paper=size==='58'?'54mm':size==='80'?'76mm':'auto',title=transferDocTitle(kind,x),rows=transferRows(x),status=x.status==='requested'?'مطلوب':x.status==='in_transit'?'في الطريق':x.status==='received'?'مستلم ومقفل':x.status==='cancelled'?'ملغي':x.status||'—',logo=st.showInvoiceLogo!==false?'brand-logo.png':'';
 const w=window.open('','almezan-transfer-print','width=850,height=900');if(!w)return A.toast('اسمح بالنوافذ المنبثقة للطباعة.','warning');
 const css=thermal?`@page{size:${size==='58'?'58mm':'80mm'} auto;margin:0}body{width:${paper};margin:0 auto;padding:4mm 2mm;font-size:11px}`:`@page{size:A4 portrait;margin:12mm}body{max-width:190mm;margin:0 auto;padding:0;font-size:12px}`;
 const itemRows=rows.map(r=>`<tr>${r.map((c,i)=>`<td>${i>=4?esc(Number(c).toFixed(2)):esc(c)}</td>`).join('')}</tr>`).join('');
 const extra=kind==='transfer'?`<div class="totals"><span>قيمة النقل: <b>${esc(A.money(x.totalValue||0))}</b></span>${num(x.landingCost)>0?`<span>مصاريف الشحن: <b>${esc(A.money(x.landingCost))}</b></span>`:''}${num(x.shortageValue)>0?`<span>العجز/التالف: <b>${esc(A.money(x.shortageValue))}</b></span>`:''}</div>`:'';
 w.document.open();w.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>${esc(title)} ${esc(x.number)}</title><style>*{box-sizing:border-box}html,body{background:#fff;color:#000}body{font-family:Tahoma,Arial,sans-serif;line-height:1.45}${css}.head{text-align:center;border-bottom:2px solid #000;padding-bottom:7px;margin-bottom:8px}.head img{width:${thermal?'38mm':'30mm'};max-height:${thermal?'22mm':'24mm'};object-fit:contain;display:block;margin:0 auto 4px}.head h1{font-size:${thermal?'16px':'22px'};margin:2px 0}.head p{margin:1px 0;font-size:${thermal?'9px':'11px'}}.title{text-align:center;font-weight:700;font-size:${thermal?'15px':'18px'};margin:7px 0}.meta{width:100%;border-collapse:collapse;margin-bottom:7px}.meta td{padding:2px 3px;border:0;font-size:${thermal?'10px':'11px'}}table.items{width:100%;border-collapse:collapse;table-layout:auto}.items th,.items td{border:1px solid #000;padding:${thermal?'3px 2px':'6px'};text-align:center;font-size:${thermal?'9px':'11px'};word-break:break-word}.items th{font-weight:700}.totals{display:flex;flex-wrap:wrap;justify-content:space-between;gap:5px;border:1px solid #000;padding:6px;margin-top:7px;font-size:${thermal?'10px':'12px'}}.notes{margin-top:7px;border-top:1px dashed #000;padding-top:5px;font-size:${thermal?'9px':'11px'}}.foot{margin-top:8px;text-align:center;font-size:${thermal?'8px':'10px'}}@media print{.no-print{display:none!important}}</style></head><body><header class="head">${logo?`<img src="${logo}" alt="">`:''}<h1>${esc(d.company.name||'الميزان برو')}</h1>${d.company.legalName?`<p>${esc(d.company.legalName)}</p>`:''}<p>${esc(d.company.phone||'')}${d.company.address?` — ${esc(d.company.address)}`:''}</p></header><div class="title">${esc(title)}</div><table class="meta"><tr><td><b>الرقم:</b> ${esc(x.number)}</td><td><b>التاريخ:</b> ${esc(x.date||'')}</td></tr><tr><td><b>من:</b> ${esc(transferFromLabel(kind,x))}</td><td><b>إلى:</b> ${esc(transferToLabel(kind,x))}</td></tr><tr><td><b>الحالة:</b> ${esc(status)}</td><td><b>المستخدم:</b> ${esc(A.currentUser()?.name||'—')}</td></tr></table><table class="items"><thead><tr><th>#</th><th>الصنف</th><th>الكمية</th><th>الوحدة</th><th>التكلفة</th><th>الإجمالي</th></tr></thead><tbody>${itemRows}</tbody></table>${extra}${x.notes?`<div class="notes"><b>ملاحظات:</b> ${esc(x.notes)}</div>`:''}${x.receiveNotes?`<div class="notes"><b>ملاحظات الفحص:</b> ${esc(x.receiveNotes)}</div>`:''}<div class="foot">${esc(d.company.name||'الميزان برو')} — ${new Date().toLocaleString('ar-EG')}</div><script>let printed=false;window.onload=()=>setTimeout(()=>{if(printed)return;printed=true;window.print()},180);window.onafterprint=()=>{try{window.close()}catch(e){}};<\/script></body></html>`);w.document.close();w.focus();
}
A.registerAction('transfer-excel-v753',b=>exportTransferExcel(b.dataset.kind,b.dataset.id));A.registerAction('transfer-pdf-v753',b=>printTransferDoc(b.dataset.kind,b.dataset.id,true));A.registerAction('transfer-print-v753',b=>printTransferDoc(b.dataset.kind,b.dataset.id,false));

function transferActionButtons(kind,id){return `<div class="table-actions transfer-doc-actions">${ib('transfer-excel-v753','excel','Excel',`data-kind="${kind}" data-id="${id}"`)}${ib('transfer-pdf-v753','pdf','PDF',`data-kind="${kind}" data-id="${id}"`)}${ib('transfer-print-v753','print','طباعة',`data-kind="${kind}" data-id="${id}"`)}</div>`}
function transfersView753(root){
 const d=D(),bm=isBranchManager(),bid=activeBranch(),reqs=(d.transferRequests||[]).filter(r=>!bm||r.fromBranchId===bid||r.toBranchId===bid),trs=(d.transfers||[]).filter(t=>!bm||t.fromBranchId===bid||t.toBranchId===bid);
 root.classList.add('v753-transfer-page');root.innerHTML=`${A.pageHead('النقل المخزني','بين الفروع أو بين مستودعات نفس الفرع',`${btn('transfer-request-v750','طلب تحويل','plus')}${btn('transfer-out-v750','سند تحويل بين فروع','transfer','btn-secondary')}${btn('internal-transfer-v753','نقل داخل الفرع','warehouse','btn-secondary')}`)}<div class="grid-2 v753-transfer-grids"><article class="panel"><div class="panel-head"><h3>طلبات التحويل بين الفروع</h3></div>${A.table(['الطلب','التاريخ','من','إلى','الأصناف','الحالة','إجراء الدورة','ملفات'],reqs.map(r=>`<tr><td><b>${esc(r.number)}</b></td><td>${A.dateFmt(r.date)}</td><td>${esc(branchName(r.fromBranchId))}</td><td>${esc(branchName(r.toBranchId))}</td><td>${r.lines?.length||0}</td><td>${A.badge(r.status==='requested'?'مطلوب':r.status==='in_transit'?'قيد النقل':'مستلم',r.status==='requested'?'amber':r.status==='in_transit'?'blue':'green')}</td><td>${r.status==='requested'&&(!bm||r.fromBranchId===bid)?`<button class="btn btn-primary btn-sm" data-action="transfer-out-from-request-v750" data-id="${r.id}">إصدار الإخراج</button>`:'—'}</td><td>${transferActionButtons('request',r.id)}</td></tr>`),A.emptyState('transfer','لا توجد طلبات',''))}</article><article class="panel"><div class="panel-head"><h3>سندات النقل</h3></div>${A.table(['السند','النوع','من','إلى','الأصناف','القيمة','الحالة','الإجراءات','ملفات'],trs.map(t=>{const internal=t.scope==='internal',from=internal?whName(t.fromId):branchName(t.fromBranchId),to=internal?whName(t.toId):branchName(t.toBranchId);return `<tr><td><b>${esc(t.number)}</b></td><td>${A.badge(internal?'داخل الفرع':'بين الفروع',internal?'primary':'blue')}</td><td>${esc(from)}</td><td>${esc(to)}</td><td>${t.lines?.length||1}</td><td>${A.money(t.totalValue||0)}</td><td>${A.badge(t.status==='in_transit'?'في الطريق':t.status==='received'?'مستلم ومقفل':'ملغي',t.status==='in_transit'?'amber':t.status==='received'?'green':'red')}</td><td><div class="table-actions">${!internal&&t.status==='in_transit'&&(!bm||t.toBranchId===bid)?`<button class="btn btn-primary btn-sm" data-action="transfer-in-v750" data-id="${t.id}">استلام</button>`:''}${!internal&&t.status==='in_transit'&&(!bm||t.fromBranchId===bid)?ib('cancel-transfer-v750','undo','عكس قبل الاستلام',`data-id="${t.id}"`):''}</div></td><td>${transferActionButtons('transfer',t.id)}</td></tr>`}),A.emptyState('transfer','لا توجد سندات',''))}</article></div>`;
}
A.registerView('transfers',transfersView753);

// ---------------- Cashier search in the exact catalog title row; survives direct re-renders ----------------
function bindCatalogSearch(box){const input=box?.querySelector('input');if(!input||input.dataset.v753Bound)return;input.dataset.v753Bound='1';input.addEventListener('input',e=>{S.cashierSearch=e.target.value;clearTimeout(S.v753SearchTimer);S.v753SearchTimer=setTimeout(()=>A.renderCurrent('cashier'),110)});input.addEventListener('keydown',e=>{if(e.key==='Escape'){e.target.value='';S.cashierSearch='';A.renderCurrent('cashier')}})}
function ensureCatalogSearch(){const root=$('#workspace');if(!root||!root.querySelector('.cashier-page'))return;const title=root.querySelector('.cashier-section-title');if(!title)return;let box=root.querySelector('.cashier-catalog-search-v752');if(!box){box=document.createElement('div');box.className='cashier-catalog-search-v752 cashier-catalog-search-v753';box.innerHTML=`${I('search',14)}<input id="cashierCatalogSearch" type="search" autocomplete="off" placeholder="بحث صنف..." value="${esc(S.cashierSearch||'')}">`;A.injectIcons(box)}else box.classList.add('cashier-catalog-search-v753');const badge=title.querySelector('.badge');if(box.parentElement!==title)title.insertBefore(box,badge||null);const input=box.querySelector('input');if(input&&document.activeElement!==input&&input.value!==String(S.cashierSearch||''))input.value=S.cashierSearch||'';bindCatalogSearch(box)}
const previousCashier=S.views.cashier;A.registerView('cashier',root=>{previousCashier?.(root);ensureCatalogSearch()});
let searchObserverBusy=false;const obs=new MutationObserver(()=>{if(searchObserverBusy)return;searchObserverBusy=true;requestAnimationFrame(()=>{searchObserverBusy=false;ensureCatalogSearch()})});const ws=$('#workspace');if(ws)obs.observe(ws,{childList:true,subtree:true});window.addEventListener('almezan:navigated',ensureCatalogSearch);setTimeout(ensureCatalogSearch,100);

window.AlMezanV753={openInternalTransfer753,openUnifiedVoucher,printTransferDoc,ensureCatalogSearch};
})();
