(function(){
  'use strict';
  const A=window.AlMezan,S=A.state,$=A.$,esc=A.esc,num=A.num,I=A.I,D=()=>A.db;

  function activePriceGroups(){return (D().priceGroups||[]).filter(x=>x.active!==false)}
  function activeCustomerGroups(){return (D().customerGroups||[]).filter(x=>x.active!==false)}
  function customerGroup(customer){const d=D();return d.customerGroups.find(x=>x.id===customer?.customerGroupId)||d.customerGroups.find(x=>x.id==='CG-RETAIL')||d.customerGroups[0]||null}
  function priceGroupForCustomer(customer){const d=D(),cg=customerGroup(customer),id=customer?.priceGroupIdOverride||cg?.priceGroupId||d.settings.defaultPriceGroupId||'PG-RETAIL';return d.priceGroups.find(x=>x.id===id)||d.priceGroups.find(x=>x.id==='PG-RETAIL')||d.priceGroups[0]||null}
  function customerDiscountPercent(customer){const cg=customerGroup(customer);return Math.max(0,num(cg?.defaultDiscountPercent)+num(customer?.extraDiscountPercent))}
  function customerCreditLimit(customer){const cg=customerGroup(customer);return num(customer?.creditLimit)>0?num(customer.creditLimit):num(cg?.defaultCreditLimit)}
  function customerPaymentTerms(customer){const cg=customerGroup(customer);return num(customer?.paymentTermsDays)>0?num(customer.paymentTermsDays):num(cg?.paymentTermsDays)}
  function itemPrice(productId,unitId,priceGroupId){return (D().itemPrices||[]).find(x=>x.productId===productId&&x.unitId===unitId&&x.priceGroupId===priceGroupId)||null}
  function priceForCustomer(product,unit,customer){
    if(!product||!unit)return 0;
    const d=D(),pg=priceGroupForCustomer(customer);let row=itemPrice(product.id,unit.id,pg?.id);
    if(!row&&product.isVariant&&product.parentId){const parent=d.products.find(x=>x.id===product.parentId),idx=(product.units||[]).findIndex(x=>x.id===unit.id),parentUnit=parent?.units?.[idx]||parent?.units?.find(x=>x.name===unit.name)||parent?.units?.[0];if(parentUnit)row=itemPrice(parent.id,parentUnit.id,pg?.id)}
    if(row&&Number.isFinite(Number(row.price)))return Math.max(0,num(row.price));
    return Math.max(0,num(unit.salePrice));
  }
  function repriceCart(customer){
    const c=customer||D().customers.find(x=>x.id===S.cashierCustomerId)||D().customers.find(x=>x.system);
    for(const line of S.cart||[]){const p=D().products.find(x=>x.id===line.productId),u=A.productUnit(p,line.unitId);if(p&&u)line.unitPrice=priceForCustomer(p,u,c)}
    S.cashierCustomerAutoDiscount=customerDiscountPercent(c);
    A.persistCart();
    return S.cashierCustomerAutoDiscount;
  }
  function refreshPricingCache(){
    const d=D(),payload={version:1,generatedAt:A.now(),priceGroups:d.priceGroups,customerGroups:d.customerGroups,itemPrices:d.itemPrices,customers:d.customers.map(c=>({id:c.id,name:c.name,phone:c.phone,customerGroupId:c.customerGroupId,priceGroupIdOverride:c.priceGroupIdOverride,extraDiscountPercent:c.extraDiscountPercent,creditLimit:c.creditLimit,paymentTermsDays:c.paymentTermsDays,active:c.active,system:c.system})),products:d.products.map(p=>({id:p.id,name:p.name,sku:p.sku,active:p.active,units:(p.units||[]).map(u=>({id:u.id,name:u.name,barcode:u.barcode,salePrice:u.salePrice}))}))};
    try{localStorage.setItem('almezan_pos_pricing_cache_v1',JSON.stringify(payload));return true}catch(_){return false}
  }

  function action(id,label,icon='plus',cls='btn-primary',attrs=''){return `<button class="btn ${cls}" data-action="${id}" ${attrs}>${I(icon)}${esc(label)}</button>`}
  function iconBtn(id,icon,title,attrs=''){return `<button class="icon-button" data-action="${id}" title="${esc(title)}" ${attrs}>${I(icon)}</button>`}

  function openCustomerGroup(group=null){
    const d=D();
    A.openModal({title:group?'تعديل مجموعة العملاء':'مجموعة عملاء جديدة',body:`<div class="form-grid"><label class="field"><span>اسم المجموعة</span><input name="name" required value="${esc(group?.name||'')}"></label><label class="field"><span>الكود</span><input name="code" required value="${esc(group?.code||'')}"></label><label class="field"><span>مجموعة الأسعار الافتراضية</span><select name="priceGroupId">${A.options(activePriceGroups(),'id','name',group?.priceGroupId||d.settings.defaultPriceGroupId)}</select></label><label class="field"><span>الحد الائتماني الافتراضي</span><input name="defaultCreditLimit" type="number" min="0" step="0.01" value="${num(group?.defaultCreditLimit)}"></label><label class="field"><span>شروط الدفع / أيام</span><input name="paymentTermsDays" type="number" min="0" step="1" value="${num(group?.paymentTermsDays)}"></label><label class="field"><span>خصم تلقائي %</span><input name="defaultDiscountPercent" type="number" min="0" max="100" step="0.01" value="${num(group?.defaultDiscountPercent)}"></label><label class="field"><span>الحالة</span><select name="active"><option value="1" ${group?.active!==false?'selected':''}>نشطة</option><option value="0" ${group?.active===false?'selected':''}>موقوفة</option></select></label></div>`,onSubmit:fd=>{
      const name=fd.get('name').trim(),code=fd.get('code').trim().toUpperCase();if(!name||!code)throw Error('اكتب اسم المجموعة والكود.');
      if(d.customerGroups.some(x=>x.id!==group?.id&&String(x.code).toUpperCase()===code))throw Error('كود مجموعة العملاء مستخدم.');
      const data={id:group?.id||A.uid('CG'),name,code,priceGroupId:fd.get('priceGroupId'),defaultCreditLimit:num(fd.get('defaultCreditLimit')),paymentTermsDays:num(fd.get('paymentTermsDays')),defaultDiscountPercent:num(fd.get('defaultDiscountPercent')),active:fd.get('active')==='1',system:group?.system||false,createdAt:group?.createdAt||A.now(),updatedAt:A.now()};
      group?Object.assign(group,data):d.customerGroups.push(data);A.audit(group?'تعديل مجموعة عملاء':'إضافة مجموعة عملاء','مجموعات العملاء',name);A.saveDB();refreshPricingCache();A.toast('تم حفظ مجموعة العملاء');A.renderCurrent();
    }})
  }
  function renderCustomerGroups(root){
    const d=D();root.innerHTML=`${A.pageHead('مجموعات العملاء','',action('add-customer-group','مجموعة جديدة'))}<section class="pricing-info-strip"><span>${I('customer')} كل مجموعة تحدد قائمة السعر والحد الائتماني وشروط الدفع والخصم التلقائي.</span></section><article class="panel">${A.table(['المجموعة','الكود','مجموعة الأسعار','الحد الافتراضي','أيام الدفع','الخصم','العملاء','الحالة','الإجراءات'],d.customerGroups.map(g=>`<tr><td><b>${esc(g.name)}</b></td><td>${esc(g.code)}</td><td>${esc(d.priceGroups.find(x=>x.id===g.priceGroupId)?.name||'—')}</td><td>${A.money(g.defaultCreditLimit)}</td><td>${num(g.paymentTermsDays)}</td><td>${num(g.defaultDiscountPercent)}%</td><td>${d.customers.filter(c=>c.customerGroupId===g.id).length}</td><td>${A.badge(g.active!==false?'نشطة':'موقوفة',g.active!==false?'green':'red')}</td><td><div class="table-actions">${iconBtn('edit-customer-group','edit','تعديل',`data-id="${g.id}"`)}${g.system?'':iconBtn('delete-customer-group','trash','حذف',`data-id="${g.id}"`)}</div></td></tr>`))}</article>`
  }

  function openPriceGroup(group=null){
    const d=D();A.openModal({title:group?'تعديل مجموعة الأسعار':'مجموعة أسعار جديدة',body:`<div class="form-grid"><label class="field"><span>اسم مجموعة الأسعار</span><input name="name" required value="${esc(group?.name||'')}"></label><label class="field"><span>الكود</span><input name="code" required value="${esc(group?.code||'')}"></label><label class="field"><span>الحالة</span><select name="active"><option value="1" ${group?.active!==false?'selected':''}>نشطة</option><option value="0" ${group?.active===false?'selected':''}>موقوفة</option></select></label></div>`,onSubmit:fd=>{const name=fd.get('name').trim(),code=fd.get('code').trim().toUpperCase();if(!name||!code)throw Error('اكتب الاسم والكود.');if(d.priceGroups.some(x=>x.id!==group?.id&&String(x.code).toUpperCase()===code))throw Error('الكود مستخدم لمجموعة أسعار أخرى.');const data={id:group?.id||A.uid('PG'),name,code,active:fd.get('active')==='1',system:group?.system||false,createdAt:group?.createdAt||A.now(),updatedAt:A.now()};group?Object.assign(group,data):d.priceGroups.push(data);A.audit(group?'تعديل مجموعة أسعار':'إضافة مجموعة أسعار','مجموعات الأسعار',name);A.saveDB();refreshPricingCache();A.toast('تم حفظ مجموعة الأسعار');A.renderCurrent()}})
  }
  function priceMatrix(groupId){
    const d=D(),group=d.priceGroups.find(x=>x.id===groupId);if(!group)return;
    const rows=d.products.filter(p=>p.active!==false).flatMap(p=>(p.units||[]).map(u=>({p,u,row:itemPrice(p.id,u.id,groupId)})));
    A.openModal({title:`أسعار: ${group.name}`,size:'modal-xl',body:`<div class="price-matrix-toolbar"><span>${I('card')} اترك السعر فارغاً لاستخدام سعر البيع الأساسي.</span><button type="button" class="btn btn-secondary btn-sm" data-action="bulk-price-adjust" data-id="${group.id}">${I('calculator')} تعديل جماعي %</button></div><div class="table-wrap"><table class="data-table price-matrix"><thead><tr><th>الصنف</th><th>الوحدة</th><th>السعر الأساسي</th><th>سعر ${esc(group.name)}</th></tr></thead><tbody>${rows.map(({p,u,row})=>`<tr><td><b>${esc(p.name)}</b><small>${esc(p.sku||'')}</small></td><td>${esc(u.name)}</td><td>${A.money(u.salePrice)}</td><td><input class="matrix-price" data-product="${p.id}" data-unit="${u.id}" type="number" min="0" step="0.01" placeholder="${num(u.salePrice).toFixed(2)}" value="${row?num(row.price):''}"></td></tr>`).join('')}</tbody></table></div>`,submitText:'حفظ قائمة الأسعار',onSubmit:(fd,form)=>{for(const inp of A.$$('.matrix-price',form)){const productId=inp.dataset.product,unitId=inp.dataset.unit,val=String(inp.value).trim(),existing=itemPrice(productId,unitId,groupId);if(val===''){if(existing)d.itemPrices=d.itemPrices.filter(x=>x!==existing);continue}const price=Math.max(0,num(val));if(existing)existing.price=price;else d.itemPrices.push({id:A.uid('IPR'),productId,unitId,priceGroupId:groupId,price,createdAt:A.now()})}A.audit('تحديث قائمة أسعار','مجموعات الأسعار',group.name);A.saveDB();refreshPricingCache();A.toast('تم تحديث أسعار المجموعة');A.renderCurrent()}})
  }
  function renderPriceGroups(root){
    const d=D();root.innerHTML=`${A.pageHead('مجموعات الأسعار','',`${action('add-price-group','مجموعة أسعار جديدة')}${action('refresh-pricing-cache','تحديث كاش POS','refresh','btn-secondary')}`)}<section class="pricing-group-grid">${d.priceGroups.map(g=>`<article class="pricing-group-card"><div class="pricing-group-head"><span class="summary-icon">${I('card')}</span><div><h3>${esc(g.name)}</h3><small>${esc(g.code)}</small></div>${A.badge(g.active!==false?'نشطة':'موقوفة',g.active!==false?'green':'red')}</div><div class="pricing-group-stats"><span><small>أسعار مخصصة</small><b>${d.itemPrices.filter(x=>x.priceGroupId===g.id).length}</b></span><span><small>مجموعات عملاء</small><b>${d.customerGroups.filter(x=>x.priceGroupId===g.id).length}</b></span></div><div class="actions"><button class="btn btn-primary btn-sm" data-action="edit-price-matrix" data-id="${g.id}">${I('edit')} تحرير الأسعار</button><button class="btn btn-secondary btn-sm" data-action="assign-price-customers" data-id="${g.id}">${I('customer')} العملاء</button><button class="btn btn-secondary btn-sm" data-action="edit-price-group" data-id="${g.id}">${I('settings')} المجموعة</button>${g.system?'':`<button class="icon-button" data-action="delete-price-group" data-id="${g.id}" title="حذف">${I('trash')}</button>`}</div></article>`).join('')}</section>`
  }
  function assignCustomersToPriceGroup(groupId){
    const d=D(),g=d.priceGroups.find(x=>x.id===groupId);if(!g)return;
    const customers=d.customers.filter(c=>!c.system&&c.active!==false);
    A.openModal({title:`عملاء مجموعة الأسعار — ${g.name}`,size:'modal-lg',body:`<div class="price-customer-search"><span>${I('search',15)}</span><input id="priceCustomerSearch" type="search" placeholder="بحث بالاسم أو الهاتف..."></div><div id="priceCustomerList" class="price-customer-list">${customers.map(c=>`<label class="price-customer-item" data-search="${esc((c.name+' '+(c.phone||'')).toLowerCase())}"><input type="checkbox" name="customerId" value="${c.id}" ${c.priceGroupIdOverride===g.id?'checked':''}><span><b>${esc(c.name)}</b><small>${esc(c.phone||'')} — ${esc(customerGroup(c)?.name||'بدون مجموعة')}</small></span></label>`).join('')||'<div class="custom-select-empty">لا يوجد عملاء</div>'}</div>`,submitText:'حفظ ربط العملاء',onSubmit:fd=>{const selected=new Set(fd.getAll('customerId'));for(const c of customers){if(selected.has(c.id))c.priceGroupIdOverride=g.id;else if(c.priceGroupIdOverride===g.id)c.priceGroupIdOverride=''}A.audit('ربط عملاء بمجموعة أسعار','مجموعات الأسعار',`${g.name} — ${selected.size} عميل`);A.saveDB();refreshPricingCache();A.toast('تم تحديث ربط العملاء بمجموعة الأسعار');A.renderCurrent()},afterOpen:form=>{const inp=A.$('#priceCustomerSearch',form);inp.oninput=e=>{const q=e.target.value.trim().toLowerCase();A.$$('.price-customer-item',form).forEach(row=>row.hidden=!!q&&!row.dataset.search.includes(q))}}})
  }

  function bulkAdjust(groupId){const d=D(),g=d.priceGroups.find(x=>x.id===groupId);if(!g)return;A.openModal({title:`تعديل جماعي — ${g.name}`,body:`<div class="form-grid"><label class="field"><span>نسبة التغيير %</span><input name="percent" type="number" step="0.01" value="5" required></label><label class="field"><span>طريقة التغيير</span><select name="direction"><option value="increase">زيادة</option><option value="decrease">تخفيض</option></select></label></div>`,submitText:'تطبيق على جميع الأصناف',onSubmit:fd=>{const pct=Math.abs(num(fd.get('percent'))),factor=fd.get('direction')==='decrease'?1-pct/100:1+pct/100;if(factor<0)throw Error('نسبة التخفيض كبيرة جداً.');for(const p of d.products)for(const u of p.units||[]){const current=itemPrice(p.id,u.id,groupId),base=current?num(current.price):num(u.salePrice),price=Number((base*factor).toFixed(2));current?current.price=price:d.itemPrices.push({id:A.uid('IPR'),productId:p.id,unitId:u.id,priceGroupId:groupId,price,createdAt:A.now()})}A.audit('تعديل جماعي للأسعار','مجموعات الأسعار',`${g.name}: ${fd.get('direction')} ${pct}%`);A.saveDB();refreshPricingCache();A.toast('تم تطبيق التعديل الجماعي');priceMatrix(groupId)}})}

  A.customerGroup=customerGroup;A.priceGroupForCustomer=priceGroupForCustomer;A.customerDiscountPercent=customerDiscountPercent;A.customerCreditLimit=customerCreditLimit;A.customerPaymentTerms=customerPaymentTerms;A.itemPrice=itemPrice;A.priceForCustomer=priceForCustomer;A.repriceCart=repriceCart;A.refreshPricingCache=refreshPricingCache;
  A.registerView('customer-groups',renderCustomerGroups);A.registerView('price-groups',renderPriceGroups);
  A.registerAction('add-customer-group',()=>openCustomerGroup());A.registerAction('edit-customer-group',b=>openCustomerGroup(D().customerGroups.find(x=>x.id===b.dataset.id)));A.registerAction('delete-customer-group',b=>{const d=D(),g=d.customerGroups.find(x=>x.id===b.dataset.id);if(!g||g.system)return;if(d.customers.some(c=>c.customerGroupId===g.id))return A.toast('لا يمكن حذف مجموعة مرتبطة بعملاء.','warning');A.confirmDialog('حذف مجموعة العملاء',g.name,()=>{d.customerGroups=d.customerGroups.filter(x=>x.id!==g.id);A.saveDB();refreshPricingCache();A.renderCurrent()})});
  A.registerAction('assign-price-customers',b=>assignCustomersToPriceGroup(b.dataset.id));
  A.registerAction('add-price-group',()=>openPriceGroup());A.registerAction('edit-price-group',b=>openPriceGroup(D().priceGroups.find(x=>x.id===b.dataset.id)));A.registerAction('edit-price-matrix',b=>priceMatrix(b.dataset.id));A.registerAction('bulk-price-adjust',b=>bulkAdjust(b.dataset.id));A.registerAction('delete-price-group',b=>{const d=D(),g=d.priceGroups.find(x=>x.id===b.dataset.id);if(!g||g.system)return;if(d.customerGroups.some(c=>c.priceGroupId===g.id)||d.customers.some(c=>c.priceGroupIdOverride===g.id))return A.toast('لا يمكن حذف مجموعة أسعار مرتبطة بعملاء.','warning');A.confirmDialog('حذف مجموعة الأسعار',g.name,()=>{d.priceGroups=d.priceGroups.filter(x=>x.id!==g.id);d.itemPrices=d.itemPrices.filter(x=>x.priceGroupId!==g.id);A.saveDB();refreshPricingCache();A.renderCurrent()})});
  A.registerAction('refresh-pricing-cache',()=>{refreshPricingCache();A.toast('تم تحديث كاش الأسعار للعمل دون إنترنت')});
  refreshPricingCache();
})();
